### ISSUE TITLE
Drop down apis for applications and environments

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#1043]
# Summary

- Drop down api for fetch devtron application and devtron charts, used in user access section and more.
- Environments list combined with clusters and namespaces for helm type permissions.

# Proposal

- applications list filtered by project id, existing api need to modify with extra request param for helm apps.
- new apis for environments group by clusters and combined with db environments and cluster/namespaces.

**Comment by prakarsh-dt** [comment]
Closing as the PRs linked are meged
