### ISSUE TITLE
Feature: Allow user to change project for application.

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#1058]
# Summary

- Allow user to change project for application.

AB#469

**Comment by ankit-ls** [comment]
We have a usecase where as part of org restructuring, we want to change the ownership of an app to a different project.

@vikramdevtron @nishant-d Can we prioritise this? Or is this a bigger effort?

**Comment by vikramdevtron** [comment]
Hi @ankit-ls this feature was in our todo list. this has impact on user permissions which are associated with modified project.  
Will planning to pick this in parts, where we can allow users to change the project for an app
We will definitely consider it for higher priority. will get back to you once this resolve.

**Comment by prakarsh-dt** [comment]
Fixed by #2365
