### ISSUE TITLE
kube-capacity

### ISSUE THREAD

**Issue by aviralsrivastava01** [devtron-labs/devtron#1070]
* An overview of the resource requests, limits, and utilisation in a Kubernetes cluster.
* To find out the nodes with the total CPU and Memory resource requests and limits for all the pods running on them.
* Find out the  total available resources on the node.

**Comment by kartik-579** [comment]
updated estimated time with introduction of dependency versions problem and increased testing scope

**Comment by kartik-579** [comment]
reverted time estimation, will create separate tickets with plan for new scope
