### ISSUE TITLE
UX: Allow user to change branch before triggering a build from the trigger page

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1077]
# Summary

In below user flows allow user to do the following:

1. Configuring build pipeline: Define a regex for branch name while configuring a Build Pipeline.
2. Triggering build pipeline: Select from branches matching the configured regex.

# Motivation

Currently the user has to go to the config page, change branch and then come back and retrigger. Providing them at same place would allow user to do it with fewer clicks.

# Proposal

https://www.figma.com/file/bh763czmqOCxwv4PYustlq/?node-id=1013%3A2984

**Comment by nishant-d** [comment]
automatic ci will be triggered based on last manually updated branch name at trigger time .

**Comment by pghildiyal** [comment]
User with deploy access will be able to change branch name conforming to regex from trigger page
