### ISSUE TITLE
FIX: Broken links of Docs in Dashboard

### ISSUE THREAD

**Issue by arushi09-hub** [devtron-labs/devtron#1089]
Two broken documentation links found in Devtron dashboard(Global configurations - Project and Notifications) in "Learn more about projects" & "learn more about notifications"

**Screenshots**

> 
<img width="1440" alt="Screenshot 1943-10-20 at 2 50 15 PM" src="https://user-images.githubusercontent.com/64471469/148748552-8ce8b0f5-11f0-4aba-87f0-f6a14c2b9776.png">
<img width="1440" alt="Screenshot 1943-10-20 at 3 38 42 PM" src="https://user-images.githubusercontent.com/64471469/148748724-e45cbe3b-ae26-4035-9e9a-f2c4de4eade1.png">

**Comment by uxarya-d** [comment]
Doc link also broken for:
[] Workflow Editor

**Comment by uxarya-d** [comment]
Links working fine. Verified.
