### ISSUE TITLE
Minio storage configuration override.

### ISSUE THREAD

**Issue by TheAnachronism** [devtron-labs/devtron#1093]
# Summary

Currently with the installation method with minio 4 persistent volume get created which have a fixed size of 50GB. That wouldn't really be a problem for large production clusters but I think there should be an option to override that value so it could be reduced to lets say 10 GB.

# Motivation

I was testing around with that on a 5 node bare-metal cluster and all my nodes have around 120-200 GB of storage. When installing devtron my storage class (longhorn) couldn't create more volumes because the 4 * 50 GB completely took the 200 GB of available, schedulable storage.
Reducing the entire thing to 10 or whatever I'd like to would easily solve the problem.

# Proposal

I don't know if the same override method for other configuration parts could be used but it would certainly be nice if it could be made in devtron-minio-storage-override.yaml.

AB#457

**Comment by pawan-mehta-dt** [comment]
This is configurable in devtron chart values.yaml now
You can set minio.persistence.storage=10Gi or whatever you want to set for the same
