### ISSUE TITLE
Github authenticator for the token

### ISSUE THREAD

**Issue by snehith57624** [devtron-labs/devtron#1104]
make a sample application which gets token for GitHub account

**Comment by snehith57624** [comment]
[https://app.zenhub.com/files/302922505/31cbc4aa-850d-4853-a14e-11f75b4e27b2/download](https://app.zenhub.com/files/302922505/31cbc4aa-850d-4853-a14e-11f75b4e27b2/download)

**Comment by snehith57624** [comment]
Document version[https://app.zenhub.com/files/302922505/1bae355d-879d-4faa-b5ab-8a1397f84d12/download](https://app.zenhub.com/files/302922505/1bae355d-879d-4faa-b5ab-8a1397f84d12/download)

**Comment by snehith57624** [comment]
https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/

**Comment by snehith57624** [comment]
https://docs.google.com/document/d/1cDfjjhBUZIZD0TNq-TFeUq4Nf1UwFrtnRTT_4-W4Seo/edit?usp=sharing

**Comment by manish-agrawal-ai** [comment]
changed assignee from Snehith to Nishant
