### ISSUE TITLE
Security scan is not visible on trigger page

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1105]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

I enabled image scanner on my app and it scanning is working fine I can see all the scans in build history but am not able to see the same on the trigger section.

**Expected behavior**

Security scan should be there in the trigger section while selecting the image to deploy.

**Current behavior** 

It is available on the build history page but not in the trigger section.

**Screenshots**
Trigger section
<img width="1438" alt="Screenshot 2022-01-18 at 4 41 12 PM" src="https://user-images.githubusercontent.com/85476803/149927495-2d65fd6a-9606-43f4-9248-e25e10c84e0e.png">

Build history page
<img width="1438" alt="Screenshot 2022-01-18 at 4 41 30 PM" src="https://user-images.githubusercontent.com/85476803/149927594-2ac96c94-91c6-459c-8b76-546eecca6717.png">

**Comment by anupdhiran** [comment]
merged.
