### ISSUE TITLE
Vulnerability scanning hasn’t been enabled for this build pipeline

### ISSUE THREAD

**Issue by MazenElzanaty** [devtron-labs/devtron#1107]
Checklist:

* ✅ I've searched in the docs and FAQ for my answer
* ✅ I've included steps to reproduce the bug.

**Describe the bug**

After enabling "Scan for vulnerabilities" in the build pipeline and the pipeline succeeded and the image pushed to registry, When I check the security tab I get "Vulnerability scanning hasn’t been enabled for this build pipeline".

**To Reproduce**

1. Deploy devtron version "4555196b-146-6310" and devtron dashboard version "075cba2a-136-6172"
2. Create build pipeline and enable "Scan for vulnerabilities"
3. Run the pipeline
4. After it finishes, check the security tab

**Expected behavior**

I should see scan results

**Current behavior** 

I get "Vulnerability scanning hasn’t been enabled for this build pipeline" in the security tab

**Screenshots**

![image](https://user-images.githubusercontent.com/25989948/150176490-891628c7-ab7d-47c8-ad6d-811755b08c40.png)

![image](https://user-images.githubusercontent.com/25989948/150176592-c1e02429-4607-48f4-94ad-b70d4403880d.png)

**Comment by kartik-579** [comment]
fixed in #1438
