### ISSUE TITLE
Create an API for getting deployment yaml separately for each deployment

### ISSUE THREAD

**Issue by snehith57624** [devtron-labs/devtron#1137]
for version 2 of EA, we need to make separate api to get the manifest separately as the info might be large rather than fetching all deployment history along with the manifest.

**Comment by manish-agrawal-ai** [comment]
changed assignee from Snehith to Nishant

**Comment by manish-agrawal-ai** [comment]
Duplicate of https://github.com/devtron-labs/devtron/issues/1154
