### ISSUE TITLE
Make readme accessible from deployment template

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1138]
# Summary

Users do not have clear understanding about a specific version of  Deployment template and its details. They can be helped with a version and type specific readme. Also, to provide details of the fields in template. 

# Proposal

Along with the chart values and version, send readme and schema.json file (details of fields). The details in schema.json will be - 

description
markdownDescription
title
enum

**Comment by anupdhiran** [comment]
Back end work to be tracked in this ticket and create separate ticket for FE work
