### ISSUE TITLE
[Hyperion] [FE] Breakdown deployment history API to solve grpc max size error

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#1155]
Breakdown deployment history API to solve grpc max size error.

- Fetch YAMLs lazily instead of on page load using new API - `application/deployment-detail`.
- Add `values.yaml` & rename `Applied YAML` to `Helm generated manifest`.
- Add error handling view

**Comment by sohel-rp** [comment]
Changes have been made and are under review.
Related PR: https://github.com/devtron-labs/dashboard/pull/293.
