### ISSUE TITLE
[Hyperion] [FE] Namespace filter multiple issues fix on app list

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#1156]
- Selecting one more cluster from the list is clearing out all selected namespaces from the filter
- If multiple clusters are selected & no namespaces are selected for any cluster and applied then it's clearing out the cluster from the filter
- Removing namespaces from the filter is clearing out the respective cluster when multiple clusters are selected

**Comment by sohel-rp** [comment]
Changes have been made and are under review.
Related PR: https://github.com/devtron-labs/dashboard/pull/292.
