### ISSUE TITLE
Application with app-metrics enabled gets timeout after 15 seconds.

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1183]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

One of our app takes more than 15 seconds to get response from the API but if app-metrics are enabled on the app, it gets timed out after 15 seconds no matter what timeout we define. This happens due to envoy default `Route Timeout` which is `15 seconds` by default.
[Route Timeout](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#route-timeouts)

**To Reproduce**

1. Deploy an app with app-metrics enabled
2. Hit an endpoint which takes more than 15 seconds to respond
3. It will end the connection after 15 seconds
4. Disable app-metrics and deploy again
5. Hit the same endpoint again and you'll get required response this time without any issues even if it takes more than 15 seconds

**Expected behavior**

It shouldn't timeout even with app-metrics enabled or route-timeout should be configurable

**Current behavior** 

Due to route-timeout the application couldn't take time as needed to provide the response

AB#436

**Comment by pawan-59** [comment]
Fixed in PR [#1226](https://github.com/devtron-labs/devtron/pull/1226)
