### ISSUE TITLE
UX: revisit app configuration to improve adoption

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1192]
# Summary

Currently, there are multiple configuration sections that seem complicated and might be confusing to user.
The goal is to identify such areas and simplify them with better defaults, simpler terminologies, contextual help etc.

# Proposal

https://docs.google.com/document/d/1x1WB7uKmOUCGTzuqzZrroQwf1muTEKPIyXa8M9fHTkw/edit?usp=sharing

**Comment by anupdhiran** [comment]
Completed
