### ISSUE TITLE
Panic error when versioning not enabled on Azure blob storage.

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1202]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

When installating Devtron with Azure Blob Storage, ci-runner fails to download cache when versioning isn't enabled. The error logs are misleading and shows null pointer reference in memory. ci-runner fails with panic error and doesn't recover itself

**To Reproduce**

1. Install Devtron with Azure Blob storage
2. Do not enable versioning on the blobs
3. Run ci for 2-3 times

**Expected behavior**

If not able to download cache, it should print the specific message and continue with the build

**Current behavior** 

It fails with a panic error

AB#440

**Comment by ShashwatDadhich** [comment]
Fixed
