### ISSUE TITLE
Global Config > Container registry experience optimisation

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1212]
# Summary

Add more container registry type

# Motivation

To enhance user's experience

# Proposal

We will be adding some more registry type so that user will have wider option to choose.
Link some documents for getting started and help

https://docs.google.com/document/d/11y6fsApTlwiF2O2Y3zq_xKfC46y_AjvfSbffSJSb1FQ/edit#heading=h.qmruscccwzu

**Comment by vivek-devtron** [comment]
Merged
