### ISSUE TITLE
Global config > Git account enable/disable switch doesn't work if git account is expanded.

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1213]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

In global configuration, git account enable/disable switch doesn't work when git account is expanded.

![Screenshot 2022-02-10 at 6.16.03 PM.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/79a3e205-516a-4416-af07-4cb825abd438)

**To Reproduce**

1. Navigate to Global Configuration > Git Accounts
2. Expand any saved git account
3. Toggle the switch to enable/disable the git account.
4. Reload page

**Expected behavior**

Upon clicking on the toggle switch:
1. Enabled/Disabled state should be applied/saved
2. A toast should be shown, based on the action(enable/disable) performed.
Git account enabled
OR
Git account disabled

**Current behavior** 

The switch moves to enabled/disabled state but the change is not applied.
Refreshing the page after toggling the switch shows the previously saved state.

AB#431

**Comment by rish2320** [comment]
https://github.com/devtron-labs/dashboard/pull/1179
