### ISSUE TITLE
AppList: Add hover state on create app button

### ISSUE THREAD

**Issue by sohel-rp** [devtron-labs/devtron#1215]
1. Open Create app dropdown on hovering on [+Create App] button instead of clicking on it
2. User should be able to click on items in the dropdown
3. Dropdown should not close unless the cursor/pointer moves out of the button or dropdown area
4. Dropdown should not open/close on the [+Create App] button click 

<img width="531" alt="Screenshot 2022-09-10 at 4 27 35 PM" src="https://user-images.githubusercontent.com/73632042/189480234-f85960d7-0a96-4d00-b02a-2d1c04b005e1.png">

AB#428

**Comment by uxarya-d** [comment]
Not required anymore

**Comment by Suraj-kumar00** [comment]
Hi @sohel-rp, is this issue still open and can I work on this.

**Comment by uxarya-d** [comment]
Hi @Suraj-kumar00, we're not looking at changing this interaction as of now.
You could look at some `good first issues` here: https://github.com/devtron-labs/devtron/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
