### ISSUE TITLE
While creating new app it takes too long to load project.

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1268]
When I tried to create a new app it takes too long to load the project in a large org.
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Expected behavior**

Projects should appear in a fraction of time.

**Current behavior** 
It is taking too long to load projects

**Screenshots**

<img width="400" alt="Screenshot 2022-02-24 at 11 59 45 AM" src="https://user-images.githubusercontent.com/85476803/155470463-28f21624-b613-446f-9188-f315dbdd2f3d.png">

**Comment by uxarya-d** [comment]
- Decouple project dropdown from template dropdown
- Allow user to move ahead with blank template even if apps haven’t been fetched.
- Project as well as App dropdown should be typeahead search (fetch matching apps on typing)
- Loader in dropdowns when fetching results (Currently, it shows no results found)

**Comment by vivek-devtron** [comment]
Merged
