### ISSUE TITLE
Expose sentry dsn through environment variable for dashboard

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#1277]
# Summary

Expose sentry dsn through environment variable for dashboard

# Motivation

this will help us in configuring dsn through environment variable, currently its hardcoded in our code.  

# Proposal

expose `SENTRY_DSN` environment varibale like `SENTRY_ENV` and `SENTRY_ENABLED` flags

**Comment by vivek-devtron** [comment]
Merged
