### ISSUE TITLE
Warning Icon is bigger than expected

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#1280]
# Description 

In Discover, The size of the error icon is larger than it should.

![Screenshot 2022-02-28 at 9.38.33 AM.png](https://images.zenhubusercontent.com/6019150c4e513fef37b40730/1037a20b-a4ac-412f-8478-9692bf997603)
![Screenshot 2022-02-28 at 9.36.28 AM.png](https://images.zenhubusercontent.com/6019150c4e513fef37b40730/ecf49182-81da-4426-80b2-0be6699379c8)

**Comment by milindk8** [comment]
Warning icon size fixed
