### ISSUE TITLE
[Hyperion] Add Support for rollback release for helm-app release (external and internal)

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#1281]
# Summary
Enhancement for adding provision of rollback a helm release to a particular version. This should be applicable for both types of helm apps (Installed from helm cli and installed from app store in hyperion mode)

**Comment by uxarya-d** [comment]
### Proposal

https://github.com/devtron-labs/devtron/issues/1284

**Comment by manish-agrawal-ai** [comment]
API Spec : 
https://github.com/devtron-labs/devtron/blob/hyp_1281/specs/api-spec.yaml
