### ISSUE TITLE
Change the dropdown item selection UX/UI

### ISSUE THREAD

**Issue by sohel-rp** [devtron-labs/devtron#1285]
# Summary

Highlight the whole background upon selection or already selected item from dropdown instead of showing `tick` mark. This needs to be done throughout the app (in all views).

# Motivation

The current selection shows a `tick` mark on the left side occupying some space that can be utilized by the item label itself.

# Proposal

**Existing Selection** ->
![Existing_Selection.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/7762eecb-4010-4653-b0b2-2a3ad47e7f53)

**Expected UX/UI** ->
![New_UX.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/63af1d8f-0c02-4207-b547-ed558b3884fc)

**Comment by uxarya-d** [comment]
Proposed UI
![Screenshot 2022-03-03 at 10.42.05 AM.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/61b75708-178f-426c-a54b-3e82ba0bbfa5)
