### ISSUE TITLE
Able to deploy multiple charts with duplicate name.

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#1290]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [X] I've included steps to reproduce the bug.

**Describe the bug**

Select any number of a chart by clicking on `+` sign. Deploy all the charts in same project and environment with same name for all copies of the charts. It will get deployed but it shouldn't. Also when I delete on of the instance, it shows not `NOT FOUND` for all the remaining instances. But it keep showing in `Helm Apps` section with no app details.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Go to charts section
2. select any chart and any number of instances by clicking on `+` sign.
3. Click on ` Deploy To...` button present on lower-right corner.
4. Select `Project` and `Environment` 
5. Give same name for all the chart instances.
6. Deploy charts.
7. Delete any one of the instances.
8. You'll not be able to delete any of the remaining instances.

**Expected behavior**

Should not be able to deploy multiple instances of charts with duplicate name.

**Current behavior** 

Able to deploy multiple instances of charts with duplicate name.

**Screenshots**

![helm-app-duplicate-name](https://user-images.githubusercontent.com/87755583/155944373-8497a6c0-4249-405d-849d-71abd17032e3.png)
![helm-app-duplicate-name-1](https://user-images.githubusercontent.com/87755583/155945016-4883f284-9e4f-401e-9cc9-9568c8b6b88c.png)
![helm-app-duplicate-delete](https://user-images.githubusercontent.com/87755583/155945116-408d0253-5d5b-46ce-a7c3-af2f03faa8c7.png)

![helm-app-duplicate-2](https://user-images.githubusercontent.com/87755583/155945852-0f676891-6f06-4262-b21a-9df721a574a3.png)

**Logs**
 
```
Paste any relevant application logs here.
```

AB#387

**Comment by uxarya-d** [comment]
# Proposal

If multiple instances of the same chart are added in multi-chart deploy flow:
1. Default app name: Append number in the default app name. Eg. airflow1, airflow2, airflow3 [Refer screenshot]
2. Validation: Do not allow deployment if same name is provided for multiple applications. Show error toast "Multiple applications cannot have same name"

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/73632042/189479249-696ee20d-7bd6-4c70-a222-ce7c22137fcf.png">
