### ISSUE TITLE
Feat : Show Deployment history for devtron chart (installed in full mode in gitops way)

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#1297]

**Comment by vikramdevtron** [comment]
Todo 
- Build history build and store
- Status update for each build history
- Unit testing and cases
- Integration and testing
- Review changes if any

Direct impact area:
- Create, Update, Upgrade
- Direct, Bulk, Default Trigger 

- Full mode/Ea mode E2E Testing
