### ISSUE TITLE
Add Support for rollback release for non-hyperion-app release (gitops way)

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#1298]

**Comment by vikramdevtron** [comment]
# Summary
User not able to go back to previous values as we don't have build history. required a api where user can deploy again a specific older version.

# Motivation
User should able to rollback specific older version of deployment history.


# Proposal
We have build history for each deploy, create a api and take a build history id to re-deploy.

# Testing Guideline [Optional]

General API test and Deploy Action.
