### ISSUE TITLE
Unable to see Helm app without superadmin permission

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#1300]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [X] I've searched in the docs and FAQ for my answer
* [X] I've included steps to reproduce the bug.

**Describe the bug**

If a user don't have superadmin permissions but have access to some of the helm apps, but still he can't see the Helm apps for which he has the permissions.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Uncheck ` Allow superadmin permissions` from a user
2. Give to some of the helm charts (any project/environment/application) and save.
3. Go to helm apps section.
4. You'll not see any of the helm charts there.

**Expected behavior**

Helm apps should be there for which user have access

**Current behavior** 

User cannot access any of the helm  apps for which he have permissions.

**Screenshots**

**Logs**
 
```
Paste any relevant application logs here.
```

**Comment by prakarsh-dt** [comment]
Unable to reproduce the issue. Are you expecting non-devtron apps to get displayed without selecting the cluster?
