### ISSUE TITLE
[Chart Repositories]"Add repository" Button should disable until we save or cancel the repo information

### ISSUE THREAD

**Issue by devtron-deepak** [devtron-labs/devtron#1305]
**steps to replicate the bug**

1. Go to Dashboard > Global Configurations > Chart Repositories
2.  Click on "Add repository" button 
3. Enter the repo information
4. Click on "Add repository" button again( this can happen by mistake as well)

**Actual Output**
All data we enter gets delete 

**Expected Output**
"Add repository" button should disable until we save of cancel the information

**Comment by uxarya-d** [comment]
This issue has been fixed.

**Comment by uxarya-d** [comment]
This issue has been fixed.
