### ISSUE TITLE
Readme modal > Make code-editor height dynamic based on available screen size

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1318]
# Summary

Currently, the code editor height in the readme modal is fixed to a numeric value. We need to make the code-editor height dynamic based on available screen size.

# Motivation

Having a fixed height limits us from providing an optimum user experience while editing the readme.
We are unable to leverage the available screen height in larger screens as shown below.

Please give examples of your use case, e.g. when would you use this.
![image.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/c3dce140-6ba5-4922-8888-82b4174c4b85)

# Proposal

The modal should occupy the available screen height, leaving 40px margin from top and bottom of the screen.
Accordingly, the code editor should scale vertically to leaverage the available height.

**Comment by milindk8** [comment]
Added dynamic feature for code-editor & ( readme | manifest | charts ) code editor are now dynamic.
