### ISSUE TITLE
[Hyperion] [FE+BE] If the helm release is uninstalled from the terminal then Deployment list on chart detail page give error if helm app is deployed from devtron UI

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#1343]
# Summary

If the helm release is installed from devtron app store, and if release gets uninstalled from terminal, then on chart detail page, deployment list gets stuck on loading.

<img width="1354" alt="Screenshot 2022-03-11 at 12 31 11 PM" src="https://user-images.githubusercontent.com/85211469/157818373-61cb6ef6-65fc-44a7-b88b-0d8f9210a427.png">

**Error in the  API :** 
_{"code":500,"status":"Internal Server Error","errors":[{"code":"000","internalMessage":"[{rpc error: code = Unknown desc = release: not found}]","userMessage":"rpc error: code = Unknown desc = release: not found"}]}_

# Proposal
UI should show the release with status "Not Found" like we do for argo cd apps

**Comment by anupdhiran** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/1343?planning-poker) with ZenHub @nishant-d @vikramdevtron @kartik-579 @manish-agrawal-ai
