### ISSUE TITLE
[BE] Devtron APIs authentication using API keys

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#1344]
# Summary

API key authentication for Devtron APIs so that users have more flexibility in integrating and interacting with devtron pipelines.

# Motivation

In some use cases I might want to trigger a release after a certain test case has passed/failed. Interacting with Devtron APIs will enable us to do the same.

# Proposal

Current APIs use token based authentication, we need to implement an API key based authentication to make it usable for the users.

**Comment by anupdhiran** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/1344?planning-poker) with ZenHub @nishant-d @snehith57624 @kartik-579 @manish-agrawal-ai @vikramdevtron
