### ISSUE TITLE
[Hyperion] [FE] Manifest changes are getting lost when switching tabs.

### ISSUE THREAD

**Issue by sohel-rp** [devtron-labs/devtron#1346]
Checklist:
* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Manifest changes made through the live manifest (/edit mode) are getting lost when switching between tabs.

**To Reproduce**

- Go to **Helm AppList** (Applications) 
- Then select any app and go to the **AppDetails** page
- Open the Manifest tab for Pod or Deployment.
- Click **Edit Live manifest** under **Live Manifest** inner tab and make some changes without saving
- Switch to a different tab. E.g. K8s Resources
- Then go back to opened tab and observe - all changes made in Manifest are getting lost.

**Expected behavior**

Should maintain the changes made in edit mode

**Current behavior** 

As mentioned in the description.

AB#335

**Comment by jatin-jangir-0220** [comment]
found similar issue, the chart repo got changed when deploying helm charts and switching tabs.
In one app the helm repo chart got changed.

**Comment by abhibhaw** [comment]
Fixed with attached PR
