### ISSUE TITLE
Deployment Template should support a diff between current and previously deployed values

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#1373]
# Summary

Deployment Template should support a `diff` between the current and previously deployed versions.

# Motivation

Currently, Deployment Template only shows the last saved configurations. It may happen that a user modified the Deployment Template and did not deploy it. Now when another user wants to check the latest deployed configurations, he/she will intuitively refer to the previously saved Deployment Template. Now this might be different than the one which is currently deployed. This causes confusions for the user and it might take sometime for the user to realise that the deployed configs are different from the one saved in Deployment Template.

# Proposal

We are proposing a simple `git diff` based solution, which should be able to show the realtime `diff` between the currently saved Deployment Template and the last deployed one. Additionally, it would help if this could fetch the last 10 deployed configs (maybe from git), and give an option to the user to check the `diff` between any 2 of those versions.

AB#327

**Comment by ankit-ls** [comment]
@nishant-d @pghildiyal I think we had discussed this last year, but let me know your thoughts on this feature request.

**Comment by uxarya-d** [comment]
@ankit-ls We're working on a feature that should cater to your issue. (PFA screenshot for reference)
Part of it should be available as soon as next week.

<img width="1265" alt="Screenshot 2022-03-18 at 3 34 38 PM" src="https://user-images.githubusercontent.com/73632042/158982976-ec7ca633-5286-4207-a582-030cea964c9c.png">

**Comment by ankit-ls** [comment]
Oh nice! This looks even better than I was thinking. 😄 Waiting eagerly for it. 🚀

**Comment by anupdhiran** [comment]
As per confirmation from Ankit, closing this ticket as resolved
