### ISSUE TITLE
Buildx support in CI pipelines

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#1377]
# Summary

We would like to have docker [buildx](https://docs.docker.com/buildx/working-with-buildx) in the CI step, which would help us build multi-platform images with Devtron (which can run within `amd`, `arm` etc processors).

# Motivation

Presently, Devtron runs CI pipelines with `docker build` command which we think is hardcoded as part of CI step. We would want to use `docker buildx` command which supports a lot of features on top of the good old `docker build`. `buildx` would help us in building multi-platform images which can run on all types of processors.
https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images

# Proposal

We would like Devtron to provide `buildx` option in the CI pipelines. Few additional options can also be provided to the user to choose which platform images the user wants to build. Or, it can also be provided as part of `Global Configurations`, where the Admins can select the platform(s) (`amd`, `arm` etc) for which all the apps need to build their images.

**Comment by ankit-ls** [comment]
@nishant-d @pghildiyal Please let me know your thoughts on this.

cc: @praveen-livspace

**Comment by praveen-livspace** [comment]
Any updates on this issue?

**Comment by pghildiyal** [comment]
Hi @praveen-livspace @ankit-ls this is planned to be released on 15th of July

**Comment by uxarya-d** [comment]
@ankit-ls Could you please share a preferred list of platforms for which you want to be supported for this feature?
We're currently considering the below platform options:
- linux/arm64
- linux/amd64
- linux/arm/v7
- darwin
- Custom

**Comment by ankit-ls** [comment]
Hey @uxarya-d thanks for picking this up! This list looks good enough for us for now.

> linux/arm64
linux/amd64
linux/arm/v7
darwin
Custom
