### ISSUE TITLE
run all devtron components behind one elb 

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#140]
motivation: today all devtron components are hidden behind multiple ingress objects. hiding behind single elb will help in reducing complexity of the product. 

hide them behind devtron proxy 

- [x] argocd-dex-ingress         
- [x] dashboard-ingress          
- [x] devtron-auth-ingress       
- [x] devtron-auth-login-ingress 
- [x] devtron-grafana            
- [x] devtron-ingress

**Comment by pghildiyal** [comment]
This ticket requires multiple changes

1. Dashboard microservice available at endpoint `/dashboard` should be routed through Devtron microservice
2. `/api/dex`,  `/auth/login` and `/auth/callback` urls should be routed through Devtron microservice
3. change url from `/api/dex` -> `/orchestrator/api/dex`, `/auth/login` -> `/orchestrator/auth/login`, `/auth/callback` -> `/orchestrator/auth/callback`
4. In `Global Config > SSO Login Services` section of the dashboard, for key `url` append `/orchestrator` at the end for eg change https://example.com -> https://example.com/orchestrator
5. Add `/orchestrator` to the url registered at identitiy provider i.e; https://example.com/api/dex/callback -> https://example.com/orchestrator/api/dex/callback
6. Add DASHBOARD_HOST and DASHBOARD_PORT as key in devtron-cm config map with value DASHBOARD_HOST: dashboard-service.devtroncd and DASHBOARD_PORT: 80

This upgrade will has breaking changes as url whitelisted by identity provider will change, it will result in dashboard not accessible during the time of migration.
