### ISSUE TITLE
New Pods are showing under OLD Pods section in App Details page along with filtering Workflow events

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1436]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

In the case of workflow objects when new pods are being created it shows under the OLD Pods section of the App Details page. And not able to see the logs over UI in case of workflow object as containers are not available on UI to select. Events are being sent for workflow objects which are neither ci or cd

**Expected behavior**

New pods should be under the new Pods section of the app details page.

**Current behavior** 

New Pods are shown in the Old Pods section.

**Screenshots**
New Pods showing in Old Pods section.
<img width="1440" alt="Screenshot 2022-03-28 at 4 49 59 PM" src="https://user-images.githubusercontent.com/85476803/160388127-8712ffa8-b351-43ae-9a59-c6f5d8ad22dc.png">

Logs are not available in case of the workflow object
<img width="1440" alt="Screenshot 2022-03-28 at 4 50 24 PM" src="https://user-images.githubusercontent.com/85476803/160388443-79f8fbe5-d878-4b8a-bb86-4b808a2d49ac.png">

**Comment by snehith57624** [comment]
PR: https://github.com/devtron-labs/devtron/pull/1552
