### ISSUE TITLE
External secret Issue

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1442]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

I deployed an app with AWS external-secret as secret all things running fine secrets are being used in the pod, even it shows degraded in-app status.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Create a custom app with AWS external-secret as secret.
2. Deploy the app.
3. Check the status of the app

**Expected behavior**

The app status should show healthy when everything running well. 

**Current behavior** 

Even after all things running fine but status is degraded.

**Screenshots**

<img width="1088" alt="Screenshot 2022-03-28 at 6 46 27 PM" src="https://user-images.githubusercontent.com/85476803/160406116-18ce00c8-0e4b-4e55-b12e-6625be483157.png">

**Comment by anupdhiran** [comment]
This needs to be fixed by ops team.

**Comment by prakarsh-dt** [comment]
@gunish-dt Please link to this issue when the lua script changes are merged

**Comment by anupdhiran** [comment]
@prakarsh-dt Is this issue still open ?

**Comment by prakarsh-dt** [comment]
This should be resolved now.
