### ISSUE TITLE
Customise devtron-ci pods

### ISSUE THREAD

**Issue by vishalgoel98** [devtron-labs/devtron#1455]
# Summary

Some of our micro services needs high CPU and Memory utilisation  while building images. so there would be feature from where we can customise the resource of CI pod.

**Comment by swoldanski** [comment]
I think that this functionality is already implemented. Maybe UX for doing such changes is not the best but it's working ;)

Take a look at https://github.com/devtron-labs/devtron/blob/main/manifests/updates/devtron-override-cm.yaml and follow docs at https://docs.devtron.ai/devtron/setup/install/override-default-devtron-installation-configs

Keep in mind that applying those changes takes time - follow progress by looking at logs of `inception` pod in `devtroncd` namespace.

**Comment by prakarsh-dt** [comment]
This is already configurable as stated by @swoldanski in the comment above. However, if you need it configurable at app level, please raise a separate enhancement request for the same.
