### ISSUE TITLE
Deployment history page gets Auto refreshed in Logs window.

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1461]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

In the case of pre-cd or post-cd, the deployment history page gets Auto refreshed in the Logs window again and again.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Create an app in devtron configure git-material, docker-build-config, and deployment template.
2. Create a workflow with pre or post cd enabled with some script.
3. Trigger pre or post cd pipeline and check logs while running pre or post cd pipeline live in the deployment history page.

**Comment by uxarya-d** [comment]
@pawan-59 Does this issue still exist? Was not able to reproduce.

**Comment by uxarya-d** [comment]
Verified with @pawan-59. Issue has been fixed..
