### ISSUE TITLE
Allow creation of service accounts via Devtron charts

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#1499]
# Summary

We would need the ability to create service accounts in Devtron

# Motivation

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

# Proposal

We need to add a `serviceaccount.yaml` file in chart templates.

AB#239

**Comment by strawhat5** [comment]
@nishant-d @prakarsh-dt Please review this #1502

**Comment by prakarsh-dt** [comment]
Release in chart reference-chart_4-12-0
