### ISSUE TITLE
Creating Global secrets

### ISSUE THREAD

**Issue by dipeshprajapatixoxoday** [devtron-labs/devtron#1503]
# Summary
Global secrets which are available to all environments and all the apps within environment

# Motivation

Currently, we have to create secrets for each app. If we have global secrets then we do not need to create secrets for each app individually.

# Proposal

Creating Global secrets which are available to the all apps pipelines.

# Testing Guideline [Optional]

NA

AB#241

**Comment by prakarsh-dt** [comment]
Resolved by #3869
