### ISSUE TITLE
Select text is misplaced in select material of trigger page.

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1521]
* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Select text is misplaced in select material of trigger page.

**Screenshots**

<img width="1440" alt="Screenshot 2022-04-20 at 6 27 00 PM" src="https://user-images.githubusercontent.com/85476803/164239097-6e277bc5-4e1a-4cad-9b79-da61cdf1703e.png">

**Comment by deepak-devtron** [comment]
This has been fixed
