### ISSUE TITLE
Devtron 2.0 e2e testing.

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#1551]
# Summary

Devtron 2.0 all use case testing

 - All api integration test
 - All flow testing
 - Base to base update
 - Base to Module installation
 - [Base with Module]  update

# Motivation

Bug free release.

# Proposal

- Individual API test
- Dashboard Interactions testing
-  Status and upgrade and update testing

# Testing Guideline [Optional]

How this feature will need to be tested. What all areas should be covered

**Comment by shivani170** [comment]
testing completed.
