### ISSUE TITLE
Feature: Devtron install breaks existing ArgoCD install

### ISSUE THREAD

**Issue by META-DREAMER** [devtron-labs/devtron#1572]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

When I try to install Devtron in a Kubernetes cluster that already has ArgoCD installed (via argocd-autopilot), it breaks the existing argocd install because of the changes the Devtron installer makes to ArgoCD roles / role bindings. 

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Bootstrap a cluster using argocd-autopilot
2. Install Devtron via Helm3

**Expected behavior**

Devtron detects and uses the existing argocd install under the argocd namespace

**Current behavior** 

Devtron installed a new argocd instance under the devtroncd namespace and breaks the role bindings

AB#10250

**Comment by dfl-aeb** [comment]
Any news on this topic? We're thinking about using devtron in our existing environment due to the great workflow and configuration management. But we're already using ArgoCD and devtron needs to integrate in the existing infrastructure.
Is that possible?

**Comment by awalther52** [comment]
Similar issue here, I am evaluating this platform and already use argocd.

**Comment by dfl-aeb** [comment]
@deepak-devtron @ajaydevtron can you at least tell us if sth like this is planned in the near future? That would help us a lot in planning whether we can use this tool

**Comment by prakarsh-dt** [comment]
Partial support already done in #4423, Devtron can now detect and list Argocd applications and it's objects from own as well as attached clusters.
 
<img width="1801" alt="Screenshot 2024-07-30 at 5 44 16 PM" src="https://github.com/user-attachments/assets/29622e8d-a42e-426f-a51f-c259c46b2ecc">
<img width="1745" alt="Screenshot 2024-07-30 at 5 44 37 PM" src="https://github.com/user-attachments/assets/546f9d96-e34c-4dd2-8a6f-dabaa4042394">
