### ISSUE TITLE
Docker image build still not started

### ISSUE THREAD

**Issue by yashmehta1** [devtron-labs/devtron#1583]
Hi, 

I am from Livspace company and we're using your product. I am trying to create a docker image for 2 hours. I cannot see any logs related to docker build and i cannot even abort it as its not in progress state. Please look into it as its creating problem with my work. 

Regards,
Yash

**Comment by prakarsh-dt** [comment]
@yashmehta1 This is resolved. Please message on Slack channel for faster resolutions.
