### ISSUE TITLE
Text we type in terminal is not visible when it reaches the end of terminal window

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1597]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

If we access terminal window from UI and keep running some commands, after the terminal window is full of outputs whatever we type is not visible after that

**To Reproduce**

1. Open terminal using devtron in helm apps
2. Run some commands till the output terminal window is full
3. Now type something, the text will not be visible, the output of the command is still visible

**Expected behavior**

The commands should be clear even after the first output window is full

**Current behavior** 

Text is not visible after some point

**Comment by anupdhiran** [comment]
This might have been fixed already. Milind to check and close a/c.
