### ISSUE TITLE
Validate with user just before saving the deployment template

### ISSUE THREAD

**Issue by snehith57624** [devtron-labs/devtron#1605]
# Summary
Validation of template is done and will show user the uploaded template details and proceed based on the user action 

# Motivation

User will see the uploaded template name, description as per the chart.yaml file and asks whether to proceed or will update the details

# Proposal

Validation is done separately and saving those details are done separately 

# Testing Guideline [Optional]

Tested by uploading a template

**Comment by snehith57624** [comment]
https://github.com/devtron-labs/devtron/pull/1603/

**Comment by shivani170** [comment]
Merged
