### ISSUE TITLE
[Devtron Apps] logs are not coming for specific pod on cd.devtron

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#1613]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

With new app details integration on Devtron apps, logs for a specific pod are not coming. However, they're coming under Log Analyzer for the same pod.

**To reproduce**

1. Go to the AppDetails page for Devtron app
2. Go to specific pod under K8s resources & select logs option
3. Observe
4. Switch to the Log Analyzer tab
5. Select the specific pod under the Pods dropdown
6. Observe

**Expected**: It should print/show logs under the specific pod's logs view

**Current**: Logs are not coming for specific pod

**Comment by sohel-rp** [comment]
Fix has been pushed to PR - https://github.com/devtron-labs/dashboard/pull/358
