### ISSUE TITLE
[AppDetails] Additional Space after terminal & resume button is not clickable

### ISSUE THREAD

**Issue by milindk8** [devtron-labs/devtron#1623]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

There's some additional space after the terminal component on the new app details page. Also, sometimes the resume option is not clickable in case of a Disconnected state on the terminal.

**To Reproduce**

I. Additional space -
1. Go to the AppDetails page
2. Go to Pod & select terminal option
3. Scroll to the bottom of the page
4. Observe

II. Resume option not clickable
1. Go to the AppDetails page
2. Go to Pod & select terminal option
3. In disconnected state,  try to click on resume
4. Observe

**Expected behavior**

There shouldn't be additional space & the resume should be clickable

**Current behavior** 

There's additional space & resume is not clickable

**Screenshots**

I. Additional space -
![Screenshot 2022-05-10 at 1.00.34 AM.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/c4900a62-833e-49ce-a314-d60810d02e5a)

II. Resume option not clickable
![Screenshot_20220510_131106.png](https://images.zenhubusercontent.com/61f7a8fc1e558b7ab1d73c6a/ae38519d-cf48-4f87-8f72-e5be6910c887)

**Comment by prakarsh-dt** [comment]
https://github.com/devtron-labs/devtron/issues/1597 could be linked to this issue.
