### ISSUE TITLE
[SPIKE] Figure out feature flag implementation for FE and BE

### ISSUE THREAD

**Issue by anupdhiran** [devtron-labs/devtron#1627]
# Summary

Need to figure out feature flag implementation for front end and back end code

# Motivation

This will enable faster releases in production without waiting for dependencies

# Proposal

Find out which mechanism will work best for us

# Testing Guideline [Optional]

N/A

**Comment by anupdhiran** [comment]
For backend the below library seemed to be a good candidate. For front end, research was not completed as the thought process was to not have multiple libraries and systems to manage feature flags and hence we thought of developing the solution in house by having a json file preferably in S3 and an internal api to update it and a common  service to read the flags from S3 file. 
However, as per recent discussions, we are putting this ticket on hold and this might be either picked up again or closed if the need for implementation doesn't arrive.

**Comment by deepak-devtron** [comment]
not required as on now.
