### ISSUE TITLE
Historical Data keeps the old vlaue of pipeline id

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1641]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [ ] I've included steps to reproduce the bug.

**Describe the bug**

When I am checking the history of updated data for app configuration It shows the old pipeline id of the same environment which I deleted previously and created again for the same environment.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Create a custom app on devtron and configure it.
2. Now create a workflow for a specific environment and note down the value of pipeline id.
3. Now deploy it once or save the deployment template multiple times by changing the data.
4. Check the DB once with the command `select pipeline_id,template_version,is_app_metrics_enabled,updated_on,updated_by  from deployment_template_history where app_id=<your app id> order by updated_on desc;`.
5. Now delete the pipeline and create it again for the same environment which you deleted and note down the pipeline id. 
6. Try to update some value in env override and again check the data updated on DB with the above command it would be same as that of previously deleted data.

**Expected behavior**

The data on DB should be with the latest value of pipeline id.

**Current behavior** 

It shows the pipeline id of the first time created a pipeline of the same environment.

**Comment by kartik-579** [comment]
Have checked the issue, pipelineId is getting updated correctly. The issues is with updated_on value in some cases. Fix for this will be included in https://github.com/devtron-labs/devtron/pull/1634
