### ISSUE TITLE
Feature based offering in orchestrator on application startup instead of multiple builds

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#1649]
# Summary
CICD without gitops

Avoid different builds for different offerings or modules, allow application to take call on its startup to provide feature based offering.

# Motivation
 To provide CICD feature to user powered by helm on CICD module integration.

# Proposal

# Testing Guideline [Optional]

**Comment by vikramdevtron** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/1649?planning-poker) with ZenHub @kartik-579 @manish-agrawal-ai @nishant-d @pghildiyal

**Comment by deepak-devtron** [comment]
Being taken care by another ticket
