### ISSUE TITLE
Modules Integrations Installer - Handler modifications

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#1651]
# Summary
CICD without gitops

From Module (Integrations) list, the install click currently support only "cicd" modules, modifications required here for to install other modules too.

# Motivation
 To provide CICD feature to user powered by helm on CICD module integration.

# Proposal

# Testing Guideline [Optional]

**Comment by vikramdevtron** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/1651?planning-poker) with ZenHub @kartik-579 @manish-agrawal-ai @nishant-d @pghildiyal

**Comment by deepak-devtron** [comment]
Being taken care by another ticket
