### ISSUE TITLE
Upgrade Postgres client version to latest in all microservices

### ISSUE THREAD

**Issue by anupdhiran** [devtron-labs/devtron#1657]
# Summary

Need to upgrade postgres client version in orchestrator and other microservices to latest one. Current one's are pretty old around 6.x.

# Motivation

Need to move to latest releases to reap benefits of latest releases.

# Proposal

This has been done already in lens repository. Please get in touch with Anup for learnings. Checking release notes from the current version to latest version should give an idea what all things need to be changed.

# Testing Guideline [Optional]

1. All CRUD transactions related to DB for the respective microservices will have to be tested carefully.

**Comment by deepak-devtron** [comment]
We are going to use another client for PG as GO-PG is now deprecated so I am closing it.
