### ISSUE TITLE
Non-dynamic height of terminal and logs tab 

### ISSUE THREAD

**Issue by milindk8** [devtron-labs/devtron#1668]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Terminal and log div is not taking dynamic height & not acquiring full height of view 

**To Reproduce**

1. User goes to devtron apps or helm apps 
2. User selects pods & select terminal or logs
3. Terminal and logs is not taking full height

**Expected behavior**

Terminal and logs should take full available height

**Current behavior** 

Terminal and logs is not taking full height

**Screenshots**

![Screenshot_20220517_095928.png](https://images.zenhubusercontent.com/61f7a8fc1e558b7ab1d73c6a/4657610b-8ba2-4de4-829a-0ccc2080f3bd)

**Comment by shivani170** [comment]
Merged
