### ISSUE TITLE
Access Control on Devtron UI

### ISSUE THREAD

**Issue by xoxodevops** [devtron-labs/devtron#1677]
The users who do not have Production Access are able to view the production pipeline, edit the branches in them and are able to abort an ongoing build process.

**Comment by snehith57624** [comment]
User can view production pipeline but should be authorised before editing branch, abort ongoing build for applications which have CD pipelines

**Comment by xoxodevops** [comment]
The user has admin access to other namespaces except production , but is still able to update the branch on production. if someone from devtron team wants , we can get on a call and show it.
