### ISSUE TITLE
Allow user to with build access to change branch name during build step

### ISSUE THREAD

**Issue by pghildiyal** [devtron-labs/devtron#1686]
# Summary

User with build and deploy access should be able to change the branch name in build step as long as branch name conforms to the branch name regex provided during build configuration.

# Motivation
Currently user is able to change branch name only when user has admin access and DevOps team may not want to give user admin access.
In some companies during development phase developers need to change branch name to their own development branch before they trigger build step. 

# Proposal

During build configuration, admin should be able to define regex for branch name. If regex is provided for branch name then user with build access should be able to change the branch name which conform to the regex pattern provided during build configuration. Once user has selected one branch name then behaviour would be same as is for branch fixed configuration of build.

# Testing Guideline [Optional]

Build for branch fixed and branch regex would have to be done. With empty as well as branch name provided in case of regex.

**Comment by shivani170** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/1686?planning-poker) with ZenHub @nishant-d @pghildiyal @manish-agrawal-ai @vikramdevtron
