### ISSUE TITLE
Notification dashboard Takes lots of time to load applications.

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#1697]
# Summary

While configuring new notification on global configuration it takes lots of time to load the data since we have lots of applications and pipelines. This should load as an async process like you are doing for others filters. 

<img width="1440" alt="Screenshot 2022-05-19 at 10 24 10 AM" src="https://user-images.githubusercontent.com/85476803/169210791-b955e6b7-f36b-4daf-826f-274509036dcd.png">

**Comment by deepak-devtron** [comment]
This has been improved already so closing it.
