### ISSUE TITLE
Broken UI in logs & events log in devtron app

### ISSUE THREAD

**Issue by milindk8** [devtron-labs/devtron#1713]
Logs UI bug

![image.png](https://images.zenhubusercontent.com/61f7a8fc1e558b7ab1d73c6a/403d144a-ed69-48fe-b500-198d51bd751e)

Events UI bug

![image.png](https://images.zenhubusercontent.com/61f7a8fc1e558b7ab1d73c6a/90b12a93-04e7-46e5-8540-87c49418d3b4)

Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Some CSS from parent component is overriding the CSS in new component and showing random behaviour

**To Reproduce**

1. User goes to devtron apps
2. User selects pod < logs
3. User selects pod < events

**Comment by shivani170** [comment]
Merged
