### ISSUE TITLE
Application Catalog

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#1723]
Application Catalog

**Comment by shivani170** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/1723?planning-poker) with ZenHub @nishant-d @manish-agrawal-ai @pghildiyal

**Comment by deepak-devtron** [comment]
No longer relevant
