### ISSUE TITLE
Selecting blank app clones the app if we switch from clone back to blank app

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1727]
**Describe the bug**

During creation of an app if we select clone app and select any app to clone but before creation we switch back to blank app, it still clones the application

**To Reproduce**

1. Click Create New > Custom App
2. Select Clone Application > Search and select application to clone
3. Switch back to Blank Application > Click Create

**Expected behavior**

It should have created Blank application

**Current behavior** 

It cloned the app which was selected

AB#292

**Comment by deepak-devtron** [comment]
This is still pending
