### ISSUE TITLE
User is not able to save secret as "data-volume" in environment overrides

### ISSUE THREAD

**Issue by deepak-devtron** [devtron-labs/devtron#1765]
**Bug Description**

User is not able to save secret as "data-volume" in environment overrides

**To Reproduce**
1. Create a complete CI/CD flow
2. Now go to environment overrides 
3. Try to save a secret of any data type except "Kubernetes External Secret"

**Current behaviour** 

There is no action on save button

**Expected behaviour**

File should save properly without any issue

**Comment by vivek-devtron** [comment]
Merged
