### ISSUE TITLE
Automation of Gitops configured, suggest ci name

### ISSUE THREAD

**Issue by nikeshDevtron** [devtron-labs/devtron#1793]
# Summary

Automation of :

Check gitops exists 
GET /orchestrator/gitops/configured

GET suggested ci pipeline name
/orchestrator/app/pipeline/suggest/ci/app-id

GET /orchestrator/app/{AppId}/autocomplete/git

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

# Testing Guideline [Optional]

How this feature will need to be tested. What all areas should be covered

**Comment by deepak-devtron** [comment]
These APIs already automated and merged so closing it.
