### ISSUE TITLE
Feature: Show age and restart count on App Details page

### ISSUE THREAD

**Issue by Abhinav-26** [devtron-labs/devtron#1821]
# Summary

Currently, in the status of the App Details page, Devtron doesn't show the age of k8s resources deployed and its restart count.

  # Motivation

This feature would really help to understand the insights of deployment created and improve the way Devtron shows the status of the application. On the other hand, it will also give the taste of the `kubectl` command.  When you execute `kubectl get pods -ndevtroncd`, it gives you the detailed insights of the pods created, their age, restarts count, status, etc.

AB#310

**Comment by pawan-mehta-dt** [comment]
Fixed by https://github.com/devtron-labs/dashboard/pull/588
