### ISSUE TITLE
Need deployer username and timestamp variables in post-deployment of Devtron Template

### ISSUE THREAD

**Issue by Madhav-BharatPe** [devtron-labs/devtron#1849]
# Summary

Give us a few properties or variables like deployer `username/email` and deployment `start time` so that we can create a release event in an external performance monitoring tool to monitor post deployment performance issues.

# Motivation

We are triggering a webhook to monitor our deployment metrics after every deployment for that we need the deployer username and deployment start to build time

# Testing Guideline [Optional]

It would be great if you guys can provide us actually two timestamps, one when the deployment started and the second when the traffic is actually shifting to new pods.

AB#104

**Comment by prakarsh-dt** [comment]
@manish-agrawal-ai Let's schedule this for DT-18

**Comment by prakarsh-dt** [comment]
@Madhav-BharatPe 

`DEVTRON_CD_TRIGGER_TIME` and `DEVTRON_CD_TRIGGERED_BY` env variable are now available in post CD steps
