### ISSUE TITLE
Create CI-Pipeline will take regex input

### ISSUE THREAD

**Issue by snehith57624** [devtron-labs/devtron#1853]
# Summary
When creating CI-Pipeline admins can add regex value which will be used to validate the branch name for users who have build and deploy access while updating

# Motivation
Users with build and deploy access can also edit branch names for CI-Pipeline

# Proposal
Will take regex input while creating CI-Pipeline from admins and use that to validate the branch name for build and deploy access users

# Testing Guideline
Create CI-Pipeline with regex and check with user who has build and deploy access to update branch name following regex for which it should get updated and try updating branch name which is not following the regex for which it should not get updated

**Comment by anupdhiran** [comment]
This has been completed
