### ISSUE TITLE
Some drop-down popup not fixed (Window specific)

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#1874]
**Describe the bug**

While we opening the dropdown, the Opened popup is not fixed with the dropdown.

**To Reproduce**

The user goes to Chart Store
User selects the chart & selects to deploy
then select any dropdown like Chart Version

**Expected behaviour**

Popup should be fixed with dropdown

**Current behaviour**

Popup moving with the scroller 

**Screenshots**

While open dropdown
![orignal.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/1454b358-a6c9-4bdf-b6d5-a7f237f188ad)

While Moving our scroller
![with error.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/d8610ad1-26e4-409e-8397-21d1055bc3be)

AB#322

**Comment by rakshitgondwal** [comment]
Hey!
I was looking to contribute to this issue but can you let me know any pre-requisites that I would require before trying to take upon this issue?

**Comment by sidverma32** [comment]
@nitish6660 hey i would like to pick this issue. can you assign it to me?

**Comment by shivani170** [comment]
The bug does not exist anymore. This has been resolved with the fix.
Whenever the chart version dropdown opens user cannot scroll the rest page.
