### ISSUE TITLE
Chart store Repository Filter selection is Unstable

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#1875]
**Describe the bug**

while we select any repo in the chart store scroller is unstable

**To Reproduce**

The user goes to Chart Store
Then the user selects the last repo & then needs 
to select 2nd last repo

**Expected behavior**

After selecting the repo scroller should be stable for continuous selection 

**Current behavior**

While we selecting the last Repo scroller is in unstable mode

**Screenshots**

Before selecting
![before.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/eac5fde5-ee2d-42dc-a52f-7f382c4f1edc)

After selection
![After.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/59c7f025-8fcf-45f0-b475-7ecb404f42e8)

**Comment by deepak-devtron** [comment]
No more relevant
