### ISSUE TITLE
Data validation Error while enable and disable Chart Repository

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#1879]
**Describe the bug**

If we enable and disable the chart Repository Data validation Error coming

**To Reproduce**

The user goes to Chart Repository
then enable and disable added chart Repository

**Expected behavior**

If we enable and disable the chart Repository proper massage should come

**Current behavior**

While we enable and disable the chart Repository Data validation Error is coming

**Screenshots**
When we enable

![Enable.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/2d616da6-9755-41ee-b389-3858a23c67bf)

When we disable

![Deseble.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/b4c37b4d-6c17-498d-a691-a88cee4f60f1)

**Comment by deepak-devtron** [comment]
This has been fixed
