### ISSUE TITLE
Secret and CM showing duplication while we override

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#1882]
**Describe the bug**

If we are overriding any secret or CM duplicate key value Error showing

**To Reproduce**

The user creates devtron app
Then User can override the secret or CM
Save CM and secret with different key and value

**Expected behavior**

Secret and CM should be saved with different key and value

**Current behavior**

While we trying to override a new CM and secret sometimes duplicate key value Error showing till refreshing the page

**Screenshots**

Before override 

![before.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/9ae09de0-e661-49ad-b456-a2c411b8be19)

After override

![After.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/13133f2c-806f-44d9-a01c-854458f12eae)

**Comment by deepak-devtron** [comment]
This has been fixed
