### ISSUE TITLE
Stack manager - GitOps module support

### ISSUE THREAD

**Issue by sohel-rp** [devtron-labs/devtron#1885]
# Summary

Add support to install the GitOps module through Devtron stack manager.

# Motivation

Enable ability to deploy without GitOps configuration. If user wants to use it then respective module will be available for installtion through Devtron stack manager.

# Proposal

![Screenshot 2022-06-14 at 11.55.41 AM.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/1d8c1457-1d9c-431e-88bb-37438e794e7e)

![Screenshot 2022-06-14 at 11.55.53 AM.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/28aba9ea-1f44-4443-9dea-263bb64b8d6e)

![Screenshot 2022-06-14 at 11.56.03 AM.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/65f6cec8-ef78-4ede-8624-0ca4048886d1)

![Screenshot 2022-06-14 at 11.56.31 AM.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/dac9d4ee-db7e-49b2-9bd2-ec3ab411375e)

![Screenshot 2022-06-14 at 11.56.42 AM.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/7081d26c-977c-49be-836f-4965efe46e5c)

![Screenshot 2022-06-15 at 9.54.16 AM.png](https://images.zenhubusercontent.com/61e15405a1d0b1e0e115f611/2eaf8c3c-716c-4d98-a2b3-55d0a6b6ab7c)

**Comment by deepak-devtron** [comment]
fixed with this ticket  https://github.com/devtron-labs/dashboard/issues/497
