### ISSUE TITLE
Kubernetes ExternalSecret support in 4.13.0

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#1892]
# Summary

AWS Secret manager support using Kubernetes ExternalSecret https://github.com/external-secrets/external-secrets
Also rename existing `Kubernetes External Secret` to something like `Custom Secret` 

# Motivation

Present implementation of AWS Secret Manger secrets is done using https://github.com/external-secrets/kubernetes-external-secrets which is not maintained anymore and the closest implementation is using https://github.com/external-secrets/external-secrets.

# Proposal

New changes to be encorporated mentioned above.

# Testing Guideline [Optional]

NA

**Comment by deepak-devtron** [comment]
This has been deployed.
