### ISSUE TITLE
terminal connecting status 

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#193]
connecting status of terminal(red) is confusing for user

**Comment by uxarya-d** [comment]
@nishant-d Did someone point this out?

**Comment by uxarya-d** [comment]
@nishant-d Does this look fine?
![Screenshot 2021-01-25 at 7.39.05 PM.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/75c792c5-2205-4800-956c-19a60316faf1)

**Comment by nishant-d** [comment]
it looks good in stand alone. however there is flicker when status changes from connecting to disconnected. Can we have smooth transition ?

**Comment by uxarya-d** [comment]
Okay. Have discussed this with Rashmi. She'll change the color to green for `connecting...` and we'll see if there's a flicker and what can be done about it.
