### ISSUE TITLE
UX: Allow users to create multiple cd pipeline on same environment

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1932]
# Summary

Currently, withing an application only one cd pipeline can be created for an environment.

# Motivation

Users may want to create different cd pipelines to the same env as part of separate workflows within the same application.

# Proposal

Allow users to create multiple pipelines deploying to the same environment.

AB#347

**Comment by uxarya-d** [comment]
UX task for #1174

**Comment by pawan-59** [comment]
Duplicate issue https://github.com/devtron-labs/devtron/issues/1174
