### ISSUE TITLE
Edit group name showing in multi-chart deployment flow

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1943]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Edit group name is showing in multi-chart deployment flow

**To Reproduce**

1. Go to Chart Store
2. Click on [+] on any chart > This shows a panel on the right of the screen
3. Group name and edit icon is showing on top of the right panel

**Expected behavior**

Group name and edit icon should not be shown in multi-chart deployment flow

**Current behavior** 

Edit group name is showing in multi-chart deployment flow

**Screenshots**

![image.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/34a28158-af11-4a8a-91ba-f6bde0286eda)

**Comment by vivek-devtron** [comment]
Merged
