### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CronJob" in version "batch/v1"

### ISSUE THREAD

**Issue by ladung** [devtron-labs/devtron#1963]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [ ] I've included steps to reproduce the bug.

**Describe the bug**

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. User goes to Create an application (to save space or whatever)
2. User selects clone option 
3. Configmap in environment override is not cloned

**Expected behavior**

**Current behavior** 

describe what you currently experienced from this process, and thereby explain the bug

**Screenshots**

**Logs**
 
```
Paste any relevant application logs here.
```

**Comment by prakarsh-dt** [comment]
@ladung Can you please clarify when exactly is this occurring? 
Are you trying to deploy an app using the Job and Cronjob chart?

**Comment by ladung** [comment]
@prakarsh-dt when i use command  `helm install devtron devtron/devtron-operator -n devtroncd --set installer.modules={cicd}`. I have this problem!

**Comment by ladung** [comment]
My version kubenetes is 1.17.5

**Comment by ladung** [comment]
@prakarsh-dt can you help me?

**Comment by ladung** [comment]
![image](https://user-images.githubusercontent.com/43999277/179488748-6d199754-34c2-4961-be72-f2cf8c4cb881.png)

**Comment by ladung** [comment]
![image](https://user-images.githubusercontent.com/43999277/179768575-43065a8b-a372-40fb-a13c-92cf68cf26cd.png)

@prakarsh-dt

**Comment by ladung** [comment]
@prakarsh-dt i ran that command but it's error:
![image](https://user-images.githubusercontent.com/43999277/180132178-c38bf416-1f48-477b-ab21-83fd38619d31.png)

**Comment by ladung** [comment]
@prakarsh-dt  please help me?
