### ISSUE TITLE
We are not getting any result using discover API for manually added chart-repos in chart-store

### ISSUE THREAD

**Issue by deepak-devtron** [devtron-labs/devtron#1985]
**Summary**
We are not getting any result using discover API for manually added chart-repos in chart-store

**Steps to replicate**
1. Go to global configurations
2. Add any chart-repository 
3. Go to chart-store and try to search your repo

**Actual Output**
We are not able to search this repo (No data in response of search API)

**Expected Output**
There should data in search API's response

**Comment by manish-agrawal-ai** [comment]
Assigning to @deepak-devtron for exact steps to reproduce.

**Comment by deepak-devtron** [comment]
Currently I am not able to replicate the same ,so closing it.
