### ISSUE TITLE
Git commit hash/sha as an environment variable in pre and post deployment steps

### ISSUE THREAD

**Issue by onkarhoysalalivspace** [devtron-labs/devtron#1989]
# Summary

In pre and post-deployment steps, it is useful to have the commit hash/sha as an environment variables, which we could use for example in webhook calls. 

# Motivation

Let's say we need to integrate with a third-party tool that provides deployment analytics. In such a case, their webhooks require us to append the commit hash. While it is very easy to add a post-deployment step, currently not having the commit hash is being a blocker in integrating with such tooling. 

# Proposal

Having the git hash provided as an environment variable during the pre and post deployment steps. 

AB#365

**Comment by ankit-ls** [comment]
@nishant-d @pghildiy Can you please review this request?

**Comment by onkarhoysalalivspace** [comment]
@nishant-d @pghildiyal Could you please let us know the ETA for this?

**Comment by onkarhoysalalivspace** [comment]
@nishant-d @pghildiyal Guys, any update on this? :)

**Comment by pghildiyal** [comment]
@pawan-59 please coordinate with @onkarhoysalalivspace
