### ISSUE TITLE
[SSO]On Enabling/updating SSO configurations we have to bounce orchestrator pod

### ISSUE THREAD

**Issue by deepak-devtron** [devtron-labs/devtron#1990]
1. Create a fresh cluster and install devtron in it
2. Enable SSO configuration for the same
3. Add any SSO user  
4. Try to login via SSO 

**Actual Output**
We are not able to login until we bounce the orchestrator pod

**Expected Output**
User should be able to login without restarting the pod

**Observation**
Sometime on updating the SSO configurations via API we have to bounce the orchestrator pod for make them effective.

AB#367

**Comment by anupdhiran** [comment]
To be worked upon by Gireesh
