### ISSUE TITLE
popup remains exist after the deletion of Environment

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#2015]
**Describe the bug**

While we delete any Environment, The popup remains to exist after the deletion of the Environment.

**To Reproduce**

The user goes to cluster and Environment
User deletes any environment if exists

**Expected behavior**

Popups should disappear after deleted environment

**Current behavior**

popup remains exist after the deletion of Environment 

**Screenshots**
when Environment Exist

![1.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/387ab2c0-3fb2-4c34-bb9b-2b8db861048e)

When Environment deleted
![2.JPG](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/5340a56c-4bf7-4ecd-80b3-d669bcf97116)

**Comment by deepak-devtron** [comment]
This has been fixed so closing it.
