### ISSUE TITLE
Preset container registry

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#2034]
# Summary
Preset container registry

![Screenshot 2022-07-18 at 7.16.29 PM.png](https://ima![Screenshot 2022-07-18 at 7.16.49 PM.png](https://images.zenhubusercontent.com/6019150c4e513fef37b40730/2f39343c-dd21-4893-bddb-60b5b57a28e1)ges.zenhubusercontent.com/6019150c4e513fef37b40730/9f6bd299-f2c2-40d0-aa0c-a61b17ffc659)

**Comment by shivani170** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/2034?planning-poker) with ZenHub @sohel-rp @vivek-devtron

**Comment by deepak-devtron** [comment]
No more required so closing it.
