### ISSUE TITLE
Sample application creation

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#2035]
# Summary

Sample application creation

<img width="652" alt="Screenshot 2022-07-18 at 9 29 20 AM" src="https://user-images.githubusercontent.com/61836271/179443369-abd675f1-1b2c-41bd-a1fb-04bd3d4f31c0.png">

<img width="903" alt="Screenshot 2022-07-18 at 9 29 34 AM" src="https://user-images.githubusercontent.com/61836271/179443391-c4335e71-8ac6-4086-832a-069a3cf0255e.png">

**Comment by shivani170** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/2035?planning-poker) with ZenHub @sohel-rp @vivek-devtron

**Comment by anupdhiran** [comment]
This problem will be solved via other features that the team is working on.
