### ISSUE TITLE
Checkout at path where dockerfile is present

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#2070]
# Summary

It's not necessary that dockerfile is always present at root of source code repository. In case it is not, we have to either checkout manually to dockerfile path in pre-ci or we have to create another dockerfile which has all abosulte paths from root

# Motivation

If dockerfile is not at root, checkout path will run docker build from the path where dockerfile is present in source code repository which won't need any changes to dockerfile

# Proposal

We can solve this using an input field for checkout path

AB#408

**Comment by Shubham-Laddha** [comment]
Is this same as https://github.com/devtron-labs/devtron/issues/2703?
