### ISSUE TITLE
Enforcer Caching for remaining APIs

### ISSUE THREAD

**Issue by kripanshdevtron** [devtron-labs/devtron#2072]
Earlier we introduced Enforcer Caching on Dashboard List APIs which has improved the Dashboard load time but there are other areas that are also impacted by Enforcer.

**Comment by deepak-devtron** [comment]
Here I am attaching Test cases file link for everyone’s reference.  **[Link](https://docs.google.com/spreadsheets/d/1Iu-tj50ECnCLplkljuoGL8QjPGB7SJn98iMuelOXIXI/edit?usp=sharing)**
