### ISSUE TITLE
Option to show timestamps for logs.

### ISSUE THREAD

**Issue by hariprasadiit** [devtron-labs/devtron#2080]
# Summary

Timestamps for logs in logs section

# Motivation

Timestamps will really help to understand when a particular event has occurred for debugging purposes. Not all applications output logs with timestamps.

# Proposal

Probably a toggle button to enable or disable timestamps.

AB#547

**Comment by hariprasadiit** [comment]
Can this be prioritised? timestamps are needed for devtron logs to be useful for lot of services without inbuilt timestamps in logs

**Comment by sohel-rp** [comment]
Hi @hariprasadiit,

Development to enable timestamps for logs has been completed. It will be released in the upcoming release. Most probably early next week.

Related PR - https://github.com/devtron-labs/dashboard/pull/561.
