### ISSUE TITLE
UX ONLY: Git repo path whitelisting or blacklisting

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#2138]
# Summary

Allow users to whitelist or blacklist git repo paths to consider or ignore for building image

# Motivation

User may want to Consider OR Ignore changes in specific paths for triggering a build pipeline

# Proposal

Users can provide paths either to whitelist or blacklist

Blacklisted paths: Ignore changes in path (multiple)
- CI will not be triggered for any changes made in the specified paths
- Changes in all other paths will be considered for build

Whitelisted paths: Consider changes in path (multiple) for triggering build
- Changes in all other paths will be ignored for build

[Design Prototype](https://www.figma.com/proto/bh763czmqOCxwv4PYustlq/Devtron-App-(Configuration)?page-id=1924%3A7293&node-id=1924%3A7421&viewport=392%2C266%2C0.1&scaling=min-zoom&starting-point-node-id=1924%3A7421)
AB#38

**Comment by tayalrishabh96** [comment]
Released in #3343
