### ISSUE TITLE
Add ESO (External Secret Operator)

### ISSUE THREAD

**Issue by milindk8** [devtron-labs/devtron#2169]
# Summary

Add ESO (External Secret Operator) as an additional option while creating a secret.

# Motivation

Additional options for the user

# Proposal

In secret, by adding an options in the dropdown 

![Screenshot 2022-08-23 at 9.21.02 AM.png](https://images.zenhubusercontent.com/61f7a8fc1e558b7ab1d73c6a/84597f4f-7e4a-41fe-8d1b-6ac190b750f8)

AB#81

**Comment by kartik-579** [comment]
done with #2227
