### ISSUE TITLE
Bug: Git material not getting updated properly on updating the url.

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#2215]
Git material is not getting updated properly on updating the URL. It creates another git material for the same pipeline like this app is configured with a multi git repo, although it's not the case. In my case, I was migrating from bitbucket to Github so I just updated the git repo URL in the existing app with GitHub URL.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Go to app configuration of existing deployed applications and update the different URL.
2. Now check the workflows.

**Expected behavior**

It should replace all the existing workflow with the new information.

**Current behavior** 

Right now it's creating a new record on the database and does not update the existing workflows. So we have to manually update the URL and remove the records for the existing pipeline.

**Screenshots**

<img width="1023" alt="Screenshot 2022-08-24 at 11 27 20 AM" src="https://user-images.githubusercontent.com/85476803/186341569-b3976e4a-aed9-4288-a0f0-64bff4e6eac9.png">

AB#151

**Comment by kartik-579** [comment]
issue with ci_pipeline_material and git_material entries. Need to revisit checks for fetching materials and updating them. Also issues with mutli repo when app is cloned.
