### ISSUE TITLE
take gitops config from UI

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#225]
- [ ] take gitops config from UI instead of command

currently supported param

  GIT_PROVIDER: "GITHUB"    # GITHUB OR GITLAB
  GIT_HOST: "change-me" default github.com/ gitLab.com

  GITLAB_NAMESPACE_NAME: "change-me"  #orgID
  GITHUB_ORGANIZATION: "change-me" 
  
  GIT_USERNAME: "change-me"   doc link to minimum required privilege
  GIT_TOKEN: Y2hhbmdlX21l

**Comment by uxarya-d** [comment]
Gitops details are pre-requisite to perform below actions:

1. Saving Deployment template
2. Installing chart from chart store

**Comment by uxarya-d** [comment]
- [ ] Clicking on Global Config in nav should land on first item (i.e. GitOps)
- [ ] GitOps configuration > Rename to "GitOps"
- [ ] Show ✅ on active GitOps configuration like in SSO login services
- [ ] Token field and save button padding inconsistent from right, should be aligned with other fields.
