### ISSUE TITLE
Delete Override is not showing for external secret 

### ISSUE THREAD

**Issue by milindk8** [devtron-labs/devtron#2255]
After overriding global secrets, the tab does not show modified & user can't delete override which resets the secret

Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Delete override is not working for externel secrets

**To Reproduce**

1. Override a secret
2. User selects clone option 
3. Configmap in environment override is not cloned

**Screenshots**

![Screenshot 2022-09-09 at 9.26.52 AM.png](https://images.zenhubusercontent.com/61f7a8fc1e558b7ab1d73c6a/e15863d7-7c8a-42ac-abd7-81a42458b0ab)

**Logs**
 
```
Paste any relevant application logs here.
```

AB#186

**Comment by kartik-579** [comment]
delete happens at one click without warning. probably can include this fix in this release too. @milindk8
