### ISSUE TITLE
Bug: Can't add clusters if there is any space in server url

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#2314]
While adding clusters on devtron, if any white space is there in the server url, then we get  this :`Key: 'ClusterBean.ServerUrl' Error:Field validation for 'ServerUrl' failed on the 'url' tag` error. And this fixed on removing the white space from server url.

proposed solution: This can be fixed if we trim the white spaces (if any) from the server url entered by the user.

AB#222

**Comment by vikramdevtron** [comment]
not reproducible
