### ISSUE TITLE
Unable to add cluster while we using no gitops

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#2315]
**Describe the bug**

While we trying to add cluster with no gitops unable to add them.

**To Reproduce**

1. User goes to Global configuration > Clusters and environments
2. User click on add the cluster
3. Configure as required to add cluster

**Expected behavior**

If we add a cluster without gitops configured it should be successfully added.

**Current behavior**

While we add a cluster with no gitops unable to add it is throwing error.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/d9f5c1b1-6d16-4830-84a0-e45e84c50639)

**Logs**

{"level":"error","ts":1662449555.8747437,"caller":"cluster/ClusterRestHandler.go:136","msg":"service err, Save","err":"rpc error: code = Unauthenticated desc = no session information","payload":null,"stacktrace":"github.com/devtron-labs/devtron/api/cluster.ClusterRestHandlerImpl.Save\n\t/go/src/github.com/devtron-labs/devtron/api/cluster/ClusterRestHandler.go:136\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:72\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/gorilla/mux.(Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:62\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
{"level":"info","ts":1662449555.874792,"caller":"common/apiError.go:118","msg":"ERROR RES","TYPE":"API-ERROR","RES":500,"ERROR-MSG":[{"code":"1002","internalMessage":"rpc error: code = Unauthenticated desc = no session information","userMessage":"failed to register on ACD, rollback completed from db"}],"err":null}

L

AB#223

**Comment by manish-agrawal-ai** [comment]
Invalid issue for OSS
