### ISSUE TITLE
take devtron url from UI instead of env variable

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#235]
impacted component 

- [x] notifier
- [x] external ci
- [x] grafana

**Comment by uxarya-d** [comment]
url scheme: http/https
domain on which devtron is available

Auto-fetch URL and inform user that URL has been updated.

URL can only be updated from super-admin account.

Global Config > Host URL (domain name from which this dashboard is accessible)
App > App metrics
App > Trigger
Workflow editor > Upfront + External CI
Notification > Show message upfront

**Comment by vikramdevtron** [comment]
App > App metrics  (grafana url tested)
App > Trigger https://zpl.io/ad6ODKn
Workflow editor > Upfront https://zpl.io/agON3X9
External CI https://zpl.io/aN6X7rv https://zpl.io/V4gWY8X
Notification > Show message upfront https://zpl.io/b6GrePj
