### ISSUE TITLE
Feature: Create a deployment helm-chart 

### ISSUE THREAD

**Issue by verma-kunal** [devtron-labs/devtron#2389]
### 🔖 Feature description

Creating a deployment Helm-chart under the initiative - `Bring You Own Chart`

### 🎤 Pitch

-

### ✌️ Solution

-

### 🔄️ Alternative

-

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#564

**Comment by verma-kunal** [comment]
I have worked on this in collaboration with @Abhinav-26 ! Will raise a PR asap

**Comment by pawan-mehta-dt** [comment]
Completed by #2391
