### ISSUE TITLE
Feature: Support to change the source type in ci-pipeline

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#2396]
### 🔖 Feature description

As of user can't change the source type of a ci-pipeline once created. Afterward, if a user wants to switch the source-type of ci-pipeline he has only one option that deletes the existing pipeline(which will also delete the cd-attached to ci-pipeline and deployment will also get deleted).

### 🎤 Pitch

if a user wants to switch the source-type of ci-pipeline he has only one option that deletes the existing pipeline(which will also delete the cd-attached to ci-pipeline and deployment will also get deleted). 

### ✌️ Solution

Need a feature to change the source type in ci-pipeline.

### 🔄️ Alternative

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#581

**Comment by prakarsh-dt** [comment]
Should also be resolved by #2381
