### ISSUE TITLE
Doc: custom chart doc fixes

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#2398]
### 💭 Description

To get the values file on devtron templates values.yaml needs to be renamed as app-values.yaml

The content of .image_descriptor_template.json is incorrect.
<img width="747" alt="Screenshot 2022-09-26 at 11 25 08 AM" src="https://user-images.githubusercontent.com/85476803/192203572-d77eafd5-661e-48be-b280-0849be41d66b.png">

Please mention release-values.yaml is required and give reference for same.
https://github.com/devtron-labs/devtron/blob/main/scripts/devtron-reference-helm-charts/reference-chart_4-14-0/release-values.yaml

To use the ConfigMap and secret feature of devtron app configuration needs to be there, how can users include the feature in their templates.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#582

**Comment by measutosh** [comment]
Hi @pawan-59, What I could figure out is there are 2-3 tasks involved in it. Could you be more specific and put it in short what are those in bullet points.

By far I understood this much, please clarify these doubts and lead me to the location of the files.
1. rectify the code, mostly commas are missing, one unnecessary question mark is there
2. have to write content in some file on "how can users the feature in their templates"

**Comment by pawan-59** [comment]
Hello @measutosh nice to have you here. We have already raised a PR for the fix, just waiting to get this merged on main. Although please follow these points to fix the issue
1. Add image-descriptor file content as per [this](https://github.com/devtron-labs/devtron/blob/main/contrib-chart/reference-chart_3-11-0/.image_descriptor_template.json).
2. Add [release-values.yaml](https://github.com/devtron-labs/devtron/blob/main/scripts/devtron-reference-helm-charts/reference-chart_4-14-0/release-values.yaml) in your chart.
3. Copy the content of values.yaml of the chart in app-values.yaml. (don't remove values.yaml from your chart).
