### ISSUE TITLE
Bug: GitOps (Argo CD) installation fails

### ISSUE THREAD

**Issue by mjayksharma** [devtron-labs/devtron#2438]
### 📜 Description

Created a kind cluster on 1.22.7 k8s version. 
Installed devtron using helm chart.
When tried to install GitOps (Argo CD) from the UI, it got stuck in installing state and I see argocd-application-controller and argocd-server pods are in CrashLoopBackOff state.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/53367806/193507597-af25d9b8-a377-495d-ab23-7fd096660a79.png">

**argocd-application-controller-0 pod logs**
<img width="1730" alt="image" src="https://user-images.githubusercontent.com/53367806/193468515-a7c4161d-0a7a-4983-8efd-5db3f21e69bd.png">
**argocd-server pod logs:** 
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/53367806/193468543-6d094e81-6e87-445e-8492-842c77d6668e.png">

### 👟 Reproduction steps

Install a kind cluster with below kind configurations:
`kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
    podSubnet: "10.214.0.0/16"
    serviceSubnet: "10.16.0.0/12"
nodes:
- role: control-plane
  image: kindest/node:v1.22.7@sha256:1dfd72d193bf7da64765fd2f2898f78663b9ba366c2aa74be1fd7498a1873166 
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
- role: worker
  image: kindest/node:v1.22.7@sha256:1dfd72d193bf7da64765fd2f2898f78663b9ba366c2aa74be1fd7498a1873166
- role: worker
  image: kindest/node:v1.22.7@sha256:1dfd72d193bf7da64765fd2f2898f78663b9ba366c2aa74be1fd7498a1873166 `

and use devtron helm chart to install devtron

### 👍 Expected behavior

When installing Argo CD. Pods should spin up and installation should be successful.

### 👎 Actual Behavior

Argo pods go into CrashLoopBackOff state

### 💻 Device

Desktop/Laptop

### 💻 Operating system

MacOS

### 🌍 Browser

Chrome

### 🧱 Your Environment

I use kind for creating a k8s version 1.22.7 cluster

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#620

**Comment by mjayksharma** [comment]
Thanks for the reply @pawan-59 . I applied that CRD, and the argocd-server server started fine but I am still getting below errors in argocd-application-controller pod
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/53367806/193550024-1cdd2e76-d1b1-4809-9ec0-b9f459f5c599.png">

**Comment by pawan-59** [comment]
Got it, Please apply all the crd once from [here](https://github.com/argoproj/argo-cd/tree/master/manifests/crds)

**Comment by dheeth** [comment]
Fixed this in latest release
