### ISSUE TITLE
Website Visitors and Blog Vistiors Using Python Feature for Devtron 

### ISSUE THREAD

**Issue by Apollo9999** [devtron-labs/devtron#2440]
### 🔖 Feature description

Added  Feature OF Website Visitors and Blog Vistiors Using Python

### 🎤 Pitch

Counting and Monitor the Number of Users visiting the Website and Blog of Devtron

### ✌️ Solution

Detailing Information of Counting and Monitor the Number of Users visiting the Website and Blog of Devtron

### 🔄️ Alternative

Not Available

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#622

**Comment by Apollo9999** [comment]
Approve the Issue for Hackatoberfest and Future Purposes  I will the provide the python code

**Comment by Abhinav-26** [comment]
> Approve the Issue for managing and maintaining the website user actions and to monitor analysis for future Purposes as I will provide the python source code @Abhinav-26

Hii @Apollo9999, this is not a valid PR for Devtron's repo, hence closing.
