### ISSUE TITLE
Feature: Pod restart count

### ISSUE THREAD

**Issue by gireesh-devtron** [devtron-labs/devtron#2469]
### 🔖 Feature description

display pod restart count for pods in ui.

### 🎤 Pitch

the pod restart count can be seen on ui without explicitly go into events 

### ✌️ Solution

get count from event api  

### 🔄️ Alternative

na

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#664

**Comment by tanishk-23** [comment]
@gireesh-devtron can you assign this to me?

**Comment by kripanshdevtron** [comment]
@tanishk-23 Thanx for your interest in this particular issue but unfortunately this issue has been already picked.  You can however [contribute to Devtron](https://github.com/devtron-labs/hacktoberfest2022) through other ways. 

Please feel free to reach out to me or anyone in the [discord](https://discord.devtron.ai/) for any questions.
Looking forward to have your contributions.

**Comment by pawan-mehta-dt** [comment]
Fixed by https://github.com/devtron-labs/dashboard/pull/588
