### ISSUE TITLE
Feature: Adding a sample-docker-template for Kotlin language

### ISSUE THREAD

**Issue by bishal7679** [devtron-labs/devtron#2477]
### 🔖 Feature description

A sample docker-template for Kotlin language which can be used to run a simple kotlin application in a docker container

### 🎤 Pitch

Want to Add a docker-template for Kotlin language which can be used to run a simple kotlin application in a docker container

### ✌️ Solution

Adding a sample-docker-template for kotlin

### 🔄️ Alternative

N/A

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#671

**Comment by kartik-579** [comment]
approved and merged
