### ISSUE TITLE
Feature: Clusters Token visibility 

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#2509]
### 🔖 Feature description

The cluster token should not be visible in the global configuration once configured successfully. Neither for super admin too.

### 🎤 Pitch

One can misuse the token.

### ✌️ Solution

NA

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#927

**Comment by prakarsh-dt** [comment]
Should be implemented for:
- Cluster tokens
- Git credentials
- Gitops credentials
- Container Registry credentials
- SSO credentials
