### ISSUE TITLE
Feature: Change trigger option to Manual by default when a new CI pipeline is created

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#2515]
### 🔖 Feature description

Change trigger option to `Manual` by default insted of `Automatic` when a new CI pipeline is created.

### 🎤 Pitch

Automatic/Manual trigger option is currently hidden in `Advanced options` and therefore is mostly not changed by the users. Putting pipelines on `Automatic` trigger mode triggers a build process every time a commit is done on the branch (which might not be required always).

This results in wastage of cloud resources (build workers) and in turn increases organization's carbon footprint.

### ✌️ Solution

Make `Manual` trigger as the default option.
<br><br>

<img width="1069" alt="Screenshot 2022-10-20 at 11 31 15 AM" src="https://user-images.githubusercontent.com/71125043/196868197-a0b12575-9014-4515-9736-c56b13b26e4a.png">

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#943

**Comment by Abhinav-CHD** [comment]
Hey can I work on this issue?

**Comment by kapishmalik** [comment]
@prakarsh-dt I would like to work on this issue.
