### ISSUE TITLE
User cannot add env in EA mode

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#2521]
**Describe the bug**

User unable add env in EA mode if he required 

**To Reproduce**

The user goes to Global configurations
Then User selects the Clusters

**Expected behaviour**

Add environment button should be there in cluster option

**Current behaviour**

User unable to add any environment in cluster option

**Screenshots**

![image.png](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/823cb19c-0175-4c20-8936-bd805910df28)

AB#959

**Comment by abhibhaw** [comment]
This is resolved, feel free to reopen if this still exist @nitish6660
