### ISSUE TITLE
Feature: Need option to delete the resources normally

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#2528]
### 🔖 Feature description

Currently, whenever we delete the resources from Devtron-UI it is deleted with the --force flag, which in some cases is not required. Such as if I'm running with a preStop lifecycle in my application and someone deleted the pod from the UI my preStop lifecycle won't be executed.

### 🎤 Pitch

 If I'm running with a preStop lifecycle in my application and someone deleted the pod from the UI my preStop lifecycle won't be executed.

### ✌️ Solution

If there would be an option to choose whether we want to delete the resources normally of with the --force flag like argocd provides that would help.

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#966

**Comment by sohel-rp** [comment]
Changes for this feature have been covered under - https://github.com/devtron-labs/dashboard/pull/613.
