### ISSUE TITLE
Build status showing CANCELLED instead of Aborted.

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#2531]
**Describe the bug**

Build status showing CANCELLED whereas in tooltip it is showing Aborted.

**To Reproduce**

The user goes to build history
User abort the deployment 
then after aborted hover on deployment list

**Expected behaviour**

Both massage should be same either aborted or cancelled 

**Current behaviour**

if we abort the deployment , Status showing cancelled and when hover on deployment it is showing aborted.

**Screenshots**

when aborted the deployment
![image.png](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/6f2ccf37-ba30-4168-9ff8-9c2fc92637cd)

when hover on deployment 
![image.png](https://images.zenhubusercontent.com/625e3cc952981b6166f1291a/9b0eaa25-345e-4645-a08d-49aa7b1fbffa)

AB#968

**Comment by manish-agrawal-ai** [comment]
Fixed
