### ISSUE TITLE
Doc: replace "," with "," in the end of the sentence 

### ISSUE THREAD

**Issue by nikitakoselev** [devtron-labs/devtron#2548]
### 💭 Description

Where: https://github.com/devtron-labs/devtron/blob/main/README.md
What: "Implements GitOps to manage the state of Kubernetes applications," ends in "," and should be a ".", according to other examples.

Screenshot:
![image](https://user-images.githubusercontent.com/6383738/198821821-f07c4be8-3a75-465b-8a88-051b0fa58dc4.png)

P.S. Please apply "good first time issue" label.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#1006

**Comment by kapishmalik** [comment]
@nikitakoselev I would like to work on this issue.

**Comment by akshat2203** [comment]
hello @nikitakoselev 
i have fixed this issue check below pr:
https://github.com/devtron-labs/devtron/pull/2552#issue-1429301913

**Comment by nikitakoselev** [comment]
It has been fixed by #2550, has to be merged, so I can close this ticket.

@akshat2203, it looks like 2 people completed the fix. I suggest you make a Twitter post about it, as a funny part of our job, which is hard to avoid sometimes, even for experienced devs :)

**Comment by SNe789** [comment]
Hi @nikitakoselev, its fixed. you can close this issue.

**Comment by nikitakoselev** [comment]
Thank you 🤓
