### ISSUE TITLE
Doc: Installation using a minikube cluster in Readme

### ISSUE THREAD

**Issue by Kanika637** [devtron-labs/devtron#2554]
### 💭 Description

I think we should have a section on `installation using the minikube cluster` in the Readme.md file. As a minikube user, I myself got some issues and could not install Devtron in the first go using the previously written steps. 
There are some steps which are subjected only for a minikube user Eg: for accessing the URL, an external IP address is required with a `minikube tunnel` in process.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Kanika637** [comment]
If valid, I would like to work on this issue

**Comment by prakarsh-dt** [comment]
Hi @Kanika637 
We have a separate documentation page for minikube https://docs.devtron.ai/getting-started/install/install-devtron-on-minikube-microk8s-k3s-kind 

Is that something you wanted? Do you see some scope to enhance that?

**Comment by Kanika637** [comment]
No actually @prakarsh-dt, the documentation is appropriate, I just wanted to have this section in the Readme as well.

**Comment by prakarsh-dt** [comment]
Sure, please go ahead. However, please ensure that it's not too loud in the Readme.

**Comment by Kanika637** [comment]
Will take care of that @prakarsh-dt.

**Comment by Kanika637** [comment]
Have made the PR

**Comment by ashokdevtron** [comment]
Closing this PR. Steps are enhanced and no longer the way they were a year ago.
And closing the linked PR too: https://github.com/devtron-labs/devtron/pull/2566

New PR: https://github.com/devtron-labs/devtron/pull/4477
