### ISSUE TITLE
Doc: Chinese version

### ISSUE THREAD

**Issue by loda13** [devtron-labs/devtron#2633]
### 💭 Description

need Chinese version please...

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by SNe789** [comment]
Hi @loda13, We are in the process of translating our [Devtron docs](https://docs.devtron.ai/) into different languages including Chinese. We will let you know as soon as they are available.

**Comment by loda13** [comment]
thx
