### ISSUE TITLE
Bug: PG: no rows in result set

### ISSUE THREAD

**Issue by antikilahdjs** [devtron-labs/devtron#2657]
### 📜 Description

After build some dockers and create more than 10 pipelines using CI/CD the erro "PG: no rows in result set" and cannot delete or create nothing anymore.

### 👟 Reproduction steps

1 - Just install the HELM as documentation

### 👍 Expected behavior

It should be works normally because postgres is running

### 👎 Actual Behavior

 "PG: no rows in result set" 

![image](https://user-images.githubusercontent.com/33559260/202557809-d6132e19-294f-4943-a78d-294065776f4c.png)

### ☸ Kubernetes version

1.23.6

### Cloud provider

<details>
on-premise
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

none

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by hamzaolak** [comment]
I have a same isue.

**Comment by prakarsh-dt** [comment]
@antikilahdjs @hamzaolak Can you please share more information about the issue.
1. Was the Devtron stack updated post which this issue started?
2. Were there any manual changes done in any of the tables in the DB?

**Comment by antikilahdjs** [comment]
Hello @prakarsh-dt  thank you so much but it can be fixed remove everything in the cluster abount devtron and re-install it again. I dont know what this error shows but I founded this way to fix it. Tks
