### ISSUE TITLE
Bug: Not able to create ecr-repository in pipeline override container registry

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#2676]
### 📜 Description

In the case of pipeline override for container registry, it's not able to create the repository in the pipeline override even with the proper permission.

### 👟 Reproduction steps

1. Add ecr container repository in the global config with proper permission.
2. Create a devtron application and add ci pipeline with overridden container registry and give the repo name which is not created.
3. Now try to build the image from this CI. 

### 👍 Expected behavior

It should create a repository if that repository doesn't exist and have proper permission to create a repo as we do in the global container registry.

### 👎 Actual Behavior

It is not trying to create a repository just looking for it and giving timeout.

### ☸ Kubernetes version

1.21

### Cloud provider

<details>
EKS 1.21
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
RCA: ECR repo creation was being done at Docker build config save and update action but not for ci template override actions (ci pipeline save and update apis).
