### ISSUE TITLE
Bug: We are able to deploy devtron applications in env which is not created from cluster and environment section.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#2687]
### 📜 Description

We are able to select env which is not created from cluster and environment section during deploying devtron applications.
but in backend it is going to create helm release name app name with environment name.(these env name contain underscore).

Drop down list
<img width="1257" alt="Screenshot 2022-11-25 at 1 13 51 PM" src="https://user-images.githubusercontent.com/99399155/203930643-9828f9db-c7f5-4b00-9a91-f226ed2068cc.png">

Error screenshot 

<img width="1096" alt="default-env" src="https://user-images.githubusercontent.com/99399155/203930961-eceed5d5-d514-4298-92db-1160f98c9b82.png">

error logs 
**Invalid value: "sh.helm.release.v1.external_apache.v1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')**

### 👟 Reproduction steps

1. Install devtron without CI CD mode
2. Install ci cd integration
3. create the ns from kubectl cli.
4. create a devtron app and in workflow configuration , we will see the env names(created by kubectl cli) for deploying with drop down.

### 👍 Expected behavior

It should only show the environments which are created from cluster and environment section including devtron-demo.  

### 👎 Actual Behavior

Right now we are seeing the dropdown with environments list which contains all.

### ☸ Kubernetes version

1.22

### Cloud provider

<details>
Azure
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

microk8s

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
@ajaydevtron please verify.
