### ISSUE TITLE
Bug: Wf is getting deleted from UI during update its name.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#2694]
### 📜 Description

When i am trying to update workflow name its going to delete workflow from UI.
<img width="1253" alt="Screenshot 2022-11-28 at 11 42 50 AM" src="https://user-images.githubusercontent.com/99399155/204206460-036606ed-70b4-4bc4-aa05-da5f38c79332.png">

### 👟 Reproduction steps

NA

### 👍 Expected behavior

It should update the workflows

### 👎 Actual Behavior

It getting deleted from UI , during update.

### ☸ Kubernetes version

1.22

### Cloud provider

<details>
Azure
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
RCA: orchestrator was updating active field as false for workflow update api which caused workflows to get deleted.
