### ISSUE TITLE
Feature: Deployment Support for  Monorepo

### ISSUE THREAD

**Issue by marutinandanpandya** [devtron-labs/devtron#2703]
### 🔖 Feature description

Current Deployment setup downloads the git repo and tries to build docker image from root path.

Repo Structrure 
- .gitignore
- service1/Dockerfile
- service1/scr/*
- service1/package.json
- service2/Dockerfile
- service2/scr/*
- service2/package.json

example of Dockerfile
path: <root>/service1/Dockerfile

```
FROM keymetrics/pm2:12-alpine

ENV HOME=/home/node
USER root
WORKDIR $HOME/app
COPY package.json $HOME/tmp/
COPY package-lock.json $HOME/tmp/
COPY .npmrc $HOME/tmp/
RUN cd $HOME/tmp/ && npm install
COPY src $HOME/app/src
RUN cd $HOME/app && npm run build
COPY pm2.json ./

EXPOSE 9026
```

### 🎤 Pitch

While image build, deployment script should have an option to moved to a directory (sub path) in the repo and then perform the `docker build ` command.

### ✌️ Solution

While image build, deployment script should have an option to moved to a directory (sub path) in the repo and then perform the `docker build ` command.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shubham-Laddha** [comment]
@pawan-59 @prakarsh-dt This is a valid ask for monorepos. Has this been checked?
