### ISSUE TITLE
Bug: Incorrect helm cd pipeline status in presence of GitOps cd pipeline. 

### ISSUE THREAD

**Issue by iamayushm** [devtron-labs/devtron#2709]
### 📜 Description

After introduction of GitOps or Helm option for CD, when we create multiple cd pipelines with different deployment app types (Helm or GitOps)  ,either in parallel or in different workflows then deployment status of Helm pipeline is show as failed in "Build and Deploy" tab even if cd pipeline status is healthy in app details tab. This happens only when both GitOps and Helm pipeline are present.

### 👟 Reproduction steps

1) Create a cd pipeline with deployment app type as helm. (PipelineA)
2) Wait for PipelineA's deployment app status to become healthy.
3) Create another pipeline , either in parallel to above pipeline or create a separate workflow. (PipelineB) 
4) After deployment app status of PipelineB become healthy, status of Pipeline A will be shown as Failed.

### 👍 Expected behavior

Status of PipelineA should not have been Marked as failed because in actual it is Healthy.

### 👎 Actual Behavior

Status of PipelineA (helm pipeline) is affected by presence of PipelineB (GitOps pipeline).

### ☸ Kubernetes version

1.22

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aravind-2023** [comment]
not reproducable ,already fixed
