### ISSUE TITLE
Bug: Missing files or UserAccount 

### ISSUE THREAD

**Issue by ZergHeureux** [devtron-labs/devtron#2710]
### 📜 Description

Found this while doing search on Docker : 
![image](https://user-images.githubusercontent.com/82547553/205014742-d412dd0b-0411-4fe9-96b4-d1406da85bb8.png)
Hope this helps !

### 👟 Reproduction steps

Go to : https://devtron.ai/blog/cmd-and-entrypoint-differences/#:~:text=Differences%20between%20CMD%20%26%20ENTRYPOINT&text=CMD%20commands%20are%20ignored%20by,as%20arguments%20of%20the%20command.

### 👍 Expected behavior

it should show pictures or demo around the middle part of the page

### 👎 Actual Behavior

No pictures

### ☸ Kubernetes version

None

### Cloud provider

<details>

</details>
None

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by jyotisah00** [comment]
the blog has been updated with images and all broken media has been fixed.
https://devtron.ai/blog/cmd-and-entrypoint-differences/
