### ISSUE TITLE
Feature: health check API for all micro-services

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#2725]
### 🔖 Feature description

Please create a health check API for all the microservices so we can use this in livenessProbe and readinessProbe.

### 🎤 Pitch

To ensure whether service is up or not we can use readiness and liveness probes to help identify issues at 1st level.

### ✌️ Solution

create health check API for all the micro services.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kamal-devtron** [comment]
Micro-services:
Kubelink 
Kubewatch
Image-scanner
Dashboard
Lens
git-sensor 
These are the micro services we have to create liveness and readiness probe

**Comment by pawan-59** [comment]
Duplicate ticket https://github.com/devtron-labs/devtron/issues/2793
