### ISSUE TITLE
Enhancement: Recreating deployment pipeline shows already exists error without proper information

### ISSUE THREAD

**Issue by kartik-579** [devtron-labs/devtron#2746]
### 📜 Description

If a user has created a cd pipeline on gitOps and deleted it. Sometimes they are shown with the error that the app already exists(on argocd).

### 👟 Reproduction steps

1. Create a cd pipeline using gitOps mode. 
2. Block deletion of resource from backend.,
3. Delete the pipeline.

### 👍 Expected behavior

The user should be informed with an more elaborate message. 

### 👎 Actual Behavior

Confusing message is shown which confuses user.

### ☸ Kubernetes version

1.22

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
Issue : In cases where deletion get stuck, the argo app is not actually deleted but it is deleted at devtron side. This causes error when user tries to recreate the pipeline.

Proposal: 
1. Introduce a new status like `Deletion in progress` which shows the status of deletion.
2. Introduce an informer which deletes the pipeline from devtron after successful deletion at argocd/k8s side.
3. Add a backup mechanism(maybe a cronJob) if informer fails to delete the pipeline when it should.

**Comment by vikramdevtron** [comment]
fixed in https://github.com/devtron-labs/devtron/pull/2950
