### ISSUE TITLE
Feature: Provide filter on cluster for choosing the environment while deploying chart

### ISSUE THREAD

**Issue by bipulbcopa** [devtron-labs/devtron#2757]
### 🔖 Feature description

Provide filter on cluster for choosing the environment while deploying chart

### 🎤 Pitch

Provide filter on cluster for choosing the environment while deploying chart

### ✌️ Solution

Provide filter on cluster for choosing the environment while deploying chart

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by uxarya-d** [comment]
**Proposal**

![image](https://user-images.githubusercontent.com/73632042/212033977-378cff89-ba0d-448a-b616-f16672993b73.png)

https://www.figma.com/file/j7cqlBdhQ47Bo10TLfamGl/Helm-Apps?node-id=3131%3A65121&t=YyEcskBhrys211Gq-4

**Comment by uxarya-d** [comment]
Shipped
