### ISSUE TITLE
Feature: Provide filter on cluster for choosing the environment while creating the deployment pipelin on workflow editor.

### ISSUE THREAD

**Issue by bipulbcopa** [devtron-labs/devtron#2758]
### 🔖 Feature description

Provide filter on cluster for choosing the environment while creating the deployment pipelin on workflow editor.

### 🎤 Pitch

Provide filter on cluster for choosing the environment while creating the deployment pipelin on workflow editor.

### ✌️ Solution

Provide filter on cluster for choosing the environment while creating the deployment pipelin on workflow editor.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by uxarya-d** [comment]
Create deployment pipeline > Select environment (Environments are now grouped by clusters)
