### ISSUE TITLE
cluster, env and namespace name appropriate validation messaging

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#276]
apply proper validation at frontend and backend

**Comment by uxarya-d** [comment]
1. Show character counter below field.
2. The specific error statement is shown when the user commits an error that violates the condition.

Error statements:
Use only lowercase alphanumeric characters, '-' or '.'
Start/End with an alphanumeric character
_Note: Check ending character using debounce or on focus-out_

UI: https://zpl.io/bJMBorx

**Comment by uxarya-d** [comment]
![Uploading Screenshot 2021-07-12 at 5.20.18 PM.png…]()

Error message for Namespace validation to be done in readable format as well.
Please refer: https://zpl.io/bJMBorx

**Comment by manish-agrawal-ai** [comment]
Issue fixed.
