### ISSUE TITLE
Bug: helm install of devtron failed

### ISSUE THREAD

**Issue by emoxam** [devtron-labs/devtron#2767]
### 📜 Description

touch: cannot touch '/bitnami/postgresql/.user_scripts_initialized': Permission denied

### 👟 Reproduction steps

1. add repo - helm repo add devtron https://helm.devtron.ai
2.  run - helm install devtron devtron/devtron-operator \
--create-namespace --namespace devtroncd \
--set installer.modules={cicd} \
--set argo-cd.enabled=true
3. kubectl get pod -n devtroncd
4. see - postgresql-postgresql-0              1/2     CrashLoopBackOff
5. run - kubectl logs -n devtroncd postgresql-postgresql-0
6. see -
postgresql 14:39:02.83 INFO  ==> Starting PostgreSQL in background...
touch: cannot touch '/bitnami/postgresql/.user_scripts_initialized': Permission denied
postgresql 14:39:02.99 INFO  ==> Stopping PostgreSQL...

### 👍 Expected behavior

Pod should starts

### 👎 Actual Behavior

Pod stuck with an error "CrashLoopBackOff"

### ☸ Kubernetes version

apt list --installed | grep kube
kubeadm/kubernetes-xenial,now 1.24.4-00 amd64 [installed,upgradable to: 1.26.0-00]
kubectl/kubernetes-xenial,now 1.24.4-00 amd64 [installed,upgradable to: 1.26.0-00]
kubelet/kubernetes-xenial,now 1.24.4-00 amd64 [installed,upgradable to: 1.26.0-00]
kubernetes-cni/kubernetes-xenial,now 0.8.7-00 amd64 [installed,upgradable to: 1.1.1-00]

### Cloud provider

<details>
Self hosted 
</details>

### 🌍 Browser

Edge

### ✅ Proposed Solution

fix the Permission

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by antikilahdjs** [comment]
The best way is you get the helm and customized as you needs because the helm from devtron is very simple and if you has the same of me a complex cluster or a csi you need provide some configs like permission, chmod on folder and so on.
