### ISSUE TITLE
Bug: CI/CD install fail

### ISSUE THREAD

**Issue by boerzi** [devtron-labs/devtron#2818]
### 📜 Description

china gfw network blocking,i try to install  CI/CD, response "dial tcp 0.0.0.0:443: connect: connection refused"

### 👟 Reproduction steps

1.install or Retry install

### 👍 Expected behavior

install success

### 👎 Actual Behavior

Get "https://raw.githubusercontent.com/devtron-labs/devtron/v0.6.9/charts/devtron/devtron-bom.yaml": dial tcp 0.0.0.0:443: connect: connection refused

 response : {"code":500,"status":"Internal Server Error","errors":[{"code":"000","internalMessage":"[{Get \"https:/
/raw.githubusercontent.com/devtron-labs/devtron/v0.6.9/charts/devtron/devtron-bom.yaml\": dial tcp 0.0.0.0:443: connect: co
nnection refused}]","userMessage":"Get \"https://raw.githubusercontent.com/devtron-labs/devtron/v0.6.9/charts/devtron/devtr
on-bom.yaml\": dial tcp 0.0.0.0:443: connect: connection refused"}]}

### ☸ Kubernetes version

k3d

### Cloud provider

self-hosted

### 🌍 Browser

Chrome

### ✅ Proposed Solution

 This is a request from the golang http package,I want to use golang http proxy download devtron-bom.yaml Or use other methods to successfully download . What should I do

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by prakarsh-dt** [comment]
Hi @boerzi,

Did you try adding `--set installer.source=gitee` to the helm install command?

**Comment by antikilahdjs** [comment]
HI @boerzi,

May you have some troubles internally with your ISP, DNS provider because I installed it many times and never got any issues. Try install using  --set installer.source=gitee

**Comment by boerzi** [comment]
@prakarsh-dt @antikilahdjs 
tks,I solved the install failure 。devtron team is so good
