### ISSUE TITLE
Bug: Cluster terminal doesn't work if hostname label on node doesn't match with node name

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#2826]
### 📜 Description

Cluster terminal doesn't work if hostname label on node doesn't match with node name

### 👟 Reproduction steps

Try creating EKS nodes with DHCP option enabled with your domain
The nodes won't have the hostname label value as node name
Try to create cluster terminal on any of that node

### 👍 Expected behavior

It should crawl labels on node and use the existing hostname label with value on node

### 👎 Actual Behavior

Terminal pod creation fails on the node because in affinity devtron adds node name as hostname value

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
this is fixed in https://github.com/devtron-labs/devtron/pull/2925
