### ISSUE TITLE
Bug: Node actions option should be available only to super admins

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#2830]
### 📜 Description

Node actions available on the cluster detail page should be usable only for super admin users. Node actions are mentioned below:
1. Terminal
2. Cordon
3. Drain
4. Edit taints
5. Edit YAML
6. Delete node

### 👟 Reproduction steps

1. Go to Clusters
2. Open any cluster
3. Click on 3 dot icon against any node.
4. Click on any option from the menu.

OR

Got to node detail page by clicking on any node name.
Node actions are available here as well.

### 👍 Expected behavior

If a non-super admin user clicks on any of these options from the node list or the node detail page, show `Access denied` toast.

![image](https://user-images.githubusercontent.com/73632042/210732196-15515f2f-f627-4c61-8104-570fd0aa4cd7.png)

### 👎 Actual Behavior

Incorrect handling for non-super admin users.

### ☸ Kubernetes version

NA

### Cloud provider

NA

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
Fixed in https://github.com/devtron-labs/dashboard/pull/686
