### ISSUE TITLE
Bug: Search option should not be case sensitive for chart store, clusters and chart preset values

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#2831]
### 📜 Description

When we search a chart, cluster name or chart preset values name containing capital letters. It give not found message.
![chart-seach](https://user-images.githubusercontent.com/87755583/210730310-df795a49-d925-4f6a-9ff7-50f7ee7ca59b.jpg)
![preset-value-list](https://user-images.githubusercontent.com/87755583/210730546-61b78759-93e8-471d-8e00-53e2c3147863.jpg)
![Preset value not found](https://user-images.githubusercontent.com/87755583/210730641-c8072606-83f7-4fbc-9f27-1d32897cc9e1.jpg)
![Cluster list](https://user-images.githubusercontent.com/87755583/210730779-af2de7f3-d979-4290-94d8-b2eeb1bb2bd4.jpg)

![cluster not found](https://user-images.githubusercontent.com/87755583/210730923-868e64fd-6477-4fd4-977e-045bd99c483a.jpg)

### 👟 Reproduction steps

For chart store:

1. Search for any of the chart in store, typing the name in capital letters.

For Preset values:

1. Create a preset value for a chart.
2. Go to preset values list and search for it in caps-on mode.

For clusters:

1. Go to clusters.
2. Search for cluster name in capital letters.

### 👍 Expected behavior

It should give the search results by ignoring the  keywords case.

### 👎 Actual Behavior

Only giving search results for keywords in small case.

### ☸ Kubernetes version

Microk8s 1.22

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

We can convert the capital letters to small letters at time of typing only.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aravind-2023** [comment]
https://github.com/devtron-labs/dashboard/pull/986

**Comment by Aravind-2023** [comment]
https://github.com/devtron-labs/devtron/pull/3396
