### ISSUE TITLE
Bug: No retry after pod creation timeout

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#2834]
### 📜 Description

Terminal access pod takes about 20-25 seconds to come up as healthy in general depending on the selected image. There's a timeout of around 15s which means that if the pod takes more than 15s, we show a failed message as below.

<img width="1357" alt="Screenshot 2023-01-05 at 4 12 54 PM" src="https://user-images.githubusercontent.com/71125043/210761938-dbc1eea1-2914-480d-bea6-683a1561b14b.png">

And when the user checks the events/manifest, they find that the pod has already started or is in pending. 
Even if the pod has started, after clicking back on `Terminal` Devtron doesn't retries to reconnect and gets stuck on the failed pod screen.

### 👟 Reproduction steps

1. Select a bulky image for terminal access.
2. Once the failed pod creation screen comes, check the manifest to verify if the pod has gone into the running state.
3. Once the pod is in running state (as per the manifest), got back to `Terminal`, devtron will not try to reconnect unless the user manually clicks on disconnect and reconnect.

### 👍 Expected behavior

After the pod is in running state, when the user switches back to `Terminal`, it should automatically retry to connect.

### 👎 Actual Behavior

Once the pod is in running state (as per the manifest), got back to `Terminal`, devtron will not try to reconnect unless the user manually clicks on disconnect and reconnect.

### ☸ Kubernetes version

EKS 1.21

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

1. Increase 15s timeout to 30s to avoid failed pod screen. (An animation can be used with Creating pod to let the users know it's connecting)
2. After the pod is in running state, when the user switches back to `Terminal`, it should automatically retry to connect to the pod.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by gireesh-devtron** [comment]
this is fixed in PR https://github.com/devtron-labs/devtron/pull/2925
