### ISSUE TITLE
Bug: Not getting Manifest in case of non namespace-scoped in helm apps

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#2860]
### 📜 Description

In case of helm apps and non name-space scoped attributes ,we are getting an error stating that the application is not found .

### 👟 Reproduction steps

1: Create a new helm app and deploy using some chart.
2: in the appdetails check the manifest of non-namespace scoped attributes like clusterRole.
3: Under that field ,check for its manifest ,we will get an error when we click on that.

### 👍 Expected behavior

Manifest should be displayed when we click on that.

### 👎 Actual Behavior

Manifest is not visible and we are getting an error.
### ☸ Kubernetes version

MicroK8s 1.22

### Cloud provider

MicroK8s deployed on VM provided by Azure

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
closed with https://github.com/devtron-labs/dashboard/pull/960
