### ISSUE TITLE
Misleading error message while logging in(SSO) if user has no access

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#287]
Use case: user's email id is "not provided access" , user tries to login using SSO.
Issue: Incorrect error message
To-do: https://www.figma.com/file/Djn5gYdAeiqyP45AJOsTnr/Miscellaneous?node-id=714%3A1364

![Screenshot 2021-02-17 at 5.17.29 PM.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/56b470c4-7cb3-497a-8b0a-52ef2b9185c6)

AB#637

**Comment by prakarsh-dt** [comment]
@chtnnh Sorry for the delayed response, are you still open to work on this issue?
