### ISSUE TITLE
Host URL shows error icon in Global config even if field is empty

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#290]
Host URL item should only show an error in Global config when entered URL doesn't match with the URL in the browser.

![Screenshot 2021-02-23 at 1.50.11 PM.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/8c59e40d-a98a-4fba-afcf-d3d178b5aae6)

**Comment by prakarsh-dt** [comment]
This is resolved
