### ISSUE TITLE
FR: Version controlled Configmaps

### ISSUE THREAD

**Issue by strawhat5** [devtron-labs/devtron#292]
**Describe your feature request (FR):**
As a user, I would like my configmaps to be version controlled in Git. This helps keep a track of all the changes over a period of time. It also helps in mitigating scenarios where someone with Admin access to an app, accidentally deletes its configmap.

**Possible Solution:**
While saving my configmap, it should also be committed to my app's config repository owned by Devtron app.

**Comment by prakarsh-dt** [comment]
Configmap, Secrets and deployment template versioning is handled on the UI now although it is not committed to the gitops repo. Hence, closing this as the usecase is addressed by the current implementation.
