### ISSUE TITLE
Bug: Pipeline addition not working properly in safari browser 

### ISSUE THREAD

**Issue by nitish768** [devtron-labs/devtron#2949]
### 📜 Description

User unable add multiple CD pipeline and also plus(+) sign is deflated as well in first addition.

### 👟 Reproduction steps

1- Open safari browser
2- Create a custom application
3- Add CI and CD pipe line
4- Add multiple CD pipe line

### 👍 Expected behavior

It should be add properly and also multiple pipeline addition should be there.

### 👎 Actual Behavior

It is actually while we adding the CD pipe line plus sign visible nearby CI pipeline and after that unable to add multiple 
CD pipeline.

### ☸ Kubernetes version

1.22 microk8s

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by milindk8** [comment]
Fixed in this PR:  https://github.com/devtron-labs/dashboard/pull/820
