### ISSUE TITLE
Installation status seems confusing/incomplete.

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#298]
**Use case:**
Since commands to check status and get password are provided as response after entering the last installation command, users might refer to other sources to understand the next steps and more info about them.

**Questions:**
Does “Downloaded” mean that the installation is complete?
How do I know how long will it take/how long I need to wait for the installation to finish?
How do I know what message to look for to know that the installation is complete? / I don’t know what applied means.

**Suggestion:**
Can we highlight the next steps in some way so that the info is not lost in the noise.
Using visual separator around the next steps might help.
We could also use colored text to highlight certain portions/text.

**Comment by uxarya-d** [comment]
To-do:
1. Explain what each status means along with the installation status checking command.
2. Use visual separator around the next steps.
3. Communicate next steps for kubectl installation in documentation (Heading hierarchy)

**Comment by pghildiyal** [comment]
Have introduced additional field - status_message inside status -> sync
This field will have following values

1. OutOfSync - URL change detected, new manifest will be downloaded
2. Downloaded - Installation manifest downloaded, will take ~30 mins to apply downloaded manifest
3. Applied - Manifest Applied and system is ready to use with newer version

Following command can be used to fetch status_message
kubectl -n devtroncd get installers installer-devtron -o jsonpath='{.status.sync.status_message}'
