### ISSUE TITLE
Bug: Application filter not working based on environment selection

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3001]
### 📜 Description

Application filter not working based on environment selection.

### 👟 Reproduction steps

1. Deploy multiple applications with multiple pipelines under same project.
2. Now try to add users by selecting specific environment you will see the application which is not even in this env
3. Now ask that user to open any application which he don't have the access.

### 👍 Expected behavior

After selecting environment it should load only those application which is have cd pipeline for these env.

### 👎 Actual Behavior

RIght now it is listing all the application created on selected project not checking the environment selected.

### ☸ Kubernetes version

1.21

### Cloud provider

<details>
AWS KOPS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
Not a bug, its a expected behavior.
