### ISSUE TITLE
SSO configuration is required before Adding user in user access

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#301]
Setting up SSO configuration should be a pre-requisite for grant permissions via user access.
Because, user can only login to the dashboard with an email id (via SSO) if the SSO is configured.

Proposal: https://www.figma.com/file/3XEoOGNg6cCpz4VfQSQlLX/Authorization?node-id=1613%3A10088&t=DynSf6BjZO0IlmuZ-4

**Comment by deepak-devtron** [comment]
This feature has been implemented already so closing it.
