### ISSUE TITLE
Feature: Helm Chart UI changes to show GUI option on re-deployments too

### ISSUE THREAD

**Issue by rishabhtayal72** [devtron-labs/devtron#3036]
### 🔖 Feature description

As of now when we configure & deploy a helm chart for the **1st time** we are shown below UI **(UI-1)**:

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/37596568/221105109-3c718bec-a037-4768-8c30-107ca7475669.png">

When we deploy the chart for the **2nd time** we are directly landed into values file as shown below **(UI-2)**:

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/37596568/221105496-ccca37ff-38ad-48ea-9763-b063837f0bac.png">
 
So the requirement is every time i go to configure and deploy the helm chart i should be displayed with the parametrised UI **(UI-1)** so that i can directly change those parameters and deploy directly.

### 🎤 Pitch

Why this feature should be implemented : 
Because every time i want to deploy a helm chart i don't want to go into my values file which could be a 500 lines of yaml, i instead would want to just change a few parameters and trigger the deployment.

Use Case / Example : 
I have an helm chart that runs a migration script. I only change one _command parameter_ before triggering deployment. So i want this to be displayed as parameterised **UI-1** every time before deployment.

### ✌️ Solution

This UI-1 is rendered through a schema.json, we just need to render it every time i click on configure button to configure helm chart.

### 🔄️ Alternative

None.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by milindk8** [comment]
Fixed the issue, now GUI is showing after deployment https://github.com/devtron-labs/dashboard/pull/801
