### ISSUE TITLE
Feature: Permission level for (build and deploy) and branch change for devtron apps.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3037]
### 🔖 Feature description

We want one more permission level who have  build and deploy permission and branch change permission for devtron apps.

### 🎤 Pitch

Right now developers , not able to change branch and test own branch code for CI who have build and deploy permission.

### ✌️ Solution

NA

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Already done as per @ajaydevtron
