### ISSUE TITLE
Bug: field values gets replaced in helm chart preset values

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#3069]
### 📜 Description

1. Name of preset values gets changed after selecting chart values.
2. Chart version remains unchanged after saving preset values.
3. Shows force delete pop-up window, when i try to delete preset values, however it is deleted.
4. After clicking cancel, it remains on UI.

### 👟 Reproduction steps

1. Create a preset values for a chart.
2. Create a new preset values with different name using same chart.
3. Check preset value name and chart version after saving it. This will be changed. (Happening only if chart values is select using pre-configured preset values)
4. Then try to delete the preset values.

### 👍 Expected behavior

Preset values details configurations should remain unchanged after saving it.

### 👎 Actual Behavior

Preset values details configurations gets changed after saving it.

### ☸ Kubernetes version

1.21

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shubham9t9** [comment]
![Screenshot 2023-03-02 at 12 02 01 PM](https://user-images.githubusercontent.com/87755583/222349347-ec5bec62-82f6-4dab-9db3-dd25497724ca.jpg)

**Comment by Shubham9t9** [comment]
![empuls](https://user-images.githubusercontent.com/87755583/226921297-b1f6f977-9da5-4209-a5bc-099e952d5eed.jpeg)

**Comment by Aravind-2023** [comment]
https://github.com/devtron-labs/dashboard/pull/967
