### ISSUE TITLE
Feature: Allow configuring custom buildpack builders in dropdown

### ISSUE THREAD

**Issue by benosman** [devtron-labs/devtron#3075]
### 🔖 Feature description

I would like to be able to use a custom buildpack builder when deploying an app, and if possible prevent the use of the existing ones.

### 🎤 Pitch

We have created custom builders based on Paketo Jammy to allow pre configuring the base images with our specific requirements, such as certificates, required packages, etc.

We are going to use these builders for all our apps, and it would be great if we could configure the list of builders in devtron to default to ours.

### ✌️ Solution

Offer a way to set the list of allowed builders for the dashboard and build process. It would be fine if it was set as an environment variable rather than choosing the list through the GUI.

### 🔄️ Alternative

I've looked through the docs to see if I could override it anywhere, but I couldn't find it, short of running a forked dashboard.

I also don't know if there is a constraint else where in the system for the allowed buildpacks,

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by uxarya-d** [comment]
Hi @benosman, thanks for opening the issue.

We've looked into your feature request and in the first phase, we're planning to, allow providing a custom builder image tag as input.

This should help in solving your primary use case.
In the future, we would look into providing the capability to set custom builders in addition to the predefined builder options.

We will let you know about the feature update when it is available.

**Comment by uxarya-d** [comment]
@benosman the feature for providing a `custom builder image tag` as input has been merged.
The update will be available in the next OSS release.
