### ISSUE TITLE
Bug: Wrong redirection for pre/post-cd logs details

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3140]
### 📜 Description

Wrong redirection for pre/post-cd logs details

### 👟 Reproduction steps

1. Configure one application with either pre-cd or post-cd step
2. Now trigger the pipelines and try to check the logs by clicking on the details for the respective pipeline(pre/post-cd).
3. It will redirect you to the latest triggered deployed.

### 👍 Expected behavior

It should redirect to the respective pipeline.

### 👎 Actual Behavior

It is redirecting to the latest triggered deploy details.

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by rish2320** [comment]
https://github.com/devtron-labs/dashboard/pull/1013
