### ISSUE TITLE
Bug: Details on app detail page are not persistence

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3141]
### 📜 Description

 Details on app detail page are not persistence

### 👟 Reproduction steps

1. Create a Devtron app with rawYaml having a Job manifest
2. In case of failed Job you would notice the snapshot issue.

### 👍 Expected behavior

It should show the correct value.

### 👎 Actual Behavior

It's not even showing on the page refresh
https://user-images.githubusercontent.com/85476803/226354281-ef288e66-d3b3-412f-817f-0838ef91591f.mov

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
fixed in https://github.com/devtron-labs/dashboard/pull/1071
