### ISSUE TITLE
Bug: Devtron can't handle the scenario where configMap and Secret are created with same name in same namespace

### ISSUE THREAD

**Issue by rishabhtayal72** [devtron-labs/devtron#3147]
### 📜 Description

If configMap and secret is created with same name (for ex. f-default), we can not add both in pre-deployment / post deployment and also we can't differentiate between the two.

### 👟 Reproduction steps

Create a configMap and secret by any name let say _f-default_ in a namespace let's say dev. 
Create an application in dev namespace. 
Attach both configMap and secret with the application created above.
Configure necessary steps.
Go to pre-deploy, search for adding configMap and secrets, there you will find 2 by the name of _f-default_. Here there are 2 issues : 
 - i) You can not differentiate which one is configMap and which is secret.
 - ii) Once you add any one you can not add the other one, it vanishes.

### 👍 Expected behavior

We should have been able to differentiate between the 2 and also add both. 

### 👎 Actual Behavior

explained above in reproduction steps.
adding screenshot..
![image](https://user-images.githubusercontent.com/37596568/226534888-d67086af-3455-4fa3-ab82-2b88e20ee989.png)

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

AWS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
Fixed in https://github.com/devtron-labs/dashboard/pull/854
