### ISSUE TITLE
Doc: Regading CI/CD module installation 

### ISSUE THREAD

**Issue by lalityadav1509** [devtron-labs/devtron#3173]
### 💭 Description

I have followed all the steps which were mentioned in the document however when i am installing build and deploy (CI/CD) in Devtron Stack Manager it is giving the error as below.

There was an error fetching the integration status. Please try again later.

![image](https://user-images.githubusercontent.com/43704554/226904968-eb24d554-97e8-4de9-9344-b5897db714be.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashokdevtron** [comment]
In subsequent versions of Devtron, this issue was not found. The logs are comparatively better now.
<img width="1424" alt="image" src="https://github.com/devtron-labs/devtron/assets/141001279/24ceed4d-2383-419d-bae5-d3efe2bceef9">

Hence, closing this issue.
