### ISSUE TITLE
Bug: Getting bad gateway during deleting CI pipeline 

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3198]
### 📜 Description

When going to delete any ci pipeline of devtron app getting bad gateway .
logs of devtron pod

{"level":"error","ts":1679985579.654767,"caller":"pipeline/PipelineBuilder.go:1305","msg":"error in deleting pipeline db","stacktrace":"github.com/devtron-labs/devtron/pkg/pipeline.PipelineBuilderImpl.DeleteCiPipeline\n\t/go/src/github.com/devtron-labs/devtron/pkg/pipeline/PipelineBuilder.go:1305\ngithub.com/devtron-labs/devtron/pkg/pipeline.PipelineBuilderImpl.PatchCiPipeline\n\t/go/src/github.com/devtron-labs/devtron/pkg/pipeline/PipelineBuilder.go:1206\ngithub.com/devtron-labs/devtron/api/restHandler/app.PipelineConfigRestHandlerImpl.PatchCiPipelines\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/app/BuildPipelineRestHandler.go:279\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go:145\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:128\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:71\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}

goroutine 848474 [running]:
net/http.(*conn).serve.func1()
   /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x4a41d40, 0x75c4280})
   /usr/local/go/src/runtime/panic.go:844 +0x258
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
   /go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/otel/sdk/trace/span.go:383 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc01427b380, {0x0, 0x0, 0xc00149ef80?})
   /go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/otel/sdk/trace/span.go:421 +0x93b
panic({0x4a41d40, 0x75c4280})
   /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/devtron-labs/devtron/api/restHandler/app.PipelineConfigRestHandlerImpl.PatchCiPipelines({{0x580fc88, 0xc001547c00}, {0x58095a0, 0xc00063cdf0}, {0x57f90e0, 0xc000870ad0}, {0x5802e08, 0xc0012aa000}, 0xc000636248, {0x58080b8, ...}, ...}, ...)
   /go/src/github.com/devtron-labs/devtron/api/restHandler/app/BuildPipelineRestHandler.go:280 +0xb3a
net/http.HandlerFunc.ServeHTTP(0x7fa910e7f540?, {0x57ee088?, 0xc0184e12c0?}, 0xc0017bba40?)
   /usr/local/go/src/net/http/server.go:2084 +0x2f
go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP({{0x506c345, 0xc}, {0x57bb000, 0xc002e638c0}, {0x57ecf48, 0xc001ec79f8}, {0x57c2d80, 0xc0017c4210}}, {0x7fa910e7f540, 0xc00d0baa50}, ...)
   /go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go:145 +0x6cf
github.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1({0x57ebdd8, 0xc00a779880}, 0xc006c69e00)
   /go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:128 +0x232
net/http.HandlerFunc.ServeHTTP(0xc006c69d00?, {0x57ebdd8?, 0xc00a779880?}, 0x16?)
   /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc001ae6b40, {0x57ebdd8, 0xc00a779880}, 0xc003562300)
   /go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
github.com/devtron-labs/authenticator/middleware.Authorizer.func1.1({0x57ebdd8, 0xc00a779880}, 0xc003562300)
   /go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:71 +0x3f1
net/http.HandlerFunc.ServeHTTP(0x0?, {0x57ebdd8?, 0xc00a779880?}, 0x18e8e85?)
   /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0x57d0f48?}, {0x57ebdd8, 0xc00a779880}, 0xc003562300)
   /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00ffb74a0, {0x57ee5e0, 0xc009af3f50})
   /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
   /usr/local/go/src/net/http/server.go:3071 +0x4db

### 👟 Reproduction steps

NA

### 👍 Expected behavior

It should delete the CI pipeline.

### 👎 Actual Behavior

<img width="1250" alt="Screenshot 2023-03-28 at 12 58 12 PM" src="https://user-images.githubusercontent.com/99399155/228161116-38e6611a-efa2-4449-89c3-55908c75deba.png">

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
RCA: response of service was being accessed without handling error first. Also, for ci pipeline material deletion update not null was being violated due to method change.
