### ISSUE TITLE
Bug: Job fails with non-interactive TTY error

### ISSUE THREAD

**Issue by kevin-delisle-peakpower** [devtron-labs/devtron#3218]
### 📜 Description

After the last step of a Job is _successfully executed_, a new and unexpected step labelled "BUILD" is triggered. This step immediately fails with this error:
```
------------------------------------------------------------------------------------------------------------------------
STAGE:  running PRE-CI steps
------------------------------------------------------------------------------------------------------------------------
2023/03/30 20:17:07 running step : Dummy Task
2023/03/30 20:17:07 variables with empty value : []
2023/03/30 20:17:07 running script commands
Nothing fancy
2023/03/30 20:17:07 
------------------------------------------------------------------------------------------------------------------------
STAGE:  Build
------------------------------------------------------------------------------------------------------------------------
Error: Cannot perform an interactive login from a non TTY device
2023/03/30 20:17:07 exit status 1
```

### 👟 Reproduction steps

1. Create a new Job
2. Create a new Step using the "Execute Custom Script" template.
3. Set the "Task Type" of the script to "Shell".
4. Paste in a very basic shell script:
```sh
#!/bin/sh 
set -eo pipefail 

echo "Nothing fancy"
```
5. Save the pipeline and run it.

### 👍 Expected behavior

Successfully execute the script, and report this success.

### 👎 Actual Behavior

Successfully executes the script, but then runs this extra "BUILD" step.

### ☸ Kubernetes version

EKS 1.22

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Firefox 111.0.1 (macOS)
### 🧱 Your Environment
Devtron v0.6.14

### ✅ Proposed Solution

I haven't familiarized myself with the codebase yet, but if I had to guess, I would say that some logic meant to prevent the pipeline builder from including a "Build" step is not correctly handling this case.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kripanshdevtron** [comment]
Hi @kevin-delisle-peakpower 
This issue is not reproducible but there might be a possibility of old CI-Runner image, can u pls share the output of following command:
```
kubectl get cm devtron-cm -ndevtroncd -o jsonpath='{.data.DEFAULT_CI_IMAGE}' && echo
```

**Comment by kevin-delisle-peakpower** [comment]
We're on the latest, I think: `quay.io/devtron/ci-runner:1d8a38a6-138-13253`

**Comment by prakarsh-dt** [comment]
Hi @kevin-delisle-peakpower ,
Do you have any Container registry configured in Global Configurations? 
If Yes, are the credentials valid?

**Comment by kevin-delisle-peakpower** [comment]
I have a working registry configuration using ECR. I have confirmed that it works as expected using another Devtron Apps pipeline (successfully building the image, pushing the image, pulling the image and consuming it in a deployment).

Additionally, I've noticed that it doesn't seem to use the assigned role or credentials, even though I can see the AWS keypair (access key/secret key) mounted in the container.
I've also confirmed the mounted credentials return the appropriate identity when I run `aws sts get-caller-identity`.

**Comment by kripanshdevtron** [comment]
Have u tried creating more jobs, is this issues happening with every job ??
To discuss more on this in detail, pls ping here ```https://discord.devtron.ai/9649```

**Comment by kevin-delisle-peakpower** [comment]
Strangely enough, I just attempted to reproduce the issue now (while making screenshots to detail what I was seeing earlier), but now I can't reproduce the problem! If I end up running into this issue again soon, I'll report back here, but for now I think we can close this.
