### ISSUE TITLE
Bug: Pod age not visible in app details page on firefox

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3239]
### 📜 Description

Pod age not visible in app details page on firefox

### 👟 Reproduction steps

Open any app details page on firefox browser and on any other browser like chrome

### 👍 Expected behavior

Should show pod age on both the browsers

### 👎 Actual Behavior

Doesn't show the pod age on firefox browser but shows the same on chrome

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
RCA: Kubelink was sending timestamp in format - "2023-04-05 05:01:28 +0000 UTC" which is not supported by firefox. Updated it to zero hour format.
