### ISSUE TITLE
Bug: Not able to view linked-ci pipeline details

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3241]
### 📜 Description

After creating a linked-ci pipeline from a webhook-based parent pipeline not able to view the details.

### 👟 Reproduction steps

1. Create a application(parent) having PR/Tag-Based build pipeline.
2. Create another application or in the same application add another build pipeline as a linked-ci pipeline.
3. Try to view the configuration(for the child pipeline) in the workflow editor itself.

### 👍 Expected behavior

It shouldn't break the page.

### 👎 Actual Behavior

Right now it's breaking the page and showing the below error page.
<img width="1440" alt="Screenshot 2023-04-05 at 6 32 15 PM" src="https://user-images.githubusercontent.com/85476803/230088399-6823863c-6600-499b-80ca-b2795a821bfe.png">

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
EKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vivek-devtron** [comment]
Fixed with sentry issues
