### ISSUE TITLE
Bug: On creating new linked build pipeline it's throwing error in case of overridden parent pipeline

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3242]
### 📜 Description

We are trying to create a new linked-build pipeline but it's throwing 502 in case of selecting overridden parent build pipeline.

### 👟 Reproduction steps

1. Create a build pipeline(parent) and override the configuration.
2. create a new linked-build pipeline by selecting the above create overridden parent pipeline.

### 👍 Expected behavior

It's throwing an error on UI but in the backend, it's getting created, but also not able to delete the same child pipeline.

### 👎 Actual Behavior

It's failing for now and also not able to delete the same pipeline.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
EKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
RCA: In case of pipeline made from parent ci pipeline which had docker build config overridden, object for saving audit log of the same was not being updated by code and thus caused panic when accessed. For panic at deletion, ci build configuration was being accessed in case of external pipeline whereas the configuration is present at its parent level only.
