### ISSUE TITLE
Bug: Getting job in navigation bar for Hyperion (non-cicd) installation

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#3254]
### 📜 Description

when we install devtron (hyperion) without CICD option. there it show the `job` option in navigation bar on right side and when we click it, then it is showing   page not found.

### 👟 Reproduction steps

1. make a new cluster or uninstall the previously installed devtron
2. install non cicd -- https://docs.devtron.ai/install/install-devtron-on-minikube-microk8s-k3s-kind
3. open the dashboard in browser.

### 👍 Expected behavior

It should not show the Job option for non-cicd installation.

### 👎 Actual Behavior

It is showing the job option in navigation bar.
<img width="1440" alt="Screenshot 2023-04-07 at 1 28 19 PM" src="https://user-images.githubusercontent.com/122791251/230572505-e713bab5-061b-42a5-9a6b-39853cf5d83d.png">

### ☸ Kubernetes version

cluster -  Microk8s
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-17T19:58:33Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-17T19:59:21Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

<details>
Azure VM
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by sohel-rp** [comment]
This issue has been addressed under https://github.com/devtron-labs/dashboard/pull/891
