### ISSUE TITLE
Bug: Helm apps with NO_GITOPS doesn't fetch child resources from CRDs

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3271]
### 📜 Description

Helm apps with NO_GITOPS doesn't fetch child resources from CRDS

### 👟 Reproduction steps

1. Deploy latest kube-prometheus-stack in NO_GITOPS mode

### 👍 Expected behavior

Prometheus and Alertmanagers are CRDs which creates statefulsets as child objects, so those statefulsets should be available

### 👎 Actual Behavior

The statefulsets shared above aren't available in helm app details page but visible in resource browser which confirms that statefulsets were created

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2722

**Comment by kamal-devtron** [comment]
It is happening same for Keda as Hpa resources are not visible in App detail page
