### ISSUE TITLE
Bug: Helm App details page showing wrong env in dropdown

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3272]
### 📜 Description

Helm App details page showing the wrong env in the dropdown.

### 👟 Reproduction steps

NA

### 👍 Expected behavior

It should only show deployed environment.

### 👎 Actual Behavior

It's showing any random in the dropdown
<img width="1440" alt="Screenshot 2023-04-12 at 5 43 00 PM" src="https://user-images.githubusercontent.com/85476803/231453486-164fb564-c911-455d-abe7-c37ba3636ad6.png">

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
EKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2724

**Comment by vivek-devtron** [comment]
Fixed in optimization branch
