### ISSUE TITLE
Bug: not able to see respective apps in search bar when you have specific permission

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#3273]
### 📜 Description

not able to see respective apps in search bar when i have. specific permission on the cluster
<img width="1113" alt="Screenshot 2023-04-12 at 6 18 06 PM" src="https://user-images.githubusercontent.com/130441461/231462136-0592ab74-0497-4ed4-92b1-d0b985246cfb.png">

### 👟 Reproduction steps

just access the search bar and your access should not be super-admin

### 👍 Expected behavior

it should be show the apps you have access
<img width="851" alt="Screenshot 2023-04-12 at 6 19 15 PM" src="https://user-images.githubusercontent.com/130441461/231462748-534ed669-9f2c-4b44-9b9d-db164d483125.png">

### 👎 Actual Behavior

showing nothing in case you have specific permission on cluster and show no apps which apps permission you have.
but it should not be in access thing it should have to see the apps which have acess to you but its showing nothing

### ☸ Kubernetes version

EKS

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2725

**Comment by vikramdevtron** [comment]
Fixed in https://github.com/devtron-labs/devtron/pull/3292
