### ISSUE TITLE
Bug: Not able to view application even with the proper permission

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3308]
### 📜 Description

I've given a user permission for multiple applications but the changes didn't reflect on the database of casbin but it's showing on UI as it got updated on orchestrator database.

### 👟 Reproduction steps

NA

### 👍 Expected behavior

Access should get reflect on the db and users should be able to view applications on UI applications

### 👎 Actual Behavior

It's not getting reflected on the database, so the user cannot view the application.

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2827

**Comment by badal773** [comment]
not reproduce now
