### ISSUE TITLE
form based deployment template edit

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#331]
# Summary 
Add option of form based values.yaml edit 

# Motivation

currently we take values corresponding to deployment template in json/yaml form user. 
observations: 

- it appears more complex than it should be to the normal user.
- json format is not being used

# Proposal

- remove json based values editing 
- user should have option to edit deployment template in 
     - yaml format 
     - form based editor for most frequently used params
     - user can toggle between to format

**Comment by abhibhaw** [comment]
This is already done
