### ISSUE TITLE
errdial tcp: lookup devtron-nats.devtroncd: i/o timeout

### ISSUE THREAD

**Issue by falser101** [devtron-labs/devtron#3342]
![image](https://user-images.githubusercontent.com/62228193/236135296-c6d1b023-d55b-465c-8c70-e35d1e5353fd.png)

`{"level":"error","ts":1683183773.710971,"caller":"pubsub-lib/NatsClient.go:98","msg":"errdial tcp: lookup devtron-nats.devtroncd: i/o timeout","stacktrace":"github.com/devtron-labs/common-lib/pubsub-lib.NewNatsClient\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go:98\ngithub.com/devtron-labs/common-lib/pubsub-lib.NewPubSubClientServiceImpl\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go:33\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/devtron/wire_gen.go:164\nmain.main\n\t/go/src/github.com/devtron-labs/devtron/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"fatal","ts":1683183773.7110474,"caller":"pubsub-lib/PubSubClientService.go:35","msg":"error occurred while creating nats client stopping now!!","stacktrace":"github.com/devtron-labs/common-lib/pubsub-lib.NewPubSubClientServiceImpl\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go:35\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/devtron/wire_gen.go:164\nmain.main\n\t/go/src/github.com/devtron-labs/devtron/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}`

when i use helm to install the devtron, the pod devtron-868b59985b-g9vjt status is error, how can i resolve this error?

the image is quay.io/devtron/devtron:9f3934ee-434-13409

AB#2938

**Comment by falser101** [comment]
@pawan-mehta-dt

**Comment by pawan-mehta-dt** [comment]
Can you share output of `kubectl get po -n devtroncd`?

**Comment by falser101** [comment]
> kubectl get po -n devtroncd

![image](https://user-images.githubusercontent.com/62228193/236137309-7173ae25-3a13-4c70-9b99-2969aea392a1.png)

**Comment by pawan-mehta-dt** [comment]
Can you share logs from inception pod?

**Comment by pawan-mehta-dt** [comment]
Can you share output of `kubectl get installer -n devtroncd -o yaml`?

**Comment by falser101** [comment]
My environmental issue has been successfully deployed in another set of K8S clusters, thanks
