### ISSUE TITLE
Bug: during commit hash check its throwing error

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#3352]
### 📜 Description

during commit hash check its throughing error if the commit hash is not present ;
actual-: their should be no result if the commit has is not present 
         -: Commit not found

### 👟 Reproduction steps

use latest enterprise release

### 👍 Expected behavior

<img width="792" alt="Screenshot 2023-05-08 at 12 31 36 PM" src="https://user-images.githubusercontent.com/130441461/236757062-448d20aa-ccee-41a1-a783-3b6e3b226bcf.png">

### 👎 Actual Behavior

<img width="623" alt="Screenshot 2023-05-08 at 12 06 37 PM" src="https://user-images.githubusercontent.com/130441461/236757414-9147077b-e493-4d53-b8c8-f2a5f59f6138.png">

### ☸ Kubernetes version

AKS 1.24.9

### Cloud provider

<details>
AZURE
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

please cheack the grpc port 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2967

**Comment by mayank-devtron** [comment]
https://github.com/devtron-labs/devtron/issues/3499

merged with another issue

**Comment by vikramdevtron** [comment]
@badal773 not able to replicate

**Comment by vikramdevtron** [comment]
Closed in https://github.com/devtron-labs/dashboard/pull/1299
