### ISSUE TITLE
Bug: Accessing users role and groups throwing "We encountered an error"

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#3360]
### 📜 Description

After editing user permission,user is getting error "We encountered an error" while checking user/group info 
<img width="1028" alt="Screenshot 2023-05-09 at 4 16 08 PM" src="https://github.com/devtron-labs/devtron/assets/44662963/432b6ecf-eaac-4e55-aa44-cc2e57049ab8">

### 👟 Reproduction steps

Change user permission to manager and so and then try to access groups and users

### 👍 Expected behavior

Will be able to access groups info if there is the access to view

### 👎 Actual Behavior

Throwing the error "We encountered an error"

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2979

**Comment by kartik-579** [comment]
RCA: the api for fetching default roles had rbac for superadmin imposed on it which made it forbidden for managers to get the results and thus made the UI break.
