### ISSUE TITLE
Bug: Increase in failed or unhealthy deployments slows down devtron

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3375]
### 📜 Description

Increase in failed or unhealthy deployments slows down devtron

### 👟 Reproduction steps

1. Have large number of cd pipelines
2. Trigger bulk deployments for 2-3 environments and see if multiple deployments are unhealthy

### 👍 Expected behavior

Devtron operations should remain unaffected

### 👎 Actual Behavior

Increases CPU load due to continous checks of unhealthy deployments and slows down app details and other pages as well as operations

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2997

**Comment by kartik-579** [comment]
fixed with #3372
