### ISSUE TITLE
Bug: mkdir /ssh-keys/2: permission denied

### ISSUE THREAD

**Issue by kordeviant** [devtron-labs/devtron#3380]
### 📜 Description

inside build & deploy section when devtron tries to show git info and access repo,
this error comes up: mkdir /ssh-keys/2: permission denied

### 👟 Reproduction steps

when trying to add gitlab.com and selecting private ssh key

### 👍 Expected behavior

it should show my commits on that repo

### 👎 Actual Behavior

mkdir /ssh-keys/2: permission denied

### ☸ Kubernetes version

microk8s latest

### Cloud provider

<details>
kubernetes personal
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3008

**Comment by pawan-mehta-dt** [comment]
Try this for a quick fix
`kubectl edit sts git-sensor -n devtroncd`
For container git-sensor, remove `allowPrivilegeEscalation: false` and `runAsNonRoot: true` under securityContext as well as change runAsUser to 0 from 1000
let us know if this works for you

**Comment by pawan-mehta-dt** [comment]
Fixed by #3393
