### ISSUE TITLE
Provide the funcationality of build and deploy by github release

### ISSUE THREAD

**Issue by sahilkukkar** [devtron-labs/devtron#339]
# Summary

What change you think needs making.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

**Comment by prakarsh-dt** [comment]
Github releases are linked with a PR, you can already build based on Github PR (https://github.com/devtron-labs/devtron/issues/2151).

I think should now be achieveable with a combination of webhook triggered ci api, but not integrated by default in the CI as of now
