### ISSUE TITLE
Doc: YAML based manifest deployments

### ISSUE THREAD

**Issue by thecloudgarage** [devtron-labs/devtron#3392]
### 💭 Description

I have a plain YAML based manifest file for an app deployment (not a Helm but YAML based) and the application is already built and docker image is already available. How do I deploy this YAML based deployment via Devtron (basically use only the CD part and not CI)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3091

**Comment by satyampsoni** [comment]
Using [deployment charts](https://docs.devtron.ai/global-configurations/deployment-charts), you can do it.

**Comment by satyampsoni** [comment]
@thecloudgarage if this answers your question, please close the issue.
