### ISSUE TITLE
Bug: Artifact option should be there in CD pipeline

### ISSUE THREAD

**Issue by nitish768** [devtron-labs/devtron#3418]
### 📜 Description

Artifact and report should be there in CD pipeline and also image should be not there.

### 👟 Reproduction steps

1-Create an app with Pre post CD 
2-Verify deployment history

### 👍 Expected behavior

-In deployment history Artifacts option should be there
-In deployment history image should be not there

### 👎 Actual Behavior

-In deployment history Artifacts option is not there
-In deployment history image is there

### ☸ Kubernetes version

microk8s:2.6

### Cloud provider

Azure

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3171

**Comment by rish2320** [comment]
Already resolved in previous dev.

**Comment by rish2320** [comment]
Already resolved in previous dev.
