### ISSUE TITLE
Feature:  Expose the build process time into stage wise.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3422]
### 🔖 Feature description

We want to analyse time taken by every build stage during the app build.

### 🎤 Pitch

Want to see the build stage time for per build , right now multiple stage happen after trigger a build.

- CI node provisioning
- download build cache(if blob storage configured )
- git cloning
- pre ci steps
- build stage
- post build steps
- image scan
- upload build cache (if blob storage configured )

### ✌️ Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3180

**Comment by rishabhtayal72** [comment]
**Need** : Both stage wise time as well as total build time.
**Good to have** : Average build time. (based upon past builds average)
cc : @prakarsh-dt @vikramdevtron

**Comment by abhibhaw** [comment]
This is already completed
