### ISSUE TITLE
Bug: Showing multiple apps of same helm app with different chart versions

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#3429]
### 📜 Description

1- Devtron showing 2 apps for same application with two different chart versions
2- When the app was deployed it got deployed with old chart version which caused the issue

### 👟 Reproduction steps

make true as the all chart version of app_chart_in_use table  in database then deploy

for more connect to devops team

### 👍 Expected behavior

their should showing only one app and form the latest values.yaml the values must be taken

### 👎 Actual Behavior

<img width="1318" alt="Screenshot 2023-05-25 at 8 33 08 PM" src="https://github.com/devtron-labs/devtron/assets/130441461/ca490abe-f992-4a76-8b25-4a0160272e99">

### ☸ Kubernetes version

1.26

### Cloud provider

<details>

</details>
azure

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3188

**Comment by vikramdevtron** [comment]
@badal773 please verify if this still exists

**Comment by badal773** [comment]
The issue was not reproducible closing this ticket.
