### ISSUE TITLE
Bug: Chart group not visible with specific chart group permission 

### ISSUE THREAD

**Issue by nitish768** [devtron-labs/devtron#3461]
### 📜 Description

Chart group not visible with specific chart group option 

### 👟 Reproduction steps

-Create a chart group
-User should access for specific chart group
- Try to create or update chart group

### 👍 Expected behavior

If user having edit option for specific chart group then user can edit and update the specific chart

### 👎 Actual Behavior

while user editing option for specific chart group then user unable to edit and update the specific chart

### ☸ Kubernetes version

microk8s:2.6

### Cloud provider

Azure 

### 🌍 Browser

Chrome

### 🧱 Your Environment

QA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3469

**Comment by Ash-exp** [comment]
closed in 
OSS PR: https://github.com/devtron-labs/devtron/pull/3962
Dashboard PR: https://github.com/devtron-labs/dashboard/pull/1315

**Comment by Ash-exp** [comment]
closed in 
OSS PR: https://github.com/devtron-labs/devtron/pull/3962
Dashboard PR: https://github.com/devtron-labs/dashboard/pull/1315
