### ISSUE TITLE
Bug: Unchecking Exclude specific file/folder in repo is not working

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#3465]
### 📜 Description

It bugs out when you want to uncheck `Exclude specific file/folder in repo`. 
Correct value is not going in payload.

### 👟 Reproduction steps

As shown below : 

<img width="599" alt="image" src="https://github.com/devtron-labs/devtron/assets/135199635/fddb4182-7714-466d-8787-3cfac608e085">

If you uncheck `Exclude specific file/folder in this repo` and save, it will throw material saved successfully but changes will not be reflected if you refresh the page.

### 👍 Expected behavior

It should have unchecked and saved the changes

### 👎 Actual Behavior

It still shows checked with the same path configured even when unchecking and saving.

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

My env is not customised.

### ✅ Proposed Solution

I could see wrong payload is going when you uncheck and save.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3495

**Comment by vivek-devtron** [comment]
Fixed in  https://github.com/devtron-labs/dashboard/pull/1032
