### ISSUE TITLE
Bug: Devtron Apps are stuck in progressing state and helm apps are not getting deployed via argocd even though gitops is selected.

### ISSUE THREAD

**Issue by rishabhtayal72** [devtron-labs/devtron#3514]
### 📜 Description

None of the newly created Devtron applications are getting deployed. They are getting stuck in progressing state. 
And Helm applications are by default getting deployed via helm (nogitops). 
Even though we have not enabled helm.

### 👟 Reproduction steps

NA

### 👍 Expected behavior

Application should have been deployed using argocd and should been available in argo.  

### 👎 Actual Behavior

But Devtron app is getting stuck.

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3761

**Comment by iamayushm** [comment]
https://github.com/devtron-labs/devtron-enterprise/pull/255
