### ISSUE TITLE
Bug: Application status showing null in exported csv .

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3517]
### 📜 Description

There are no any application status showing in exported csv.
<img width="937" alt="Screenshot 2023-06-15 at 3 07 44 PM" src="https://github.com/devtron-labs/devtron/assets/99399155/645ad646-45b4-4592-abcc-3396a635f772">

### 👟 Reproduction steps

1. deploy 3-4 application in cluster
2. click on export csv and see the csv data.

### 👍 Expected behavior

It should show the application status as well 

### 👎 Actual Behavior

Right now application status is blank

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3775

**Comment by Ash-exp** [comment]
closed in 
OSS PR: https://github.com/devtron-labs/devtron/pull/3962
Dashboard PR: https://github.com/devtron-labs/dashboard/pull/1315
