### ISSUE TITLE
Feature: Capability to promote ECR Images from non-prod to prod as part of pre-cd plugin 

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#3521]
### 🔖 Feature description

There should be some way to selectively promote an ECR image from non-prod ECR to prod ECR. This can be integrated as a plugin in pre-cd.

### 🎤 Pitch

In my use-case i will be having 2 ECRs : i) non-prod ECR and ii) prod ECR.
I will be building images and pushing to non-prod ECR for various environments. But i want to selectively promote an image (let say v1.0.9) to prod ECR. I don't want to build the same piece of code again for production. 

### ✌️ Solution

I want to have this as a plugin within pre-cd to trigger a job to promote (share) an ECR image from non-prod to prod. 
Then simply deploy the same to production.

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3783

**Comment by prakarsh-dt** [comment]
Please ensure this works for multi-arch images too.
