### ISSUE TITLE
Bug: Build stage configuration gets stuck if central-api is not reachable from client browser

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3536]
### 📜 Description

Build stage configuration gets stuck if central-api is not reachable from client browser

### 👟 Reproduction steps

1. Setup devtron in an environment from where central api endpoint isn't accessible.
2. Try to setup your first workflow

### 👍 Expected behavior

1. It should allow everything without any issues

### 👎 Actual Behavior

1. It blocks saving the configuration and doesn't allow to edit anything and save button keeps loading for infinite time and then timeouts

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3905

**Comment by sohel-rp** [comment]
Added a new state for handling scenario & unblocked users to save or update config that use I've docker file option. PR - https://github.com/devtron-labs/dashboard/pull/1086
