### ISSUE TITLE
Bug: Show application metrics and README is not visible for Job & Cronjob and StatefulSets chart type.

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#3548]
### 📜 Description

In Base deployment template configuration of an application, we have an option for 'Show application metrics' and README. This option is not visible if chart type is selected Job and CronJob & StatefulSets without switching deployment template type from Basic to Advanced (YAML). But we can get this option if we change the chart to advanced initially.  However we get this option after saving it and coming back to deployment template configuration.

### 👟 Reproduction steps

1. Create a new application.
2. Configure Git Repository and Build Configuration.
3. While configuring Base Deployment Template, select chart type Job and CronJob or StatefulSets with changing from Basic to Advanced.
4. You'll not get the option for 'Show application Metrics' and README on deployment template page.
5. But we can get this option if we change the chart to advanced initially.

### 👍 Expected behavior

'Show application metrics' and README option should be there.

### 👎 Actual Behavior

'Show application metrics' and README option is not there.

### ☸ Kubernetes version

EKS 1.25

### Cloud provider

<details>
EKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3940

**Comment by Shubham9t9** [comment]
![Screenshot 2023-06-21 at 11 52 57 AM](https://github.com/devtron-labs/devtron/assets/87755583/b36e3ac8-71a1-4559-893b-839a9dffff6a)

**Comment by aman10000q** [comment]
now you can see application metrics option even in statefulset , job and cron job
