### ISSUE TITLE
Build and Deployment pipeline > Proper validation and validation message for pipeline name

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#355]
# Summary
Build and deployment pipeline name field should have proper validation

# Current behavior
1. Proper validation does not exist for CI/build pipeline name
2. If user enters something invalid error being shown is "Some required fields are missing" [Refer screenshot]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/73632042/189474756-1659de79-b562-44d1-8587-13f0c0f8b91b.png">

# Expected behavior
1. Proper input validation error message should be shown below the Pipeline Name field.
2. "Some required fields are missing" toast message should not be shown in this case.

AB#279

**Comment by kapishmalik** [comment]
@uxarya-d I would like to work on this issue.

**Comment by uxarya-d** [comment]
@kapishmalik Sure. Let me revisit this and get back to you.
