### ISSUE TITLE
Bug: Preset value unable to delete due to cluster unreachable 

### ISSUE THREAD

**Issue by nitish768** [devtron-labs/devtron#3550]
### 📜 Description

If we created any preset value then open the same preset and try to delete which one are created it is showing cluster unreachable.
![image](https://github.com/devtron-labs/devtron/assets/84236481/40e6f919-83fe-40a3-9676-74d31b147293)

### 👟 Reproduction steps

1 - Go to chart store
2-create preset value
3-Then open same preset value
4-Delete the same preset value

### 👍 Expected behavior

If we delete Preset value it should be delete with proper delete successful notification.

### 👎 Actual Behavior

While we deleting Preset value unable to delete due to cluster unreachable.

### ☸ Kubernetes version

AKS: 1.26

### Cloud provider

Azure

### 🌍 Browser

Chrome

### 🧱 Your Environment

Staging

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3944

**Comment by Ash-exp** [comment]
closed in 
OSS PR: https://github.com/devtron-labs/devtron/pull/3962
Dashboard PR: https://github.com/devtron-labs/dashboard/pull/1315
