### ISSUE TITLE
Bug: Pass/Failure Condition is not working as expected in pre build step.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3554]
### 📜 Description

1. During the **Set failure condition** for combination of multiple variables , here we are doing **AND** operation across all conditions but it should be **OR**
2. During the **Set pass conditions** for combination of multiple variables here we are doing **OR** operation across all conditions but it should be **AND** 

Exporting the value of x and y variables .

<img width="1421" alt="Screenshot 2023-06-22 at 5 22 57 PM" src="https://github.com/devtron-labs/devtron/assets/99399155/4d3d509f-b878-405c-8fb4-2d35a93cd20b">

Set failure condition.
<img width="1422" alt="Screenshot 2023-06-22 at 5 23 14 PM" src="https://github.com/devtron-labs/devtron/assets/99399155/5eba1c20-de27-4733-b215-2e1e24061acf">

Here build should fail but here it tigger the build stage.

<img width="1299" alt="Screenshot 2023-06-22 at 5 28 22 PM" src="https://github.com/devtron-labs/devtron/assets/99399155/988f9b96-c884-4d31-908a-92a1ee7e5b88">

### 👟 Reproduction steps

1. Create a Devtron app .
2. Go into pre build stage and add below script .`#!/bin/sh 
set -eo pipefail 
#set -v  ## uncomment this to debug the script 
export x=2
export y=0
echo "The value of x and y are $x, $y"
`
3. Set output variables for x and y as number.
4. Set failure condition for x and y as shown in screenshot and trigger the build.

### 👍 Expected behavior

It should block the build stage.

### 👎 Actual Behavior

Right now it tigger the build stage.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3948

**Comment by abhibhaw** [comment]
This is fixed with #3938
