### ISSUE TITLE
Bug: Incorrect Dex config when trying to use SSO private Gitlab instance.

### ISSUE THREAD

**Issue by JaysonHaulkory** [devtron-labs/devtron#3568]
### 📜 Description

Hello the issue is that i can't modify what gitlab instance is used when i try to set up SSO with dex and gitlab(only use gitlab.com by default), when i try to configure baseURL : <my-gitlabinstance.com> as indicated in the dex [documentation](https://dexidp.io/docs/connectors/gitlab/#:~:text=baseURL%3A%20https%3A//gitlab.com) (that is recommended by devtron).
The devtron instance says that the config is then saved but then the config change to this : 
<br/> 
config:
    type: gitlab
    name: GitLab
    id: gitlab
    config:
        issuer: ""
        clientID: ••••••••
        clientSecret: ••••••••
        redirectURI: http://<ip>/orchestrator/api/dex/callback
        hostedDomains: null
<br/>
when it should look like this : <br/>

config:
  type: gitlab
  id: gitlab
  name: GitLab
  config:
    baseURL: <my-gitlabinstance.com>
    clientID: $GITLAB_APPLICATION_ID
    clientSecret: $GITLAB_CLIENT_SECRET
    redirectURI: http://devtron.yourdomain.com/orchestrator/api/dex/callback
    groups:
      - users
    useLoginAsID: false
    
<br/>

container logs when saving the config: <br/>

{"level":"info","ts":1687856159.945503,"caller":"sso/SsoLoginHandler.go:113","msg":"request payload, UpdateSSOLoginConfig","payload":{"
id":1,"name":"gitlab","url":"http://my-devtron-ip/orchestrator","config":{"id":"gitlab","type":"gitlab","name":"GitLab","config":{"base
URL":"<gitlab-private-instance.com>","clientID":"private-gitlab-clientID","clientS
ecret":"private-gitlab-clientSecret","redirectURI":"http://my-devtron-ip/orchestrator/api/dex/call
back","useLoginAsID":false}},"active":true}}
{"level":"info","ts":1687856159.9768374,"caller":"auth/UserAuthOidcHelper.go:84","msg":"updating in memory data on sso update","ssoUrl"
:"http://my-devtron-ip/orchestrator"}
time="2023-06-27T08:55:59Z" level=info msg="proxy server address:  http://argocd-dex-server.devtroncd:5556"
time="2023-06-27T08:55:59Z" level=info msg="Creating client app (argo-cd)"
 <br/>
And the dex server logs(that do receive the config change but does not save the baseURL): <br/>

2023/06/27 08:34:25 starting dex
2023/06/27 08:34:25 dex started
time="2023-06-27T08:34:25Z" level=info msg="config issuer: http://my-devtron-ip/orchestrator/api/dex"
time="2023-06-27T08:34:25Z" level=info msg="config storage: memory"
time="2023-06-27T08:34:25Z" level=info msg="config static client: devtron"
time="2023-06-27T08:34:25Z" level=info msg="config connector: gitlab"
time="2023-06-27T08:34:25Z" level=info msg="config skipping approval screen"
time="2023-06-27T08:34:25Z" level=info msg="config refresh tokens rotation enabled: true"
time="2023-06-27T08:34:25Z" level=info msg="keys expired, rotating"
time="2023-06-27T08:34:25Z" level=info msg="keys rotated, next rotation: 2023-06-27 14:34:25.421749447 +0000 UTC"
time="2023-06-27T08:34:25Z" level=info msg="listening (telemetry) on 0.0.0.0:5558"
time="2023-06-27T08:34:25Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2023-06-27T08:34:25Z" level=info msg="listening (grpc) on 0.0.0.0:5557"
<br/>
the config file that is saved in dex container: <br/>
connectors:
    - config:
        clientID: private-gitlab-clientID
        clientSecret: private-gitlab-clientSecret
        hostedDomains: null
        issuer: ""
        redirectURI: http://my-devtron-ip/orchestrator/api/dex/callback
      id: gitlab
      name: GitLab
      type: gitlab
grpc:
    addr: 0.0.0.0:5557
issuer: http://my-devtron-ip/orchestrator/api/dex
oauth2:
    skipApprovalScreen: true
staticClients:
    - id: argo-cd
      name: devtron
      redirectURIs:
        - http://my-devtron-ip/orchestrator/auth/callback
      secret: auto-gen-dex-secret
storage:
    type: memory
telemetry:
    http: 0.0.0.0:5558
web:
    http: 0.0.0.0:5556
    
 <br/>
 
Did i made a mistake on the config, somewhere else or maybe private gitlab instance is not supported 🤔  ?
    

### 👟 Reproduction steps

Global configurations>SSO Login Service>Gitlab:

then follow the [documentation](https://dexidp.io/docs/connectors/gitlab/) to configure dex
save, devtron instance sees no error and say Saved Succesfully
go to login page (disconnect admin or open other browser)
try to login with gitlab and getting redirected to gitlab.com when it should redirect to my-gitlab-instance.com to login

### 👍 Expected behavior

Should redirect to my private gitlab instance to login

### 👎 Actual Behavior

Redirect to gitlab.com for login

### ☸ Kubernetes version

AKS 1.25

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4002

**Comment by pawan-mehta-dt** [comment]
@JaysonHaulkory Can you check what's the dex config saved in devtron-secret in devtroncd namespace? is it what you expected?

**Comment by JaysonHaulkory** [comment]
> @JaysonHaulkory Can you check what's the dex config saved in devtron-secret in devtroncd namespace? is it what you expected?

@pawan-mehta-dt it's the same config that is pushed to dex server, i tried to restart dex pod already
config in secret look like this(after decode) : <br/>
connectors:
- config:
    clientID: private-gitlab-clientID
    clientSecret: private-gitlab-clientSecret
    hostedDomains: null
    issuer: ""
    redirectURI: http://my-devtron-ip/orchestrator/api/dex/callback
  id: gitlab
  name: GitLab
  type: gitlab
  
 
should look like this : <br/>
type: gitlab
id: gitlab
name: GitLab
config:
    baseURL: <my-gitlabinstance.com>
    clientID: private-gitlab-clientID
    clientSecret: private-gitlab-clientSecret
    redirectURI: http://my-devtron-ip/orchestrator/api/dex/callback
    useLoginAsID: false

What is weird is that it is the right clientID and Secret but only, those get saved the rest just vanish

**Comment by pawan-mehta-dt** [comment]
Can you share a screenshot from devtron UI?
hide your credentials in the same

**Comment by JaysonHaulkory** [comment]
Sure:
Config before clicking update:
![ConfigBeforeUpdate](https://github.com/devtron-labs/devtron/assets/58566653/57ba5304-8640-4ff8-bcd1-3a66e4aa7c50)
Config the moment i click update:
![AfterClickUpdate](https://github.com/devtron-labs/devtron/assets/58566653/af910ae9-f037-4b9e-80c9-ce859c5c45e5)


Only work around for now that i found is to edit the dex config saved in devtron-secret in devtroncd namespace with the right config, delete the dex pod and it should restart with the correct baseURL.

**Comment by JaysonHaulkory** [comment]
Also, maybe linked to this [issue](https://github.com/devtron-labs/devtron/issues/3540)

**Comment by pawan-mehta-dt** [comment]
@JaysonHaulkory are you able to get it working for you?

**Comment by JaysonHaulkory** [comment]
I can change manually the devtron secret and change the dex config, restart the pod and then it redirect me to my gitlab intance but i have other problems down the road, i don't know if it's linked but when i try to connect with my gitlab instance i get an error : Please login again, and in the pod logs it tell me there is no token in request that is processed ({"level":"info","ts":1687936837.4335184,"caller":"user/UserAuthService.go:455","msg":"no token provided"})

**Comment by pawan-mehta-dt** [comment]
Can you confirm if you have added your email with which you are trying to login in Global Configurations > Authorization > User Permissions?

**Comment by JaysonHaulkory** [comment]
It was that, i still have a 502 but this solve the no token :)
Also, is there a way to auto enroll new user ?

**Comment by prakarsh-dt** [comment]
Similar to #3540
