### ISSUE TITLE
Bug: We are not hitting "/orchestrator/app/list/v2" in Hyperion mode from dashboard

### ISSUE THREAD

**Issue by nitish768** [devtron-labs/devtron#3577]
### 📜 Description

While setup devtron with Hyperion mode and deploy any helm app or external helm app , Verify the app list no any deployed app showing in app list.

### 👟 Reproduction steps

1-install devtron in Hyperion mode
2- deploy any helm app 
3-verify list of deployed helm app
4- upgrade to CI CD 
5- deploy External helm app
6- Verify the deployed external helm app

### 👍 Expected behavior

While setup devtron with Hyperion mode and deploy any helm app or external helm app and Verify the app list all deployed app should be visible.

### 👎 Actual Behavior

While setup devtron with Hyperion mode and deploy any helm app or external helm app and Verify the app list no any deployed app showing in app list

### ☸ Kubernetes version

EKS : 1.26

### Cloud provider

Azure

### 🌍 Browser

Chrome

### 🧱 Your Environment

QA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4047

**Comment by vikramdevtron** [comment]
closed in this PR https://github.com/devtron-labs/kubelink/pull/70
