### ISSUE TITLE
Bug:  Unable to install Devtron Agent : Rollout Helm Error

### ISSUE THREAD

**Issue by ksingh7** [devtron-labs/devtron#3584]
### 📜 Description

Upon clicking on Install Devton Agent , it shows Rollout Helm error (as shown in the screenshot)

<img width="1579" alt="image" src="https://github.com/devtron-labs/devtron/assets/9701902/b7edb45b-2270-49b5-9a1e-6cf2f8331fd0">

### 👟 Reproduction steps

Not sure if this is my clusters problem or Devtron in General.
If you like to troubleshoot , i am open to jump on a Gmeet call and show you this issue.

### 👍 Expected behavior

Agent should be installed

### 👎 Actual Behavior

Error while installing devtron agent

### ☸ Kubernetes version

v1.26.3

### Cloud provider

<details>
Digital Ocean managed kubernetes
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

Devton version : v0.6.17

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4066

**Comment by pawan-59** [comment]
Hello @ksingh7, it seems like you are trying to install the Devtron agent in the default cluster only, which is not required actually. This Devtron agent is nothing but the rollout controller for the rollout object, which is already in the default cluster as a part of the Devtron stack.

**Comment by abhibhaw** [comment]
@pawan-59 This issue still exist, install agent button is not working
- If agent is not installed, rollout deployment is breaking without proper error messaging.
- Cluster page is unable to detect installation, if rollout controller is installed from chart store.
- I guess same should be the case with external secrets, without external secret operator.

FYI: @deepak-devtron @vikramdevtron @prakarsh-dt @nishant-d @pghildiyal

**Comment by abhibhaw** [comment]
As the devtron agent has been deprecated now, we can safely close this issue.
