### ISSUE TITLE
Bug: ArgoCD icon getting shown on helm applications

### ISSUE THREAD

**Issue by HimanshuJha2000** [devtron-labs/devtron#3589]
### 📜 Description

<img width="775" alt="image" src="https://github.com/devtron-labs/devtron/assets/35391094/34878282-5c22-4604-96c5-8c6a244a49d0">

### 👟 Reproduction steps

1. Deploy any helm application
2. Hover to the app details window

### 👍 Expected behavior

It should show helm icon

### 👎 Actual Behavior

It is showing argoCD icon

### ☸ Kubernetes version

EKS 1.26

### Cloud provider

microK8s 

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4086

**Comment by Darshan018** [comment]
Heyy @prakarsh-dt, are you still working on this issue? otherwise I want to work on this.
