### ISSUE TITLE
Feature: Imagepull secret should be working for External CI

### ISSUE THREAD

**Issue by nitish768** [devtron-labs/devtron#3600]
### 🔖 Feature description

Imagepull secret is not working for External CI but same secret is working for linked and deploy from source code

### 🎤 Pitch

If we want to create external CI from private registry , Imagepull secret should be work in External CI

### ✌️ Solution

When we create external CI imagepull secret should be work without facing the issue imagepull backoff

### 🔄️ Alternative

If we want to create external CI we should provide the imagepull secret in Deployment template.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4142

**Comment by Ashish-devtron** [comment]
It is working fine. We need to create the image pull secret in the namespace where the we have to deploy.
