### ISSUE TITLE
Bug: Getting error during clone an app.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3615]
### 📜 Description

During clone an app which have deployed on environment which has been enforced  for helm only deployment . 

We are getting below error .

<img width="1396" alt="Screenshot 2023-07-10 at 6 44 53 PM" src="https://github.com/devtron-labs/devtron/assets/99399155/9bc33e29-87f2-4964-9983-3b4df111ff36">

### 👟 Reproduction steps

1. Create an Devtron app.
2. Deploy an environment which was not enforced for any specific deployment (helm/gitops)
3. Make that environment for helm only using api .
4. Try to clone that app to create new app.

### 👍 Expected behavior

it should be cloned.

### 👎 Actual Behavior

clone api is through 400 bad request.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4217

**Comment by kartik-579** [comment]
resolved
