### ISSUE TITLE
Enhancement: Add Filter of Not deployed in the App list.

### ISSUE THREAD

**Issue by rish2320** [devtron-labs/devtron#3621]
### 🔖 Feature description

Currently we do not have the option to filter App list through not deployed.

### 🎤 Pitch

A filter of Not Deployed should be provided in App List.

### ✌️ Solution

N/A

### 🔄️ Alternative

N/A

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4274

**Comment by pawan-mehta-dt** [comment]
Fixed by https://github.com/devtron-labs/devtron/pull/3916
