### ISSUE TITLE
Bug: Not able to see multiple choice option for namespace in Kubernetes resource permission.

### ISSUE THREAD

**Issue by Nikhil-gupta1** [devtron-labs/devtron#3658]
### 📜 Description

I want to add multiple namespace in Kubernetes resource permission, but now way to add multiple namespaces in single permission role. Like If I have 50+ namespaces so need to create 50+ permissions.
<img width="794" alt="Screenshot 2023-07-19 at 10 18 39 PM" src="https://github.com/devtron-labs/devtron/assets/35950991/6176568f-8ddc-4ab7-85bc-2c7c265b1253">

Option shoud be like Resource name
<img width="794" alt="Screenshot 2023-07-19 at 10 20 09 PM" src="https://github.com/devtron-labs/devtron/assets/35950991/97e62406-7c3d-4540-beef-f9f5dc1f80ab">

### 👟 Reproduction steps

1. Go to Permission groups
2. Click on ADD Group
3. Select Kubernetes resource
4. Click Add Permission
5. Select Cluster
6. Select Namespace 'it's should be multiple choice options"

### 👍 Expected behavior

Namespace option should be in multiple choice options in Kubernetes resource permission.

### 👎 Actual Behavior

Only single namespace can select in single Kubernetes resource permission.

### ☸ Kubernetes version

EKS 1.23 EKS 1.24+

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

Stage and Production

### ✅ Proposed Solution

Kindly Add multi-choice option for Namespace in Kubernetes resource permission.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4430

**Comment by pawan-59** [comment]
Hello Nikhil, it's not a bug actually it's intentional, as we had some findings around selecting multiple namespaces that were creating confusion for users, although we are working on this to simplify for users.
But if you want to achieve the same you can do so by using API, sharing the API by which you can achieve the same.
```
curl -X POST 'https://staging.devtron.info/orchestrator/user/role/group' \
  -H 'token: <token>' \
  --data-raw '{"id":0,"name":"<name>","description":"","roleFilters":[{"key":0,"cluster":"<cluster-name-added-on-devtron>","namespace":"<comma-separated-namespaces>,"group":"<group>","kind":"<kinds>","resource":"","action":"view","entity":"cluster"}]}' \
  --compressed
  ```
  Example:-
```
curl -X POST 'https://staging.devtron.info/orchestrator/user/role/group' \
  -H 'token: <token>' \
  --data-raw '{"id":0,"name":"dev-qa-pods-admin","description":"","roleFilters":[{"key":0,"cluster":"dev-cluster","namespace":"dev,qa,"group":"k8sempty","kind":"Pod","resource":"","action":"view","entity":"cluster"}]}' \
  --compressed
  ```
  The above API will add a permission group with all Pods admin access in the dev and qa namespaces for the dev cluster.

**Comment by Nikhil-gupta1** [comment]
Thanks for the update
