### ISSUE TITLE
Bug: build and deploy page break

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#3675]
### 📜 Description

just upgraded to latest main and the bulid and deploy page is broken

### 👟 Reproduction steps

1. just upgrade all the microservice to latest main and wait untill old pod is down
2. cmd+shift+r (hard reload the dashboard)
3. then just go to the build and deploy page 

### 👍 Expected behavior

it should be worked

### 👎 Actual Behavior

<img width="1440" alt="Screenshot 2023-07-25 at 11 10 43 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/cef6c707-2385-48fc-8a15-074b71e97ddf">

### ☸ Kubernetes version

1.26

### Cloud provider

<details>

</details>
aks

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4548

**Comment by milindk8** [comment]
Added fix in the above PR
