### ISSUE TITLE
Bug: Nats messages in pending state if multiple deployments are done back to back

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3686]
### 📜 Description

We have a cronjob in which we create all the missing workflows daily and trigger them one by one without any sleep in between.
Those go around 200+ on daily basis

### 👟 Reproduction steps

Try deploying 200 pipelines running on Gitops one by one

### 👍 Expected behavior

Everything should be smooth without any delays

### 👎 Actual Behavior

Nats messages are in pending state and take around 30-40 minutes to consume which delays the deployments of developers

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4568

**Comment by gireesh-devtron** [comment]
configured consumer properties to process nats messages parallelly
