### ISSUE TITLE
Bug: Application admins are not able to delete pods in case of helm apps [Permission issue]

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#3690]
### 📜 Description

It bugs out when you are not superadmin but admin for a particular application and try to delete the pod. It will throw Access Denied error even though user has admin access for that application.

### 👟 Reproduction steps

Give user admin privileges for specific helm app and not superadmin, then deleting the pod of that particular application will replicate the issue.
<img width="980" alt="image" src="https://github.com/devtron-labs/devtron/assets/135199635/aa2c3c72-730f-4ba8-8621-97fc6ba18b9d">

### 👍 Expected behavior

It should have deleted the pod.

### 👎 Actual Behavior

It throws permission denied error.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4594

**Comment by milindk8** [comment]
Fixed this issue in the above PR
