### ISSUE TITLE
Bug: We should not send (default) in Storage class name while we are trying to get manifest for the same

### ISSUE THREAD

**Issue by mayank-devtron** [devtron-labs/devtron#3691]
### 📜 Description

Manifest is not available when we click on storage class containing default in the name

### 👟 Reproduction steps

1.Resource Browser->Config & Storage->Storage Class
2.Try to access manifest with storage class containing default

### 👍 Expected behavior

storage class name should not contain default 

### 👎 Actual Behavior

Manifest is not available for storage class name with default 
<img width="1439" alt="storageclass" src="https://github.com/devtron-labs/devtron/assets/123984701/44d466a0-313f-4e62-86af-5e1239425911">

### ☸ Kubernetes version

Aks1.21

### Cloud provider

<details>
azure
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

Staging

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4596

**Comment by Ash-exp** [comment]
closed in 
OSS PR: https://github.com/devtron-labs/devtron/pull/3962
Dashboard PR: https://github.com/devtron-labs/dashboard/pull/1315
