### ISSUE TITLE
Feature:  Add MongoDbCommunity crd for No-gitops

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#3696]
### 🔖 Feature description

Add MongoDbCommunity crd for No-gitops

### 🎤 Pitch

So while deploying the kind "MongoDBCommunity" through Nogitops it doesn’t show the resource tree in App details page,
to view all the child objects need this feature 

### ✌️ Solution

Map the Crd for no-gitops 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4620

**Comment by prakash100198** [comment]
Reopening the issue as this was reproduced for the particular chart
