### ISSUE TITLE
Bug: git-sensor no resources issue 

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#3697]
### 📜 Description

Git-sensor pod is giving error `**`can't fork() have no resources`**` so when I deleted the git-sensor pod it works fine for 2-3 days and again same issue

### 👟 Reproduction steps

just run the  latest git-sensor for some-days 

### 👍 Expected behavior

it should be work fine .because in grfana their is no oomkilled like situations or memory requested by pod .

### 👎 Actual Behavior

there are creating lot of process which is not deleted in background do that for new process  their is no resources 

### ☸ Kubernetes version

1.23

### Cloud provider

<details>

</details>
aks

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4623

**Comment by subhashish-devtron** [comment]
[cb42dafd9584e51bdd59bd73d01be18f528d2b2a](https://github.com/devtron-labs/git-sensor/pull/59)
