### ISSUE TITLE
Bug: Not able to assign group permission to the user.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3707]
### 📜 Description

We have created a permission group named(**Prod, QA, QA2, UAT Read only accesss**) which  contain comma in its name .

But when we are going to provide this group permission , after refresh it their permission is not contain that group permission.

Payload when adding the permission.
<img width="1351" alt="ss1" src="https://github.com/devtron-labs/devtron/assets/99399155/5f74bff8-e7e0-4b97-ab06-08e1916808fe">

Devtron pod logs.

 {"level":"info","ts":1690551981.6474745,"caller":"user/UserRestHandler.go:210","msg":"request payload, UpdateUser","payload":{"id":407,"email_id":"ajay@devtron.ai","roleFilters":[{"entity":"chart-group","team":"","entityName":"","environment":"","action":"view","approver":false,"accessType":"","cluster":"","namespace":"","group":"","kind":"","resource":""}],"groups":["WMS Prod, QA, QA2, UAT Read only access"],"superAdmin":false}}
 
 {"level":"error","ts":1690551983.66397,"caller":"casbin/casbinService.go:54","msg":"error in adding all policies","err":null,"failedPolicies":[{"Type":"g","Sub":"ajay@devtron.ai","Obj":"group:wms_prod,_qa,_qa2,_uat_read_only_access"}],"stacktrace":"github.com/devtron-labs/devtron/pkg/user/casbin.(*CasbinServiceImpl).AddPolicy\n\t/go/src/github.com/devtron-labs/devtron/pkg/user/casbin/casbinService.go:54\ngithub.com/devtron-labs/devtron/pkg/user/casbin.AddPolicy\n\t/go/src/github.com/devtron-labs/devtron/pkg/user/casbin/Adapter.go:75\ngithub.com/devtron-
 
 
 After saving the permission , when we check the permission it is showing blank .
 
 
<img width="1062" alt="ss2" src="https://github.com/devtron-labs/devtron/assets/99399155/b66894c5-02b6-4498-9712-c64f78730e9a">

### 👟 Reproduction steps

1. Create a group named eg. **dev,staging View only access**
2. add permission group to a user and save permission 
3. try to check permission of user.

### 👍 Expected behavior

Here , it should be block the permission group creation which contain the comma , either permission group which contain comma should be added.

### 👎 Actual Behavior

It is not working as of now.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4662

**Comment by vikramdevtron** [comment]
Fixed in https://github.com/devtron-labs/devtron/pull/4183
