### ISSUE TITLE
Feature:  Configurable the verbosity of kubewatch logs to reduce the logs data size on daily basis

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3717]
### 🔖 Feature description

We have configured the LOG_LEVEL=0 to **kubewatch** mircoservice but after that on the daily basis we are getting 3GB data per day basis on some of our enterprise .

### 🎤 Pitch

We want to decrease the verbosity of kubewatch logs to decrease the logs data  size on daily basis.

### ✌️ Solution

Make Kubewatch logs less verbose by making the logging level configurable. This will enable generating minimal verbosity in the logs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4762

**Comment by kartik-579** [comment]
logging verbosity support is already added (starting with hash - bc72d8e8f8909443dcdb069767863365b787ce03). please upgrade your server version if not working.
