### ISSUE TITLE
Bug: Problem observed with helm install

### ISSUE THREAD

**Issue by surajkrishan** [devtron-labs/devtron#3726]
### 📜 Description

Hi Team, 

I did a fresh devtron install with below cmd:

`helm install devtron devtron/devtron-operator \
--create-namespace --namespace devtroncd \
--set installer.modules={cicd} \
--set argo-cd.enabled=true \
--set components.devtron.service.type=ClusterIP`

### 👟 Reproduction steps

run helm install cmd

observe the extra namespaces created which got created.

### 👍 Expected behavior

if there are no resources under the namespace devtron-ci and devtron-cd why do we still require these namespaces?

<img width="804" alt="image" src="https://github.com/devtron-labs/devtron/assets/32816421/ddee95ed-5733-4eb4-a177-029b0da25006">

### 👎 Actual Behavior

extra namespace gets created with helm install i.e devtron-ci and devtron-cd

### ☸ Kubernetes version

v1.24.10

### Cloud provider

<details>
AKS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

N/A

### ✅ Proposed Solution

helm scripts need to be refactored.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by prakarsh-dt** [comment]
Hi @surajkrishan 
Here is why you have the following namespaces created when you install devtron.

devtron-ci: It is used to run builds when they are triggered from Devtron CI pipelines.
devtron-cd: It is used to run pre-deployment / post-deployment tasks if configured.
devtron-demo: It is added as the default app environment and can be used to deploy microservices for evaluation purpose without adding any target clusters to Devtron.

I hope this answers your query. Please connect with our team on [Discord](https://dicord.devtron.ai ) if you have an further queries around Devtron or it's functionalities.
