### ISSUE TITLE
Bug: Getting error during pre deployment tigger for an app.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3747]
### 📜 Description

During trigger of pre deployment getting below error for an app.

<img width="1421" alt="ss" src="https://github.com/devtron-labs/devtron/assets/99399155/7a0a0458-bebb-4385-a923-3bea32267364">

orchestrator logs

[Aug 10 2023 11:02:44 GMT+0530] orchestrator-delhivery-dcd-68988d4cc-4t4kb: {"level":"error","ts":1691645564.9275162,"caller":"pipeline/WorkflowDagExecutor.go:1609","msg":"err","err":"modifications not found for 8655","stacktrace":"github.com/devtron-labs/devtron/pkg/pipeline.(*WorkflowDagExecutorImpl).ManualCdTrigger\n\t/go/src/github.com/devtron-labs/devtron/pkg/pipeline/WorkflowDagExecutor.go:1609\ngithub.com/devtron-labs/devtron/api/restHandler.PipelineTriggerRestHandlerImpl.OverrideConfig\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/PipelineTriggerRestHandler.go:133\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go:145\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:132\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:71\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
[Aug 10 2023 11:02:44 GMT+0530] orchestrator-delhivery-dcd-68988d4cc-4t4kb: {"level":"error","ts":1691645564.9275749,"caller":"restHandler/PipelineTriggerRestHandler.go:136","msg":"request err, OverrideConfig","err":"modifications not found for 8655","payload":{"pipelineId":9885,"appId":1669,"ciArtifactId":854379,"targetDbVersion":0,"forceTrigger":false,"deploymentWithConfig":"LAST_SAVED_CONFIG","wfrIdForDeploymentWithSpecificTrigger":0,"cdWorkflowType":"PRE","wfrId":0,"cdWorkflowId":0},"stacktrace":"github.com/devtron-labs/devtron/api/restHandler.PipelineTriggerRestHandlerImpl.OverrideConfig\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/PipelineTriggerRestHandler.go:136\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go:145\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:132\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:71\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966"}
[Aug 10 2023 11:02:44 GMT+0530] orchestrator-delhivery-dcd-68988d4cc-4t4kb: {"level":"info","ts":1691645564.9276152,"caller":"common/apiError.go:118","msg":"ERROR RES","TYPE":"API-ERROR","RES":500,"ERROR-MSG":[{"code":"000","internalMessage":"[{modifications not found for 8655}]","userMessage":"modifications not found for 8655"}],"err":null}

### 👟 Reproduction steps

NA

### 👍 Expected behavior

It should be able to trigger pre deployment .

### 👎 Actual Behavior

It is through error during pre deployment.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4919

**Comment by vikramdevtron** [comment]
This issue was resolved for the client as pager item. relevant issue is https://github.com/devtron-labs/devtron/issues/2215 will be fixed soon.
