### ISSUE TITLE
Bug: No able to disable chart repository

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#3748]
### 📜 Description

Not able to disable chart repository showing 500 internal server error

### 👟 Reproduction steps

Disable the chart and click on update button then you get the below error  and it is enabling the chart again

<img width="1415" alt="Screenshot 2023-08-10 at 2 01 22 PM" src="https://github.com/devtron-labs/devtron/assets/128121299/66330681-3f67-486c-be83-c85300dc3ccc">

### 👍 Expected behavior

It should disbale the  chart

### 👎 Actual Behavior

It is enabling the chart again after refreshing 

### ☸ Kubernetes version

Any

### Cloud provider

<details>

</details>
Any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4937

**Comment by kartik-579** [comment]
RCA: In older versions of devtron, chart repo's entry was made in argo cd cm and in new versions (starting from 20/04/23) the entry is made as a separate secret. User accidentally deleted the entry and since it was not found in any of the two places, the code broke.
