### ISSUE TITLE
Feature: Support for handling hibernation and un-hibernation especially when Keda autoscaling is enabled in an application

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3791]
### 🔖 Feature description

Currently, hibernation and un hibernation are not being handled for Devtron apps when **Keda autoscaling** is enabled.

### 🎤 Pitch

In some applications, we have set up Keda autoscaling based on various scalers such as **Kafka, Cron, CloudWatch**, etc. This allows the apps to scale dynamically. However, there are scenarios where we also need to hibernate and unhibernate these apps.

### ✌️ Solution

Certainly, we can disable the Keda scaling configuration by setting it to **"false"** and adjusting the values of minReplicaCount to 0 and maxReplicaCount to 0 on **GitOps** same as have in the case of cpu and memory based HPA.

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5055

**Comment by abhibhaw** [comment]
We can pick https://github.com/devtron-labs/devtron/issues/2089 this along with this story. Minor changes should do the job cc: @Ash-exp
