### ISSUE TITLE
Bug: Getting error while changing branch in linked CI pipeline 

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3797]
### 📜 Description

We are not able to update branch name in linked ci pipeline.

API error 

internalMessage

"[{error while updating linked pipeline}]"
userMessage

"error while updating linked pipeline"

Orchestrator logs

{"level":"error","ts":1692610236.429828,"caller":"pipeline/CiCdPipelineOrchestrator.go:528","msg":"material not fount in patent","gitMaterialId":2177,"stacktrace":"github.com/devtron-labs/devtron/pkg/pipeline.CiCdPipelineOrchestratorImpl.PatchMaterialValue\n\t/go/src/github.com/devtron-labs/devtron/pkg/pipeline/CiCdPipelineOrchestrator.go:528\ngithub.com/devtron-labs/devtron/pkg/pipeline.(*PipelineBuilderImpl).patchCiPipelineUpdateSource\n\t/go/src/github.com/devtron-labs/devtron/pkg/pipeline/PipelineBuilder.go:1719\ngithub.com/devtron-labs/devtron/pkg/pipeline.PipelineBuilderImpl.PatchCiPipeline\n\t/go/src/github.com/devtron-labs/devtron/pkg/pipeline/PipelineBuilder.go:1558\ngithub.com/devtron-labs/devtron/api/restHandler/app.PipelineConfigRestHandlerImpl.PatchCiPipelines\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/app/BuildPipelineRestHandler.go:397\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go:145\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:132\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:71\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2936\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1995"}
[Aug 21 2023 15:00:36 GMT+0530] orchestrator-delhivery-dcd-86d87bcf9d-9wlmp: {"level":"error","ts":1692610236.430176,"caller":"app/BuildPipelineRestHandler.go:399","msg":"service err, PatchCiPipelines","err":"error while updating linked pipeline","PatchCiPipelines":{"ciPipeline":{"isManual":true,"dockerArgs":{"PROFILE":"prod"},"isExternal":false,"parentCiPipeline":0,"parentAppId":0,"appId":4998,"externalCiConfig":{"id":0,"webhookUrl":"","payload":"","accessKey":"","payloadOption":null,"schema":null,"responses":null,"projectId":0,"projectName":"","environmentId":"","environmentName":"","environmentIdentifier":"","appId":0,"appName":"","role":""},"ciMaterial":[{"source":{"type":"SOURCE_TYPE_BRANCH_FIXED","value":"main","regex":""},"gitMaterialId":5844,"id":12614,"gitMaterialName":"","isRegex":false},{"source":{"type":"SOURCE_TYPE_BRANCH_FIXED","value":"j2p-connect-test","regex":""},"gitMaterialId":5845,"id":12615,"gitMaterialName":"","isRegex":false}],"name":"commom-grv-ci","id":8064,"active":true,"linkedCount":788,"scanEnabled":true,"appWorkflowId":7950,"preBuildStage":{"id":3975,"steps":null},"postBuildStage":{"id":3976,"steps":null},"isDockerConfigOverridden":true,"dockerConfigOverride":{"dockerRegistry":"ecr-api","dockerRepository":"kafka-consumers","ciBuildConfig":{"id":1246,"gitMaterialId":5845,"buildContextGitMaterialId":5845,"useRootBuildContext":true,"ciBuildType":"self-dockerfile-build","dockerBuildConfig":{"dockerfileRelativePath":"Dockerfile","dockerfileContent":"","args":{"PROFILE":"dev"},"targetPlatform":"linux/arm64","useBuildx":false},"buildPackConfig":null}},"isOffendingMandatoryPlugin":false,"lastTriggeredEnvId":0},"appId":4998,"action":1,"appWorkflowId":7950},"stacktrace":"github.com/devtron-labs/devtron/api/restHandler/app.PipelineConfigRestHandlerImpl.PatchCiPipelines\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/app/BuildPipelineRestHandler.go:399\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go:145\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:132\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\ngithub.com/devtron-labs/authenticator/middleware.Authorizer.func1.1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:71\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2936\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1995"}
[Aug 21 2023 15:00:36 GMT+0530] orchestrator-delhivery-dcd-86d87bcf9d-9wlmp: {"level":"info","ts":1692610236.4303007,"caller":"common/apiError.go:118","msg":"ERROR RES","TYPE":"API-ERROR","RES":500,"ERROR-MSG":[{"code":"000","internalMessage":"[{error while updating linked pipeline}]","userMessage":"error while updating linked pipeline"}],"err":null}

### 👟 Reproduction steps

NA

### 👍 Expected behavior

It should allow me to update branch name.

### 👎 Actual Behavior

Not able to change branch

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5097

**Comment by kushagra-devtron** [comment]
only happening when git material id in parent is wrong.

**Comment by kushagra-devtron** [comment]
The issue seems to be different , which should be debugged, as to how the wrong git material id got added for parent CI.

**Comment by ajaydevtron** [comment]
Closing this issue will be fix in #3827
