### ISSUE TITLE
Bug:  Error occurs when building image with specified target platform

### ISSUE THREAD

**Issue by chris-lsn** [devtron-labs/devtron#3809]
### 📜 Description

I'm trying to use buildx to build a Docker image. The image building and pushing processes were successful, but I encountered an error at the end. It gave me a warning stating:
`ERROR: open /var/lib/devtron/buildx/.tmp-manifest.json2685967695: no such file or directory`

### 👟 Reproduction steps

When the target platform is set

### 👍 Expected behavior

Build success

### 👎 Actual Behavior
Build failed
![image](https://github.com/devtron-labs/devtron/assets/9113255/4589f5ff-b4b1-40fa-a825-be493ad3841c)

### ☸ Kubernetes version

k3s version v1.27.4+k3s1 (36645e73)

### Cloud provider

<details>
k3s - on-prem
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

CPU Architecture:   aarch64

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by pawan-mehta-dt** [comment]
Can you share if you are using any blobstorage setup with devtron?
