### ISSUE TITLE
Bug: Not able to add helm repository on devtron where default_cluster is no longer reachable

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3813]
### 📜 Description

Not able to add helm repository on devtron where default_cluster is no longer reachable

### 👟 Reproduction steps

1. Use a devtron cluster which has been migrated from another cluster and default_cluster on newer one no longer works
2. Try adding a helm repository

### 👍 Expected behavior

It should get added successfully

### 👎 Actual Behavior

It shows an error cannot add to argocd-cm, attempted 3 times

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

AWS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5149

**Comment by iamayushm** [comment]
after doing RCA of this issue it was found that this is related to default cluster configurations saved in DB. Creating new issue for this and closing this one.

**Comment by iamayushm** [comment]
Main issue :- https://github.com/devtron-labs/devtron/issues/3831
