### ISSUE TITLE
Bug: Showing incorrect manifest on app details page if 2 same named k8s objects are deployed in 2 different namespaces

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#3817]
### 📜 Description

Showing incorrect manifest on app details page if 2 same-named k8s objects are deployed in 2 different namespaces.

### 👟 Reproduction steps

1. Create 2 service accounts with the same name in 2 different namespaces. 
2. Deploy and go to the app details page. 
3. Comparing the manifests for the 2 service accounts, it'll appear both are same, meaning both manifests will belong to the same namespace.

### 👍 Expected behavior

metadata.namespace should have been different for the 2 identical objects.

### 👎 Actual Behavior

metadata.namespace are same. Meaning both manifests are shown for same object.

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5160

**Comment by prakarsh-dt** [comment]
Same as #3425
