### ISSUE TITLE
Cluster creation abrupt from refresh interval 

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#382]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

When filling the data for cluster creation page refresh on some interval, loose the data.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. User goes to Create an application (to save space or whatever)
2. User selects clone option 
3. Configmap in environment override is not cloned

**Expected behavior**
handle refresh interval while cluster update in progress from front end 

**Current behavior** 

When trying to update something, page refresh in some interval on cluster list page, clears form values.

**Comment by prakarsh-dt** [comment]
Resolved
