### ISSUE TITLE
Bug: API Token's permissions are mismatching compared between actual permissions and what we show on UI

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#3864]
### 📜 Description

T

### 👟 Reproduction steps

E

### 👍 Expected behavior

S

### 👎 Actual Behavior

T

### ☸ Kubernetes version

1.23

### Cloud provider

<details>

</details>
AWS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5342

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3861] Bug: API Token&#39;s permissions are mismatching compared between actual permissions and what we show on UI   (70%)
