### ISSUE TITLE
Bug: Displaying running pod count 0 after clicking on old pods.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#3865]
### 📜 Description

On the Devtron app page, when we click on "Old Pods," it shows a running pod count of 0, even though the application has some running pods.

Before clicking on **old pods** section
<img width="1362" alt="ss1" src="https://github.com/devtron-labs/devtron/assets/99399155/7c367a78-084b-431b-b6f4-ab98f8598fcb">

After clicking on old pods 

<img width="1406" alt="ss2" src="https://github.com/devtron-labs/devtron/assets/99399155/0b579aef-8360-4b56-af31-b847dd34f156">

### 👟 Reproduction steps

1. Create a Devtron apps having some replicas running.
2. Click on old pods and see new pods count.

### 👍 Expected behavior

it should show the all running pods counts .

### 👎 Actual Behavior

Right now it is showing 0 running pods.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5344

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3823] Feature: Storing and displaying previous values in pre-build, post-build, pre CD and post CD (40.18%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3823] Feature: Storing and displaying previous values in pre-build, post-build, pre CD and post CD (40.18%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3823] Feature: Storing and displaying previous values in pre-build, post-build, pre CD and post CD (40.18%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3823] Feature: Storing and displaying previous values in pre-build, post-build, pre CD and post CD (40.18%)
