### ISSUE TITLE
Bug: Selected container registry not visible in applications

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3867]
### 📜 Description

For existing applications, selected container registry isn't visible

### 👟 Reproduction steps

NA

### 👍 Expected behavior

Container registry should be visible for all applications

### 👎 Actual Behavior

For existing applications, selected container registry isn't visible

### ☸ Kubernetes version

EKS 1.26

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5366

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3866] Bug: Unable to build image using Shallow Cloning (42.68%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3866] Bug: Unable to build image using Shallow Cloning (42.68%)
