### ISSUE TITLE
Bug: Slowness in Devtron if Devtron is opened in multiple tabs

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#3868]
### 📜 Description

It bugs out when Devtron's dashboard is opened in multiple tabs. In this case, Devtron's Dashboard's response time increases drastically. It becomes extremely slow.
Ques - How do I know that it is an issue with opening multiple tabs of Devtron ?
Ans - Well as soon as I closed all the tabs where Devtron was running, Its responsiveness improved drastically. The slowness just vanishes. Have experienced this multiple times.

Ques - What kind of slowness was observed ?
Ans - Page load becomes extremely slow or try connecting terminal for any application's pod and try running few commands. The lag increases extensively.

### 👟 Reproduction steps

1. Open multiple tabs of devtron. 
2. Open terminal for any application's pod. 
3. Try running any command, you should experience lag greater than 10 / 20 seconds.

NOTE : It might be the case that certain pages / apis are creating this issue because there have been scenarios where 10+ devtron tabs were opened but still slowness was not observed whereas there have been scenarios where I observed slowness even with 5 devtron tabs being opened. 

### 👍 Expected behavior

There should be no slowness in page loading or terminal etc irrespective of how many tabs are opened.

### 👎 Actual Behavior

Slowness is introduced. 

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5368

**Comment by vikramdevtron** [comment]
@tayalrishabh96 Is this still slow.
