### ISSUE TITLE
Bug: no able to deploy on a specific pipeline that migrated to helm from gitops deployment 

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#3871]
### 📜 Description

no able to deploy any new deployment on a specific pipeline that migrated to helm from gitops deployment .
having error-: **pg: multiple rows in result set**

### 👟 Reproduction steps

none

### 👍 Expected behavior

it should be worked fine 

### 👎 Actual Behavior
<img width="1414" alt="Screenshot 2023-09-08 at 11 54 12 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/1926572f-3305-4b48-b593-935886a62184">
<img width="663" alt="Screenshot 2023-09-08 at 11 54 38 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/d81d49ea-c76a-49e1-bda9-b9e7df516c62">

not working 

### ☸ Kubernetes version

1.24

### Cloud provider

<details>

</details>
aws

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5398

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3863] Bug: Gitops replicas sync into the deployment&#x2F;rollout on commits made to same repo + same folder (42.41%)

  - [#3845] Bug: multiple entries for helm charts for every releases in Helm deployment (42.6%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3863] Bug: Gitops replicas sync into the deployment&#x2F;rollout on commits made to same repo + same folder (42.41%)

  - [#3845] Bug: multiple entries for helm charts for every releases in Helm deployment (42.6%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3863] Bug: Gitops replicas sync into the deployment&#x2F;rollout on commits made to same repo + same folder (42.41%)

  - [#3845] Bug: multiple entries for helm charts for every releases in Helm deployment (42.6%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3863] Bug: Gitops replicas sync into the deployment&#x2F;rollout on commits made to same repo + same folder (42.41%)

  - [#3845] Bug: multiple entries for helm charts for every releases in Helm deployment (42.6%)
