### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by ShashwatDadhich** [devtron-labs/devtron#3872]
### 🔖 Feature description

Allow approves of an image to deploy by adding a global variable

### 🎤 Pitch

Currently the approvers of an image are not able to deploy that image

### ✌️ Solution

Allow approves of an image to deploy by adding a global variable both in backend and frontend

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5400

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3855] Feature: Crossplane (55%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3855] Feature: Crossplane (55%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3855] Feature: Crossplane (55%)
