### ISSUE TITLE
Feature: optimize workflow status  fetch api

### ISSUE THREAD

**Issue by gireesh-devtron** [devtron-labs/devtron#3878]
### 🔖 Feature description

optimize workflow status  fetch api

### 🎤 Pitch

optimize workflow status  fetch api

### ✌️ Solution

optimise ci-pipeline status fetch call .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5413

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3830] Feature: Non-gitops to push helm chart to git.  (44.08%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3830] Feature: Non-gitops to push helm chart to git.  (44.08%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#3830] Feature: Non-gitops to push helm chart to git.  (44.08%)
