### ISSUE TITLE
Bug: External helm app configure page not working.

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#3882]
### 📜 Description

getting nil pointer error for some variable named OCI in console.

<img width="1440" alt="Screenshot 2023-09-11 at 3 50 54 PM" src="https://github.com/devtron-labs/devtron/assets/122791251/8f381ec6-2ccd-4173-970d-08712771e3f3">
<img width="1440" alt="Screenshot 2023-09-11 at 3 51 14 PM" src="https://github.com/devtron-labs/devtron/assets/122791251/d6025559-1db0-4c0a-bbef-367989cf80bc">

### 👟 Reproduction steps

add helm app from helm cli
and see the configure page in helm app 

### 👍 Expected behavior

should able to see the configure page

### 👎 Actual Behavior

unable to see the configure page

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 🧱 Your Environment

any

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5436

**Comment by iamayushm** [comment]
https://github.com/devtron-labs/dashboard/pull/1266
