### ISSUE TITLE
Bug: Not able to delete no-gitops cd pipeline 

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#3885]
### 📜 Description

I was trying to create a cd-pipeline and trigger it, but due to some error it failed to deploy Now I'm not able to delete the cd-pipeline also no error on UI.

### 👟 Reproduction steps

1. Create an env for namespace on devtron, and delete the namespace manually using kubectl.
2. Create a new cd-pipeline for the same environment and try to deploy it will fail as the namespace doesn't exist.
3. Now try to delete the cd-pipeline.

### 👍 Expected behavior

Right now when we are triggering cd it marks the deployment_app_created column as true in the pipeline table irrespective of the deployment status due to which not able to delete the cd-pipeline. Also, it should prompt respective messaging on the UI for the same.

### 👎 Actual Behavior

We are not able to delete the cd-pipeline as we mark the pipeline as deployment_app_created as true even after failing the deployment.

### ☸ Kubernetes version

AKS 1.26

### Cloud provider

<details>
Azure
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5451

**Comment by vikramdevtron** [comment]
Fixed in below pr
https://github.com/devtron-labs/devtron/pull/3991
https://github.com/devtron-labs/devtron/pull/4008
