### ISSUE TITLE
Feat: Ability to change branch for all selected applications during bulk build from Application Groups

### ISSUE THREAD

**Issue by Abhinav-26** [devtron-labs/devtron#3887]
### 🔖 Feature description

The ability to select branches at runtime during bulk build from application groups would be great. The given branch should be propagated to all the applications that are selected for build.

### 🎤 Pitch

Developers would be using different branches for testing and building. In cases when you have different applications and projects to builds, it can be hectic to change the branch name of each and every workflow manually. With this feature, it would be really easy for anyone to dynamically change the branch (if the git repo is same) for different applications at once and build it.

### ✌️ Solution

A feature which would allow me to change the branch name from Application Group before I select the applications and build it. Also there should be an option to select applications in which new branch name will be propagated.

### 🔄️ Alternative

Branch change API can be used for time-being

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5471

**Comment by uxarya-d** [comment]
### Cases
1. RBAC
- Branch fixed: Users with `Admin` permission can change
- Branch regex: Users with `Build & Deploy` permission can change
2. Source type
- PR and Tag based build pipelines will not be changed
3. Branch regex
- Provided branch name must match `regex`
4. Multi-Git
//Currently the API expects `materialID` as well to be able to cater to multi-git case

**Comment by prakarsh-dt** [comment]
Duplicate of #3102
