### ISSUE TITLE
Bug: Issues with helm app deployments in NO_GITOPS mode

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#3935]
### 📜 Description

Few issues with helm app deployments in NO_GITOPS mode

### 👟 Reproduction steps

1. Deploy a helm app which gets failed on first deployment itself due to wrong values
2. Deploy a helm app which has some pre-install jobs like kube-prometheus-stack with custom values so that it takes a little longer than expected
3. Deploy a helm app which gets failed on 2nd or 3rd deployment but first deployment was success due to wrong values and then delete this helm app

### 👍 Expected behavior

1. App should be visible in helm apps section even if status is failed
2. Helm app should get deployed successfully if values are correct
3. Deleting this helm release should delete all it's related resources too

### 👎 Actual Behavior

1. App isn't available in helm apps but in cluster helm release is created with failed status this creates a confusion that release was never deployed but next time you fix values, it'll say helm release already exists. You can confirm the release by filtering out cluster and check external helm apps.
2. The timeout is set to 5 minutes but it gets timed out much before than that due to which the app isn't shown in helm apps but exists in external helm apps because helm release was successfully created. It creates the same confusion as first case.
3. The helm release isn't deleted but shown on UI that it's deleted. The release as well as resources still exists in the cluster.

### ☸ Kubernetes version

EKS 1.26

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5619

**Comment by prakash100198** [comment]
closed in the following PRs:- 
https://github.com/devtron-labs/devtron/pull/3856 
https://github.com/devtron-labs/kubelink/pull/74
