### ISSUE TITLE
Doc: Include details on generating deployment template form for custom charts

### ISSUE THREAD

**Issue by dustinblackman** [devtron-labs/devtron#3942]
### 💭 Description

DevTron has fantastic capability where for it's own Deployment Charts, the YAML template is rendered as a form rather than raw yaml. For on-boarding Engineers who are not familiar with Kubernetes, this significantly eases the process.

![image](https://github.com/devtron-labs/devtron/assets/5246169/06572616-5d24-426f-a989-19840d1e7ee7)
![image](https://github.com/devtron-labs/devtron/assets/5246169/bfc01213-ffa4-4190-91b2-773871d06e57)

There is [existing documentation](https://docs.devtron.ai/v/v0.6/global-configurations/custom-charts) that details how to produce custom charts to be used in the deployment template. However what's missing is what files are required in the chart to produce the form such as what's available for a Deployment. 

I've made personal attempts of producing the smallest chart and form based on the Deployment, and while the key piece seems to be the `schema.json`, I'm unable to render the form and instead just get the usual YAML editor.

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "container": {
      "type": "object",
      "description": "defines ports on which application services will be exposed to other services",
      "title": "Container Port",
      "items": {
        "type": "object",
        "properties": {
          "port": {
            "type": "integer",
            "description": "envoy port for the container",
            "title": "Envoy Port"
          }
        }
      }
    }
  }
}
```

![image](https://github.com/devtron-labs/devtron/assets/5246169/ca99061a-ebe3-4d34-a7b6-b3f3f8947146)

### 🛠️ Action Items

Documentation with just examples of existing charts and the correct files to build would be greatly beneficial to improving this part of the experience when creating and managing applications for teams who wish to use custom charts.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5634

**Comment by dustinblackman** [comment]
Ah I misunderstood. This isn't parsing a helm values, but is a [simplified UI](https://github.com/devtron-labs/dashboard/blob/b1eb28fe9b6f5321cc1c696b0f9112189b7aca1a/src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx#L170-L193) with only a few inputs.

**Comment by uxarya-d** [comment]
Hey @dustinblackman, you have a reasonable request. We have also been thinking around these lines.
Reopening this issue as we would like to build this capability in the near future.
Cheers! 👍

**Comment by dustinblackman** [comment]
That's great! I'm experimenting with [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) in a branch to see if it's a viable solution. I had planned to use it to kick off discussions in another issue.

**Comment by uxarya-d** [comment]
Great! We do something similar for helm charts already(refer screenshot), a GUI form is generated based on the schema.json provided with the chart.
<img width="1201" alt="Screenshot 2023-09-24 at 7 34 01 PM" src="https://github.com/devtron-labs/devtron/assets/73632042/fb1beef5-1084-4bb2-8799-a876aac2d0cc">

**Comment by dustinblackman** [comment]
Ah so it does exist! Is it available during app creation?

**Comment by uxarya-d** [comment]
As of now it is only available for deploying helm charts. You can navigate to the chart store from the Primary Navigation and find it for some helm charts like the one in above screenshot. Referring couple of examples below:

https://preview.devtron.ai/dashboard/chart-store/discover/chart/67/deploy-chart
https://preview.devtron.ai/dashboard/chart-store/discover/chart/55/deploy-chart
