### ISSUE TITLE
Bug: Getting Limit as request for resources in Ci-pod 

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#3983]
### 📜 Description

ci pods are getting request as same limit

### 👟 Reproduction steps

run build with different  limit and request

### 👍 Expected behavior

request should be same as request given env

### 👎 Actual Behavior

ci pods are getting request as same limit

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 🧱 Your Environment

any

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5824

**Comment by kartik-579** [comment]
Broke in workflow refactoring, instead of requests limits were being set.
