### ISSUE TITLE
Bug: Post deployment was not working in auto trigger mode

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#3985]
### 📜 Description

Post deployment was not working in auto trigger mode

### 👟 Reproduction steps

Create a CD pipeline which may be auto or manual and then create a post deployment step and keep it auto.

### 👍 Expected behavior

Post deployment should triggered by itself

### 👎 Actual Behavior

Post deployment is not getting triggered automatically.

### ☸ Kubernetes version

1.24

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5847

**Comment by kartik-579** [comment]
RCA: Instead of pipelineId, pipelineOverrideId was being sent which was causing post stage not being fetched. Introduced in https://github.com/devtron-labs/devtron/pull/3911
