### ISSUE TITLE
Bug: Pagination on Nodes View on Devtron Dashboard not working properly

### ISSUE THREAD

**Issue by ggsood** [devtron-labs/devtron#3989]
### 📜 Description

Hi team i am seeing an issue with the devtron dashboard in case of multiple nodes with list of pages, if you try to switch to next page, it takes you to the pop go to resource manager
this is currently observed at nodes list, pods list is working good, the behavior goes into loop

### 👟 Reproduction steps

Have multiple nodes added to the cluster so pagination comes into affect, try browsing the next page, it goes to resource manager and back to the first page

### 👍 Expected behavior

pagination should work normally

### 👎 Actual Behavior

Hi team i am seeing an issue with the devtron dashboard in case of multiple nodes with list of pages, if you try to switch to next page, it takes you to the pop go to resource manager
this is currently observed at nodes list, pods list is working good, the behavior goes into loop

### ☸ Kubernetes version

eks 1.26.2

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

Developer

### ✅ Proposed Solution

Raised it on Discord server with the team

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5853

**Comment by pawan-mehta-dt** [comment]
Fixed by https://github.com/devtron-labs/dashboard/pull/1351
