### ISSUE TITLE
Feature: Ability to set filters on deployment pipelines

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#3993]
### 🔖 Feature description

The current workflow pipeline in Devtron system forces all events to flow through every auto step, which is not ideal for handling complex requirements efficiently. This rigid approach necessitates the creation of multiple pipelines for various use cases, even when these use cases could be logically grouped within a single pipeline.

### 🎤 Pitch

Restructure and enhance the existing pipeline system to improve flexibility, efficiency, and user-friendliness for handling various use cases and complex requirements.

### ✌️ Solution

There is a need to optimize the pipeline architecture to allow event segregation based on filters and accommodate a more flexible and efficient workflow.

A filter can be defined at the Global level applicable. A filter definition would comprise of:

1. Filter conditions (Pass and/or Fail) > Filter condition can be defined by providing a CEL Expression
2. Application & Environment (which will act as deployment pipeline selectors on which the filter would be applied)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by gireesh-devtron** [comment]
closed as this is done in cd filter story
