### ISSUE TITLE
Feature: Capability to bulk hibernate applications via Application Groups

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4003]
### 🔖 Feature description

Capability to hibernate applications currently persists in app details page only. This should be available in application groups as well. 

### 🎤 Pitch

In my use case, there is a scenario where I want to hibernate all of my consumer applications. Even if I use the API, that will require me to generate the CSV having app IDs and env_ids, which sometimes becomes cumbersome and human error-prone. 

### ✌️ Solution

I want this feature to be made available in application groups as well so that one can directly hibernate the applications without worrying about generating CSV and making API calls.

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5874

**Comment by pawan-mehta-dt** [comment]
Completed by #4229
