### ISSUE TITLE
Feature: Capability to bulk restart workloads from application groups

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4004]
### 🔖 Feature description

This feature enhances the capability to restart / redeploy applications in bulk via application groups.

### 🎤 Pitch

In my use case, I am upgrading my application cluster and want to rotate all the pods based on the deployment strategy currently set. There is no option to do this for a large number of applications as the restart workloads option lies in the app details page only. Using API calls is quite hectic because the required parameters are app_id, env_id, rollout_name, and  namespace_name. I can not fetch a list directly from anywhere that has a mapping of rollout names and app names. Hence this feature request.

### ✌️ Solution

I want this feature to be made available in application groups.

### 🔄️ Alternative

There can be an alternative approach by bringing in the capability to deploy currently deployed applications. As of now if you go to Deploy applications in bulk using application groups you can only deploy the latest image and not the currently **Active** one.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5876

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4003] Feature: Capability to bulk hibernate applications via Application Groups (67.31%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4003] Feature: Capability to bulk hibernate applications via Application Groups (67.31%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4003] Feature: Capability to bulk hibernate applications via Application Groups (67.31%)

**Comment by prakarsh-dt** [comment]
Should be worked along with #4003

**Comment by venkytek3036** [comment]
@tayalrishabh96 when can we expect this feature ?
