### ISSUE TITLE
Bug: Resource tree api giving http 502 Bad Gateway

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4017]
### 📜 Description

It bugs out when you try to deploy the application for the first time after migration from gitops to nogitops and it fails during deployment due to any "XYZ" reason. 

### 👟 Reproduction steps

1. Create and deploy an application using gitops.
2. Migrate to helm using devtroncli tool.
3. Make sure that the first deployment after migration fails (create a service that already exists)
4. Try visiting app details page -> here you should see a HTTP 502 Bad gateway.  

### 👍 Expected behavior

It should not have thrown an error HTTP 502 Bad Gateway on app-details page and rather given a msg saying application not deployed. 

### 👎 Actual Behavior

It is throwing an error.

### ☸ Kubernetes version

EKS 1.26

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5972

**Comment by kartik-579** [comment]
RCA: In #3856 we started sending release existence data in resource tree call. It was not handled in Helm type cd pipelines, so whenever release did not exist and we checked resource tree it panics. Also, the resource tree was not called from UI when deployment was not done but there is one edge case when app from gitOps to helm and deployment failed on helm then UI used to call resource tree.
