### ISSUE TITLE
Feature: Cloning all services into new environment.

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#4029]
### 🔖 Feature description

Want to clone all the resources ie Devtron apps and helm apps from one environment to newer or existing environment

### 🎤 Pitch

As we have fixed number of micro services which is installed in one cluster and to replicate the same we have to create the pipeline for new cluster which is quite time taking, and for testing purpose or for some other purposes we replicate the same.
So for time management and fast development we need UI where we can replicate on environment basis

### ✌️ Solution

Need a Button on UI for replicating the resources

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6013

**Comment by tayalrishabh96** [comment]
**Use Case :** 
The specific usecase that i'm looking for is capability to clone `complete workflow` (ci + cd) both from a source `environment`. 
We have workflow get api and workflow post api, we can utilise these to create a script but these API's need appId, workflow Id. Now fetching workflowId for all applications belonging to a certain environment is another headache. 
Hence I have a simple use-case that I should be able clone workflow (CI + CD) just by providing source envId (or envName) and target envId (or envName).
