### ISSUE TITLE
Deployment Status on app Detail 

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#406]
# Description

Earlier in Devtron"s Dashboard After deploying the app users were not able to see deployment status.
Recently `App Status` and `Deployment status`  been segregated  

#Motivation
Easier debugging

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

**Comment by prakarsh-dt** [comment]
Closing as PR is already closed
