### ISSUE TITLE
telemetry for oss

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#407]
# Summary

Track and monitor number of devtron installation.

# Motivation

monitor by graphs and numbers in website so that we can see number of installation one place.
points we want to track

1. installation
2. uninstall, dead
3. usages(no of apps, deployments-prod, deployment-non-prod,  user)  
4. devtron version 
5.  k8s version
6. ip
7. total no of cluster+ env

# Proposal

Webhook from devtron application and a new micro-service will be implemented for processes and dump data.

# Implementation Doc
https://docs.google.com/document/d/1rifNYa8C-8iN3kMQVKonoHyfKIlgzxQUO-MZbe3sU1I/edit

https://docs.google.com/document/d/10K1INC-bRi8bULVURtbSGWNmyXgaY4uT6XQKPv0lx38/edit

**Comment by pghildiyal** [comment]
There should not be an PII in the data.
We need to capture frequency of use also.

**Comment by vikramdevtron** [comment]
> There should not be an PII in the data.
 - for unique installation we are using devtron generated id inside configmap.
 -
> We need to capture frequency of use also.
 - currently focusing on number of installation and active users. for frequency we can later introduced new event type publish 
 in a same manner.
