### ISSUE TITLE
Bug: System variables are not reflecting in pre/post build 

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#4090]
### 📜 Description

Not able to print any system variables in post-build 

### 👟 Reproduction steps

1. Create a cluster and sync it with the latest main code.
2. Configure a post-build task.
3. Introduce an input variable named DOCKER_IMAGE, which is a SYSTEM VARIABLE.
4. Observe the outcome when attempting to print the DOCKER_IMAGE variable.

<img width="619" alt="Screenshot 2023-10-13 at 11 20 32 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/412bc381-22b4-46b9-959d-9c171e7b7d06">
<img width="619" alt="Screenshot 2023-10-13 at 11 22 22 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/10bb0a9b-f372-44a4-99e6-b3b6a79c7f65">

### 👍 Expected behavior

The post-build process should correctly display the real Docker image that has been generated.

### 👎 Actual Behavior

Currently, the post-build process treats system variables as strings and prints them accordingly.

### ☸ Kubernetes version

1.26

### Cloud provider

<details>
aks
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6188

**Comment by ritvikmahajan17** [comment]
this issue is fixed in this pr : https://github.com/devtron-labs/dashboard/pull/1382
