### ISSUE TITLE
Bug: Frontend loader stops loading and throws No results found screen

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4109]
### 📜 Description

It bugs out generally in subsequent request made to events page or pods page in resource browser section. The frontend displays the screen No result found after 2-3 seconds even if backend request is still processing.

### 👟 Reproduction steps

1. It can only be reproduced if you have enough resources in the cluster such that the request takes at least 5-6 seconds. 
2. Now go pods page in resource browser section. The first request will succeed. 
3. Keeping inspect element with network tab ready, try refreshing the page and you will see no results found after 2-3 seconds. NOTE : in inspect element you'll notice the backend request was still processing.

### 👍 Expected behavior

It should have waited for the backend request to process before showing `No Results Found.`

### 👎 Actual Behavior

It throws `No Results Found` screen even when backend request is processing.

### ☸ Kubernetes version

EKS 1.26

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6251

**Comment by mukultayal135** [comment]
Resolved with PR #1387
