### ISSUE TITLE
Bug: The CI-trigger based on Bitbucket tags is not functioning as expected when specifying a Git repository with a username included

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#4115]
### 📜 Description

When the Git repository URL is configured as "https://badal773@bitbucket.org/test773/test.git" in the context of a fixed branch, it functions as expected. However, when applied to tag-based operations, the cURL request returns a 200 status code but fails to reflect the changes in Devtron.

However, by adjusting the URL to "https://bitbucket.org/test773/test.git," resolves the issue specifically for tag-based operations.

In summary, the Git repository URL "https://bitbucket.org/test773/test.git" works effectively for tag-based processes, while "https://badal773@bitbucket.org/test773/test.git" functions correctly for branch-related operations.

### 👟 Reproduction steps

1. Begin by creating a repository in Bitbucket and then set up an application in Devtron.
2.  Configure your Git account as Bitbucket and ensure you save the URL with the username.
3. Implement a tag-based pipeline in your application.
4. Proceed to set up a webhook in Bitbucket and ensure that you enable history tracking for this webhook.
5. Create a new tag in your Bitbucket repository.
6.  After creating the tag, check the webhook history in Bitbucket; it should ideally display a response status of 200.
7. However, despite the webhook history showing a successful response, if you find that the pipeline is not triggered in Devtron.

### 👍 Expected behavior

The expected behavior is to function correctly, displaying tag in the build and deploy page .

### 👎 Actual Behavior

However, this is currently not performing as expected.

### ☸ Kubernetes version

1.26

### Cloud provider

<details>
azure
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6294

**Comment by prakash100198** [comment]
RCA:- the issue was that in global git account 73strings were using user email id instead of username, hence the git checkout operation was not able to  execute, they were under the impression that email will work same as username hence they gave user email id, once we changed email to username it started workign fine
