### ISSUE TITLE
Bug: App details page showing incorrect pod's details

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4119]
### 📜 Description

It bugs out while trying to see the resources in app details and then switching env and application. The app details page will keep switching resources between the ones previously accessed.
As seen in screenshot below : 
![image](https://github.com/devtron-labs/devtron/assets/135199635/e4f0a9b3-af39-4347-b6a3-8402203d8f47)

### 👟 Reproduction steps

1. Open app details page for app a1 in environment e1
2. Switch to app details page for app a2 in environment e2
3. Now keep looking at the pod name, sometimes it shows for a1 sometimes for a2. It keeps switching.

### 👍 Expected behavior

It should not switch the pod details to the one previously accessed.

### 👎 Actual Behavior

Pod details are switching between the ones previously accessed. 

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6300

**Comment by vikramdevtron** [comment]
Closed in  https://github.com/devtron-labs/dashboard/pull/1392
