### ISSUE TITLE
Bug: Kubelink is getting restarting due to panic error

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#4135]
### 📜 Description

We are not able to deploy the application due to Kubelink is in not ready state and getting restarted several times. 
Getting panic error in kubelink containers

### 👟 Reproduction steps

Deploy the kubelink with latest image. 

### 👍 Expected behavior

It shouldn't be restarted and should run in stable mode. 

### 👎 Actual Behavior

Restarting and failing 

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
GCP
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6341

**Comment by Ashish-devtron** [comment]
Fixed in:- https://github.com/devtron-labs/kubelink/pull/87
