### ISSUE TITLE
Bug: image scan throws panic when scan is disabled and there are no entries in scan_info table

### ISSUE THREAD

**Issue by subhashish-devtron** [devtron-labs/devtron#4151]
### 📜 Description

 image scan throws panic when scan is disabled and there are no entries in scan_info table

### 👟 Reproduction steps

 image scan throws panic when scan is disabled and there are no entries in scan_info table

### 👍 Expected behavior

should return from the flow

### 👎 Actual Behavior

goes to update and panics

### ☸ Kubernetes version

NA

### Cloud provider

NA

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6386

**Comment by ShashwatDadhich** [comment]
Why it happened - It happened because of not proper understanding of code in this particular area.
What can we do to let this not happen in future - By analysing the code properly before jumping into development 
When it got broke - while fixing another bug in same area
