### ISSUE TITLE
Bug: Git-Sensor multiple processes are creating over the time

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4191]
### 📜 Description

multiple processes are created in git-sensor pod, which lead to more CPU and memory utilisation.

Pod didn't get OOM kill or CPU throttled.
grafana memory utilisation
<img width="1378" alt="Screenshot 2023-11-01 at 2 18 51 PM" src="https://github.com/devtron-labs/devtron/assets/122791251/b25c2b82-807e-43e7-8367-e1b1771f8b4d">

In that case latest commit are not fetched.

### 👟 Reproduction steps

1. cluster with multiple ci pipelines
2. over long period when pod didn't restarts  we can see the processes by running `ps awk|wc -l`.

### 👍 Expected behavior

optimal number of processes should be present.

### 👎 Actual Behavior

zombie process are getting created.

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 🧱 Your Environment

any

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6573

**Comment by vikramdevtron** [comment]
@jatin-jangir-0220 please confirm if still exists.

**Comment by abhibhaw** [comment]
Please reopen if still exist @jatin-jangir-0220
