### ISSUE TITLE
Bug: Unable to fetch last saved or last deployed config during config review before deployment

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4199]
### 📜 Description

It is bugging for few applications that config review is not visible for last saved config and last deploy config both. 
None of the API calls is failing. The API call responsible for the same is bringing null data from backend. 

### 👟 Reproduction steps

Don't know how to replicate.

### 👍 Expected behavior

It should have fetched the data from backend and config diff should have been visible.

### 👎 Actual Behavior

It shoes as attached in pic below : 
<img width="500" alt="image" src="https://github.com/devtron-labs/devtron/assets/135199635/24fb2e80-c92e-4472-9c29-0c2fcf3e3dc7">

### ☸ Kubernetes version

Na

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6633

**Comment by prakash100198** [comment]
RCA:- This was a rare incident after triggering deployment, for some time there might have been downtime which was evident from the fact that some tables had entry of that trigger but helm release command did not show that release also some table did not have entries related to that trigger, in which last saved config were saved, so it was unable to fetch from db, triggered the deployment once again, everything started functioning normal
