### ISSUE TITLE
Bug: ReplicaCount remains unchanged after disabling the Horizontal Pod Autoscaler (HPA) in non-GitOps

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#4245]
### 📜 Description

If you've deployed a Devtron app using Helm and successfully enabled Horizontal Pod Autoscaling (HPA), let's consider the current replica count set to 5 or the maximum allowed replicas,

disabling HPA and deploying it again will result in the replica count remaining unchanged.

### 👟 Reproduction steps

None

### 👍 Expected behavior

It should be changed

### 👎 Actual Behavior

It's not changing the replica-count

### ☸ Kubernetes version

1.24

### Cloud provider

<details>
aws
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6804

**Comment by pawan-59** [comment]
Update: this behavior is only with the Rollout object, for the Deployment object it's not the issue

**Comment by Ash-exp** [comment]
Helm has some limitations for CRDs https://github.com/helm/helm/issues/9937 . Helm doesn't three way patch the values for CRDs, it uses two way patch.
