### ISSUE TITLE
Bug: Retrying failed deployments in application groups automatically closes the bulk deploy response modal

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4287]
### 📜 Description

It bugs out when you deploy a number of applications via application groups. A new modal pops up showing the status of applications whose deployment was triggered. On clicking retry failed the modal closes automatically which should not happen.

### 👟 Reproduction steps

1. In my case I deployed 140+ applications simultaneously via application groups.
2. On triggering bulk deployment a few get failed.
3. On clicking `retry failed` the bulk deploy modal automatically closes. This should not be the correct behaviour.
<img width="1163" alt="image" src="https://github.com/devtron-labs/devtron/assets/135199635/c2f3499f-b296-47b6-9c33-e8db0e0dfadb">

### 👍 Expected behavior

Expected behaviour would have been modal not closing automatically 

### 👎 Actual Behavior

modal closes automatically.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7003

**Comment by vikramdevtron** [comment]
@vivek-devtron this should works fine after batching
