### ISSUE TITLE
Bug:  Getting Time out If there is a large number of pods in the resource browser

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#4322]
### 📜 Description

In our Kubernetes cluster, there are over 1,000 pods within a single namespace. When attempting to access pods through the resource browser, the pod list **API times out.**

<img width="1426" alt="ss" src="https://github.com/devtron-labs/devtron/assets/99399155/88e41de4-88bc-4d31-8d6e-fdd7d24d1e66">

### 👟 Reproduction steps

1. Create over 1,000 pods in a single namespace.
2. Attempt to access any pod using the resource browser.

### 👍 Expected behavior

1. It should able to access pod.

### 👎 Actual Behavior

Getting time out in resource browser page

### ☸ Kubernetes version

1.34

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7114

**Comment by vikramdevtron** [comment]
Fixed after informer caching
