### ISSUE TITLE
Feature: Installation: nodeSelector

### ISSUE THREAD

**Issue by dzirg44** [devtron-labs/devtron#435]
# Summary

It would be great if we had `nodeSelector` implementation for devtron installation.

# Motivation

sometimes we want to use spot instances for a cluster and having this feature can help to make builds\deployments more predictable 

# Proposal

At least in the helm chart, it would be nice to have an opportunity to set up it for all components, and maybe even in the future - for each component. 
If  I missed something in the documentation, let me know.

AB#10249

**Comment by prakarsh-dt** [comment]
Linked to #1763

**Comment by prakarsh-dt** [comment]
Resolved by https://github.com/devtron-labs/devtron/pull/5453
