### ISSUE TITLE
Bug: Inconsistent behaviour on deploying application from application group v/s devtron cli tool after changing deploymentType 

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4355]
### 📜 Description

After changing deploymentType from argoCD to Helm or vice-versa and then triggering deployment from application groups breaks app details page, Build and Deploy page and workflow editor page for that particular application. 

### 👟 Reproduction steps

1. Change the Application's Deploy Type from helm to argocd or vice-versa using devtctl tool.
2. Deploy the same application using application groups.
3. Go to the app details page, Build and Deploy page, or workflow editor page. All of them would be broken.

_App Details Page_
<img width="807" alt="image" src="https://github.com/devtron-labs/devtron/assets/135199635/360dccd3-c1b8-4172-b2a6-c9a561cfdf49">

_Workflow Editor Page_
<img width="863" alt="image" src="https://github.com/devtron-labs/devtron/assets/135199635/2726b9db-d61c-482d-8fa8-a7342c00e3bd">

### 👍 Expected behavior

Either we should not be able to deploy using Application groups after changing Deployment Type or we should handle this scenario. 

### 👎 Actual Behavior

Deployment from app groups is breaking app details and few other pages after changing deployment type. 

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

Deletion request field needs to be handled in pipelines table.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7223

**Comment by ShashwatDadhich** [comment]
Fixed
