### ISSUE TITLE
Bug: Not able to deploy one application

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#4376]
### 📜 Description

Created one devtron application using the clone option in devtron, and then the application faced the following issue with the following error while deploying the application.
```
closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR
```

### 👟 Reproduction steps

1. Create a devtron application using the clone option.
2. Deploy the application

### 👍 Expected behavior

For the very 1st deployment of this application got an `error reading from server: EOF` and after redeploying the application I got the below error 
```
closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR
```

### 👎 Actual Behavior

The application not getting deployed.

### ☸ Kubernetes version

EKS

### Cloud provider

<details>
1.26
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7359

**Comment by gireesh-devtron** [comment]
this issue occurred because maximum helm release version history was set to infinite. this issue can be resolved by limiting the release versions using ``REVISION_HISTORY_LIMIT_DEVTRON_APP`` flag.
