### ISSUE TITLE
Feature: Support overriding DOCKER_IMAGE_TAG with TAG@DIGEST for deployments

### ISSUE THREAD

**Issue by Kaushiks4** [devtron-labs/devtron#4416]
### 🔖 Feature description

Allow the DOCKER_IMAGE_TAG value to be overridden with a digest in the format TAG@DIGEST instead of just the tag. This would provide greater flexibility when deploying to clusters with differing image requirements.

### 🎤 Pitch / Usecases

- Deploy to restricted clusters that require signed container images using content trust. Specifying the digest would integrate with immutable image requirements. 

- Rollback deployments by pinning to a particular image digest instead of moving tags.

- Enforce exact version deployments across environments by using the digest of pre-validated images.

### 🔄️ Alternative

No alternative at the moment

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7505

**Comment by prakarsh-dt** [comment]
@Kaushiks4 Thanks for raising this feature request. We will be picking this up in our upcoming sprint.
