### ISSUE TITLE
Feature: Reload Git repositories connected to a git account if git account is updated

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#4463]
### 🔖 Feature description

Reload Git repositories connected to a git account if git account is updated

### 🎤 Pitch / Usecases

We may mess with credentials that we have added to Git account and all of the respositories related to that account become inactive after few errors. Once we update the credentials, we have to manually update all the git materials associated with that git account.

### 🔄️ Alternative

we can manually update all the git materials associated with that git account

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7681

**Comment by abhibhaw** [comment]
Fixed with attached PR
