### ISSUE TITLE
Bug: Handling batch call responses in app grouping, success and failed scenarios on page refresh

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4466]
### 🔖 Feature description

This is a feature request to handle failed deployment triggers that happens in application groups. The deployment trigger fails if we deploy more than a certain number of applications via application groups. Although we give an option to retry failed but than there is another problem that the modal vanishes if page is refreshed. We should be able to handle this scenario as well that I should be able to retry failed even if the page is refreshed. 

### 🎤 Pitch / Usecases

There are multiple scenarios where I use bulk deployment of all applications using application groups. Now we successfully trigger deployment for few apps only and fails for rest. Then I keep on doing retry failed until deployment is successfully triggered for all apps.
This scenario is specifically tested for gitOps.

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7717

**Comment by vikramdevtron** [comment]
https://github.com/devtron-labs/devtron/issues/4731
