### ISSUE TITLE
Create a Permission group and delete permission group(with or without search) -> Incorrect group is removed from list

### ISSUE THREAD

**Issue by mayank-devtron** [devtron-labs/devtron#4483]
### 📜 Description

Create a Permission group ->save permission group ->delete permission group(with or without search) -> Incorrect group is removed from listBug(works fine after refresh)

### 👟 Reproduction steps

Create a Permission group
->save permission group 
->delete permission group(with or without search) 
->delete modal freeze
-> Incorrect group is removed from listBug:

### 👍 Expected behavior

delete modal should not freeze and correct group should be deleted

### 👎 Actual Behavior

https://github.com/devtron-labs/devtron/assets/123984701/87341245-cbee-40ae-8515-f45f33a81502

### ☸ Kubernetes version

aks

### Cloud provider

<details>
azure
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

qa

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7769

**Comment by abhibhaw** [comment]
Fixed with Active / Inactive story
