### ISSUE TITLE
Bug: Getting "Deployment failed: context canceled" while triggering deployment

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4502]
### 📜 Description

getting context canceled while deploying, but the release was created.
<img width="1501" alt="content" src="https://github.com/devtron-labs/devtron/assets/122791251/3e6c8bcb-4a65-4329-b526-ae973c15b668">
 

### Criticality

P2 - Medium

### Impact on Enterprise

1. user is unsure about release 
2. user experience 

### 👟 Steps to replicate the Issue

.

### 👍 Expected behavior

if release was success or failed it must show the result properly.

### 👎 Actual Behavior

context deadline

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7860

**Comment by vikramdevtron** [comment]
may be fixed in gitops async @Ash-exp. please verify and close

**Comment by Ash-exp** [comment]
similar to https://github.com/devtron-labs/devtron/issues/4943
