### ISSUE TITLE
Chore: Remove unused jira integration and unused tables related to db_migration_config 

### ISSUE THREAD

**Issue by Ash-exp** [devtron-labs/devtron#4532]
### 🔖 Feature description

1. Removed/ clean up unused db_tables: db_migration_config, db_config
2. Remove unused jira integration and related code

### 🎤 Pitch / Usecases

Clean up and remove unused integrations in the code base

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7981

**Comment by abhibhaw** [comment]
Fixed by the attached PR
