### ISSUE TITLE
Feature: Add support for linting, pre-commit hook and CI workflow

### ISSUE THREAD

**Issue by eshankvaish** [devtron-labs/devtron#4534]
### 🔖 Feature description

- Add the ESLint configuration for FE repositories along with prettier
- Add support for husky pre-commit hook
- Add support for lint staged for linting only the staged files
- Add the CI workflow to check linting on each PR

### 🎤 Pitch / Usecases

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7996

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4521] Feature: Add support for uploading the frontend source maps to Sentry (64.79%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4521] Feature: Add support for uploading the frontend source maps to Sentry (64.79%)

**Comment by eshankvaish** [comment]
> Potential duplicates:
> 
> * [[Feature: Add support for uploading the frontend source maps to Sentry #4521](https://github.com/devtron-labs/devtron/issues/4521)] Feature: Add support for uploading the frontend source maps to Sentry (64.79%)

Both the issues are unrelated.
