### ISSUE TITLE
Bug: Application group not working

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#4601]
### 📜 Description

The application group is not working after upgrading the Devtron stack from the 0.6.22 version to 0.6.26. Previously it was working fine.

### Criticality

None

### Impact on Enterprise

OSS

### 👟 Steps to replicate the Issue

1. Upgrade the Devtron stack from 0.6.22 to 0.6.26.

### 👍 Expected behavior

It should work fine after upgrading the Devtron stack

### 👎 Actual Behavior

Showing application count 0 for each environment even applications are deployed on environments.

### ☸ Kubernetes version

1.27

### Cloud provider

<details>
AWS EKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8247

**Comment by abhibhaw** [comment]
@pawan-59 Is this issue still there or resolved?

**Comment by pawan-59** [comment]
yes @abhibhaw this is resolved now. Closing the issue.
