### ISSUE TITLE
Checklist status bug

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#465]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Status is not uploading after  Configuration

<img width="1079" alt="Screenshot 2021-05-24 at 5 43 37 PM" src="https://user-images.githubusercontent.com/61836271/119346232-946adb00-bcb7-11eb-91fa-0fcd442afd3a.png">

**To Reproduce**

1.  When a user initially enters to `Global Configuration` section, a checklist appears
2.  In case the User has configured `Docker registries`
3.  Status is not updated (unchecked) in app list
<img width="229" alt="Screenshot 2021-05-24 at 5 51 23 PM" src="https://user-images.githubusercontent.com/61836271/119347169-c466ae00-bcb8-11eb-8f9b-3cf10f528d17.png">

**Expected behavior**

After Configuration, status needs to be updated and thus should show check.

**Current behavior** 

Unchecked before name in the checklist.

**Comment by prakarsh-dt** [comment]
@shivani170 Is this done? Can you link the PR?
