### ISSUE TITLE
Bug: [DASHBOARD] Escaping missing in resource browser search

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#4660]
### 📜 Description

Escaping missing in resource browser search. Search for anything which contains special characters like "/" in search.

### 👟 Reproduction steps

1. Go to Resource Browser > Jobs
2. Search for anything in duration or namespace column like 131d or devtron-ci
3. Try to search anything in Completions column like 0/1 or 1/1

### 👍 Expected behavior

It should give me results for job completions with 0/1 or 1/1

### 👎 Actual Behavior

It doesn't show any results for that

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8434

**Comment by Elessar1802** [comment]
This is not an issue of escaping the / character. Instead the search simply doesn't work on columns other than the few specified internally. The completions column is unfortunately one of those columns that are overlooked.

**Comment by abhibhaw** [comment]
Already fixed, tested with latest devtron release
