### ISSUE TITLE
Doc: Save selection as filter option not described in Application groups

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#4664]
### 💭 Description

- [ ] `Save selection as filter` option not described in Application groups.
- [ ] `Saved Filters` option not described in Application groups
<img width="1353" alt="Screenshot 2024-02-13 at 1 25 10 PM" src="https://github.com/devtron-labs/devtron/assets/71125043/42a77b54-59a8-4695-9afc-ac01f35b808f">

Documentation page: https://docs.devtron.ai/usage/application-groups#accessing-application-groups

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8481

**Comment by ashokdevtron** [comment]
@prakarsh-dt, we already have a sub-section for that in the doc. Please check the below snapshot.
<img width="1442" alt="image" src="https://github.com/devtron-labs/devtron/assets/141001279/a27d8760-60ee-4de4-abaf-c8bb25d41c4d">
