### ISSUE TITLE
Bug: deployment status is in progressing state 

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4676]
### 📜 Description

- in devtron app, the deployment status is always in progressing state and the app status is healthy and every thing got updated successfully.
- when i manually sync on argocd the deployment status got updated at same time

### Criticality

P2 - Medium

### Impact on Enterprise

1. cd

### 👟 Steps to replicate the Issue

1. deploy in devtron application (gitops)
2. wait for app status to get heathy
3. deployment status will not get success 

### 👍 Expected behavior

deployment status should get updated

### 👎 Actual Behavior

deployment status is not get updated 

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8531

**Comment by vikramdevtron** [comment]
fixed in https://github.com/devtron-labs/enterprise-release/pull/318
