### ISSUE TITLE
Bug: App list API for older dashboard is still calling v1 after removal

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#4682]
### 📜 Description

App list API for older dashboard is still calling v1 after removal

### 👟 Reproduction steps

Upgrade to latest dashboard from version where v1 was available to version where v2 is removed

### 👍 Expected behavior

The upgradation should be smooth

### 👎 Actual Behavior

Upgrade breaks pages until hard reload or service worker reload

### ☸ Kubernetes version

EKS 1.29

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8540

**Comment by vikramdevtron** [comment]
Marking it pager issue
