### ISSUE TITLE
devtroncd installation - On Premises - Functionality is not working as expected

### ISSUE THREAD

**Issue by zohebshaik41** [devtron-labs/devtron#4699]
Hi Team,

I've deployed devtroncd on-premises(VMWare Infra). All the pods are up/running and even I am able to login and access web UI. However, I am not able to create application as the option itself is not available in dashboard.

Did someone tested devtroncd on-premises? In Azure AKS I've tested the same helm chart and it worked like a charm.

I wanted to use open source devtroncd on-premises.

Secondly, is there any specific documentation available for on-premises setup?

Appreciate your feedback, if someone from Product team can look into it.

Screenshot FYR.

![image](https://github.com/devtron-labs/devtron/assets/152380397/e1a98c54-4a78-445b-9a73-53f83cfc3b73)
 

AB#8610

**Comment by pawan-mehta-dt** [comment]
Can you try this and see if you are able to see apps on dashboard now?
`kubectl delete po -n devtroncd -l app=kubelink`

@zohebshaik41

**Comment by zohebshaik41** [comment]
@pawan-mehta-dt Hi Pawan, no luck. Still it's the same.

I see the kubelink pod is up again and the logs are as follows:

kubectl logs kubelink-84898786d7-lcb4g -n devtroncd
{"level":"info","ts":1708497644.611673,"caller":"sql/connection.go:65","msg":"connected with db","db":{"Addr":"postgresql-postgresql.devtroncd","Port":"5432","User":"postgres","Password":"********","Database":"orchestrator","ApplicationName":"orchestrator","LogQuery":true,"LogAllQuery":false,"ExportPromMetrics":false,"QueryDurationThreshold":5000}}
{"level":"info","ts":1708497644.6764545,"caller":"kubelink/App.go:83","msg":"starting server on ","port":50051}
{"level":"info","ts":1708497644.681169,"caller":"k8sInformer/K8sInformer.go:363","msg":"starting informer for cluster - cluster-id 2cluster-name kubernetes"}
{"level":"info","ts":1708497644.68266,"caller":"k8sInformer/K8sInformer.go:469","msg":"informer started for cluster: cluster_id2cluster_namekubernetes"}
{"level":"debug","ts":1708497644.682702,"caller":"k8s/K8sUtil.go:694","msg":"getting k8s rest config"}
{"level":"debug","ts":1708497644.68331,"caller":"k8sInformer/K8sInformer.go:222","msg":"Starting informer, reading new cluster request for default cluster"}
{"level":"info","ts":1708497644.6866722,"caller":"k8sInformer/K8sInformer.go:363","msg":"starting informer for cluster - cluster-id 1cluster-name default_cluster"}
{"level":"debug","ts":1708497644.6867135,"caller":"k8s/K8sUtil.go:694","msg":"getting k8s rest config"}
{"level":"info","ts":1708497644.6873715,"caller":"k8sInformer/K8sInformer.go:469","msg":"informer started for cluster: cluster_id1cluster_namedefault_cluster"}
{"level":"debug","ts":1708497644.7011476,"caller":"k8sInformer/K8sInformer.go:232","msg":"Event received in cluster secret Add informertime2024-02-21 06:40:44.701093392 +0000 UTC m=+0.370810503"}
{"level":"debug","ts":1708497644.7019649,"caller":"k8sInformer/K8sInformer.go:359","msg":"informer for kubernetes already exist"}
{"level":"debug","ts":1708497644.7020063,"caller":"k8sInformer/K8sInformer.go:245","msg":"error in adding informer for clusterid2errINFORMER_ALREADY_EXIST"}
{"level":"debug","ts":1708497644.8012686,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.801229944 +0000 UTC m=+0.470947046"}
{"level":"debug","ts":1708497644.8044393,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.80436133 +0000 UTC m=+0.474078505"}
{"level":"debug","ts":1708497644.8559206,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.8559024 +0000 UTC m=+0.525619514"}
{"level":"debug","ts":1708497644.8585033,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.858495151 +0000 UTC m=+0.528212267"}
{"level":"debug","ts":1708497644.8591475,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.859143861 +0000 UTC m=+0.528860972"}
{"level":"debug","ts":1708497644.8635514,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.863544971 +0000 UTC m=+0.533262081"}
{"level":"debug","ts":1708497644.8664443,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.866435283 +0000 UTC m=+0.536152393"}
{"level":"debug","ts":1708497644.8673265,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.867321064 +0000 UTC m=+0.537038175"}
{"level":"debug","ts":1708497644.8682575,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.868252334 +0000 UTC m=+0.537969444"}
{"level":"debug","ts":1708497644.8688781,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.868874146 +0000 UTC m=+0.538591256"}
{"level":"debug","ts":1708497644.874015,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.874004868 +0000 UTC m=+0.543721978"}
{"level":"debug","ts":1708497644.8748806,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.874875729 +0000 UTC m=+0.544592840"}
{"level":"debug","ts":1708497644.8773894,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.877384218 +0000 UTC m=+0.547101329"}
{"level":"debug","ts":1708497644.8789957,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.878989854 +0000 UTC m=+0.548706965"}
{"level":"debug","ts":1708497644.8820903,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.882083521 +0000 UTC m=+0.551800632"}
{"level":"debug","ts":1708497644.8844774,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.884472753 +0000 UTC m=+0.554189864"}
{"level":"debug","ts":1708497644.8857913,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.885784468 +0000 UTC m=+0.555501586"}
{"level":"debug","ts":1708497644.8886938,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.888688329 +0000 UTC m=+0.558405440"}
{"level":"debug","ts":1708497644.8928845,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.892878389 +0000 UTC m=+0.562595500"}
{"level":"debug","ts":1708497644.8953798,"caller":"k8sInformer/K8sInformer.go:397","msg":"Event received in Helm secret add informertime2024-02-21 06:40:44.895373845 +0000 UTC m=+0.565090955"}
{"level":"info","ts":1708497696.6679904,"caller":"service/HelmAppServiceWrapper.go:60","msg":"List Application Request"}
{"level":"debug","ts":1708497696.6680875,"caller":"service/HelmAppService.go:173","msg":"Fetching application list ","clusterId":2,"clusterName":"kubernetes"}
{"level":"info","ts":1708497696.6688213,"caller":"service/HelmAppService.go:179","msg":"Fetching helm release using Cache"}
{"level":"info","ts":1708497696.6700618,"caller":"service/HelmAppServiceWrapper.go:75","msg":"List Application Request served"}

**Comment by pawan-mehta-dt** [comment]
Can you check in Stack Manager is CI/CD module is installed?
Also, can you confirm if the cluster is Air-Gapped? @zohebshaik41

**Comment by zohebshaik41** [comment]
From cluster, I am able to pull images and we have a proxy. It's not fully air-gapped, but if we need to access any specific URLs then we need to see how it can be allowed. As we are not using network policies as well at kubernetes level.

![image](https://github.com/devtron-labs/devtron/assets/152380397/106601f6-777a-43b5-96f6-75b7c9da1cf6)


Error Details when I click update:

![image](https://github.com/devtron-labs/devtron/assets/152380397/b66750f7-0e91-4caf-adbd-c4e5e2adcac0)

**Comment by zohebshaik41** [comment]
From all the worker nodes, I've verified below access and it's responding with 200 code.

curl https://api.devtron.ai/health
{"code":200,"result":"OK"

**Comment by zohebshaik41** [comment]
@pawan-mehta-dt Adding error details here:

{"level":"error","ts":1708497973.3818345,"caller":"telemetry/PosthogClient.go:88","msg":"error fetching posthog api key, http call","err":"Get \"https://telemetry.devtron.ai/devtron/telemetry/posthogInfo\": dial tcp: lookup telemetry.devtron.ai on 10.96.0.10:53: server misbehaving","stacktrace":"github.com/devtron-labs/devtron/client/telemetry.getPosthogApiKey\n\t/go/src/github.com/devtron-labs/devtron/client/telemetry/PosthogClient.go:88\ngithub.com/devtron-labs/devtron/client/telemetry.NewPosthogClient\n\t/go/src/github.com/devtron-labs/devtron/client/telemetry/PosthogClient.go:55\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/devtron/cmd/external-app/wire_gen.go:300\nmain.main\n\t/go/src/github.com/devtron-labs/devtron/cmd/external-app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}

Looks like devtroncd needs external URL access and from cluster, the pods are not able to reach devtroncd URLs.

Are there any list of URLs, I need to allow or to sort this issue?

**Comment by pawan-mehta-dt** [comment]
Air gapped installation is part of our enterprise offering as of now @zohebshaik41 

You can check more details about the same here - https://devtron.ai/pricing

**Comment by zohebshaik41** [comment]
For now, only option is: Either access those URLs by allowing it at f/w level or else enterprise one.

**Comment by zohebshaik41** [comment]
From all worker nodes, I am able to access the URLs mentioned above. Not sure, why the pods are not able to reach the URLs.

I've verified the URLs from the worker nodes, and it's reachable.

Any suggestions?

**Comment by pawan-mehta-dt** [comment]
@zohebshaik41 You can join our discord community to continue the conversation as our whole team is available there to help

https://discord.devtron.ai

**Comment by zohebshaik41** [comment]
@pawan-mehta-dt Already I am in the community and raise this issue few days back. Badal asked me to verify few things and I did.

Now the only help required is, to enable that http proxy for devtron components.

As the URLs are reachable from worker nodes.

**Comment by pawan-mehta-dt** [comment]
Please ping me (`@pawanmehta`) or Badal (`@badal0090`) on discord and we'll help you setup http proxy in devtron components

**Comment by zohebshaik41** [comment]
@pawan-mehta-dt I just pinged you in discord and you can see my message.

**Comment by zohebshaik41** [comment]
@pawan-mehta-dt @badal773 

Please find the error logs:

 kubectl logs image-scanner-6f8fc56b5f-bcpqz -n devtroncd
hello
{"level":"error","ts":1708520392.210706,"caller":"sql/connection.go:42","msg":"error in connecting db ","db":{"Addr":"127.0.0.1","Port":"5432","User":"","Password":"********","Database":"orchestrator","ApplicationName":"image-scanner","LogQuery":true},"err":"dial tcp 127.0.0.1:5432: connect: connection refused","stacktrace":"github.com/devtron-labs/image-scanner/internal/sql.NewDbConnection\n\t/go/src/github.com/devtron-labs/image-scanner/internal/sql/connection.go:42\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/image-scanner/wire_gen.go:37\nmain.main\n\t/go/src/github.com/devtron-labs/image-scanner/main.go:13\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
2024/02/21 12:59:52 dial tcp 127.0.0.1:5432: connect: connection refused
panic: dial tcp 127.0.0.1:5432: connect: connection refused

goroutine 1 [running]:
log.Panic({0xc00051df60?, 0xc000014018?, 0xc00051df40?})
        /usr/local/go/src/log/log.go:384 +0x65
main.main()
        /go/src/github.com/devtron-labs/image-scanner/main.go:15 +0x8d

**Comment by zohebshaik41** [comment]
`kubectl get cm devtron-custom-cm -n devtroncd -o yaml
apiVersion: v1
data:
  DEFAULT_CI_IMAGE: quay.io/devtron/ci-runner:d4dadb96-138-20830
  HTTP_PROXY: ip:8080
  HTTPS_PROXY: ip:8080
  NO_PROXY: localhost,podcidr,127.0.0.1,.svc,.cluster.svc,.svc.cluster.local,.argo,.devtron-cd,.devtron-ci,.devtron-demo,.devtroncd,.monitoring,argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,argocd-dex-server,.bs.ch,dashboard-service,devtron-minio,devtron-minio-svc,devtron-nats,devtron-service,git-sensor-service,kubelink-service,lens-service,postgresql-postgresql,postgresql-postgresql-headless,postgresql-postgresql-metrics
  http_proxy: ip:8080
  https_proxy: ip:8080
kind: ConfigMap
metadata:
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: devtron
    meta.helm.sh/release-namespace: devtroncd
  creationTimestamp: "2024-02-14T11:18:23Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    release: devtron
  name: devtron-custom-cm
  namespace: devtroncd
  resourceVersion: "27294608"
  uid: f39077c1-2f26-40b5-8bd7-0f175c714354`

**Comment by zohebshaik41** [comment]
data:
  DEFAULT_CI_IMAGE: quay.io/devtron/ci-runner:d4dadb96-138-20830
  HTTP_PROXY: ip:8080
  HTTPS_PROXY: ip:8080
  NO_PROXY: localhost,podcidr,127.0.0.1,.svc,.cluster.svc,.svc.cluster.local,.argo,.devtron-cd,.devtron-ci,.devtron-demo,.devtroncd,.monitoring,argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,argocd-dex-server,.bs.ch,dashboard-service,devtron-minio,devtron-minio-svc,devtron-nats,devtron-service,git-sensor-service,kubelink-service,lens-service,postgresql-postgresql,postgresql-postgresql-headless,postgresql-postgresql-metrics

**Comment by zohebshaik41** [comment]
![image](https://github.com/devtron-labs/devtron/assets/152380397/5594caaf-821e-459b-a2d0-6f2f8eb9414e)

**Comment by zohebshaik41** [comment]
updated configmap and executing patch command for kubelink for this. But getting same connection refused error

![image](https://github.com/devtron-labs/devtron/assets/152380397/6e5449e5-9487-4e50-a74e-fdf13f68ab11)


kubelink pod error details:

{"level":"error","ts":1708523436.2589505,"caller":"sql/connection.go:62","msg":"error in connecting db ","db":{"Addr":"127.0.0.1","Port":"5432","User":"","Password":"********","Database":"orchestrator","ApplicationName":"orchestrator","LogQuery":true,"LogAllQuery":false,"ExportPromMetrics":false,"QueryDurationThreshold":5000},"err":"dial tcp 127.0.0.1:5432: connect: connection refused","stacktrace":"github.com/devtron-labs/kubelink/pkg/sql.NewDbConnection\n\t/go/src/github.com/devtron-labs/kubelink/pkg/sql/connection.go:62\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/kubelink/wire_gen.go:34\nmain.main\n\t/go/src/github.com/devtron-labs/kubelink/Main.go:8\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
2024/02/21 13:50:36 dial tcp 127.0.0.1:5432: connect: connection refused
panic: dial tcp 127.0.0.1:5432: connect: connection refused

goroutine 1 [running]:
log.Panic({0xc0007bff60?, 0x3245870?, 0x0?})
        /usr/local/go/src/log/log.go:384 +0x65
main.main()
        /go/src/github.com/devtron-labs/kubelink/Main.go:10 +0x4b

**Comment by zohebshaik41** [comment]
@abhibhaw Yes it's working. Pawan & Badal helped in fixing this issue.

I would like to thank Pawan & Badal for their support.

**Comment by abhibhaw** [comment]
@pawan-mehta-dt Is ther any action item for us? Any doc improvements / product improvements required?

**Comment by kranthikirang** [comment]
simply adding no_proxy solved the issue reaching to default cluster?
