### ISSUE TITLE
Bug: nats connection is failing 

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4702]
### 📜 Description

error while subscribing to nats ","stream":"ORCHESTRATOR","topic":"HELM-CHART-INSTALL-STATUS-TOPIC","error":"configuration requests ack wait to be 5m0s, but consumer's value is 30s","stacktrace":"github.com/devtron-labs/common-lib/pubsub-lib.PubSubClientServiceImpl.Subscribe\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go:127\ngithub.com/devtron-labs/devtron/pkg/appStore/deployment/fullMode.AppStoreDeploymentFullModeServiceImpl.subscribeHelmInstallStatus\n\t/go/src/github.com/devtron-labs/devtron/pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go:310\ngithub.com/devtron-labs/devtron/pkg/appStore/deployment/fullMode.NewAppStoreDeploymentFullModeServiceImpl\n\t/go/src/github.com/devtron-labs/devtron/pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go:111\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/devtron/wire_gen.go:480\nmain.main\n\t/go/src/github.com/devtron-labs/devtron/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
 

### Criticality

P2 - Medium

### Impact on Enterprise

all

### 👟 Steps to replicate the Issue

use nats version 2.6.3

### 👍 Expected behavior

should able to connect with nats

### 👎 Actual Behavior

crashloopbackoff

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8623

**Comment by vikramdevtron** [comment]
Fix : Upgrade the NATS server version to 2.9.3
