### ISSUE TITLE
Bug: Scanning images encounters a 500 error during the build process.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#4703]
### 📜 Description

While initiating the build process for our application utilizing the ECR container repository, we encounter the following error during image scanning

**`Image Scan err {"code":500,"status":"Internal Server Error","errors":[{"code":"000","internalMessage":"[{can't pull fsLayers}]","userMessage":"can't pull fsLayers"}]}`**

Image scanner logs

```
{"level":"error","ts":1708442073.2559178,"caller":"api/RestHandler.go:99","msg":"err in process msg","err":"can't pull fsLayers","stacktrace":"github.com/devtron-labs/image-scanner/api.(*RestHandlerImpl).ScanForVulnerability\n\t/go/src/github.com/devtron-labs/image-scanner/api/RestHandler.go:99\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/devtron-labs/common-lib/middlewares.Recovery.func1\n\t/go/src/github.com/devtron-labs/image-scanner/vendor/github.com/devtron-labs/common-lib/middlewares/recovery.go:26\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/devtron-labs/image-scanner/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/image-scanner/internal/middleware/instrument.go:70\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/image-scanner/vendor/github.com/gorilla/mux/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2936\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1995"}
[Feb 20 2024 20:44:33 GMT+0530] image-scanner-6fff4b665b-qlk92: {"level":"info","ts":1708442073.2559457,"caller":"api/apiError.go:64","msg":"ERROR RES","TYPE":"API-ERROR","RES":500,"ERROR-MSG":[{"code":"000","internalMessage":"[{can't pull fsLayers}]","userMessage":"can't pull fsLayers"}],"err":null}
```

### Criticality

P0 - Critical/Blocking

### Impact on Enterprise

ENT-DEY

### 👟 Steps to replicate the Issue

NA

### 👍 Expected behavior

The image should be scanned, and the build should succeed.

### 👎 Actual Behavior

The build is currently failing because the image scanning is throwing a 500 error.

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8626

**Comment by vikramdevtron** [comment]
Use Trivy
