### ISSUE TITLE
Feature: Use helm upgrade --install in NO_GITOPS for helm apps as well

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#4738]
### 🔖 Feature description

Use helm upgrade --install in NO_GITOPS for helm apps as well

### 🎤 Pitch / Usecases

If the first release in helm chart deployment fails, we mark it as release created and after fixing when we run again, it tried to upgrade which doesn't work as helm release was not created in first deployment.
This also fails DR mechanism in case of NO_GITOPS for helm apps, for devtron apps this is working fine

### 🔄️ Alternative

We have to manually set release created to false in database for successful deployment

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8759

**Comment by prakarsh-dt** [comment]
@prakash100198 This implementation needs to be reviewed by @nishant-d

**Comment by prakash100198** [comment]
Upon conducting a thorough investigation into the matter, an intriguing issue has surfaced regarding the installation behavior of Helm SDK's install flag. Specifically, it appears that the install flag itself does not facilitate the automatic installation of a chart during the upgrade command if a release does not already exist. In contrast, Helm CLI handles this scenario differently: when executing "helm upgrade --install ..." command, Helm CLI triggers a manual install if the install flag is provided and the release is not found.

For more details pls refer to below links:- 
https://github.com/helm/helm/blob/main/cmd/helm/upgrade.go
https://github.com/helm/helm/blob/e5e3fac3ca06970ad52012fe8cd92b0d2761bff0/pkg/action/upgrade.go#L49
