### ISSUE TITLE
Bug: Private Registry Error 

### ISSUE THREAD

**Issue by antikilahdjs** [devtron-labs/devtron#4749]
### 📜 Description

When I try to configure the private registry I am getting a error like below:

2024/03/05 14:19:36 parse "172.30.104.250:30002": first path segment in URL cannot contain colon

I cannot run my pipelines using the Harbor due the error above.

### 👟 Reproduction steps

1. Just install the devtron using the official helm charts

### 👍 Expected behavior

Works with more resources for housekeeping

### 👎 Actual Behavior

2024/03/05 14:19:36 parse "172.30.104.250:30002": first path segment in URL cannot contain colon

![image](https://github.com/devtron-labs/devtron/assets/33559260/5abc2bdc-2f27-4ba6-9f03-abe3c668a472)

### ☸ Kubernetes version

On-Premise 1.23.6

### Cloud provider

<details>
Not using cloud in this environment
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

I dont know, I tried many approach but the error keeping showing

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8787

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4712] Bug: Error Handling in Bulk Edit (60%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4712] Bug: Error Handling in Bulk Edit (60%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4712] Bug: Error Handling in Bulk Edit (60%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4712] Bug: Error Handling in Bulk Edit (60%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4712] Bug: Error Handling in Bulk Edit (60%)

**Comment by antikilahdjs** [comment]
Hello @prakarsh-dt it is possible help on it? Please

**Comment by antikilahdjs** [comment]
Update: I tried changed directly in the database but got the same error. My server for now is HTTP and it was marked as Insecure but keeps show the HTTPS error

 time="2024-03-07T12:28:16Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://172.30.104.250:30002/v2/\": http: server gave HTTP response to HTTPS client"

 Get "https://172.30.104.250:30002/v2/": http: server gave HTTP response to HTTPS client

![image](https://github.com/devtron-labs/devtron/assets/33559260/2544d41f-e08a-4e65-95ad-22e73a344b19)
