### ISSUE TITLE
Feature: Showing ENV list in EA mode

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4803]
### 🔖 Feature description

in EA mode, We are showing `+ add environment` but not showing list of environments.

### 🎤 Pitch / Usecases

user should able to list envs added by him/her

### 🔄️ Alternative

We can also add button to add existing namespace in my cluster to env in devtron.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8931

**Comment by abhibhaw** [comment]
Fixed during recent EA fix activity
