### ISSUE TITLE
Bug: adding cd between two cd's for external ci pipeline , corrupts the whole pipeline UI.

### ISSUE THREAD

**Issue by kushagra-devtron** [devtron-labs/devtron#4812]
### 📜 Description

Bug: adding cd between two cd's for external ci pipeline , corrupts the whole pipeline UI.

### 👟 Reproduction steps

1. create a external ci pipeline.
2. add a cd pipeline between to cd's
3. verify the result.

### 👍 Expected behavior

cd should get added between two cd's

### 👎 Actual Behavior

whole UI corrupts.

### ☸ Kubernetes version

latest

### Cloud provider

<details>
azure
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

cd

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shivam-nagar23** [comment]
Issue with payload, PipelineType is being sent as webhook, instead should be CD_PIPELINE
