### ISSUE TITLE
Bug: NATS messages are in pending state CD-STAGE-SUCCESS-EVENT

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4819]
### 📜 Description

getting pending ack in nats for topic CD-STAGE-SUCCESS-EVENT

orchestrator log --
06_52_22.log:871:nats: slow consumer, messages dropped on connection [468] for subscription on "CD-STAGE-SUCCESS-EVENT" 

Nats box log --- 
~ # nats stream view ORCHESTRATOR --subject=CD-STAGE-SUCCESS-EVENT
[1232] Subject: CD-STAGE-SUCCESS-EVENT Received: 2024-03-19T06:43:20Z

  Nats-Msg-Id: MsgHeaderId-ym5fec8iio

{"deployStageType":"","pipelineOverride":{"Id":13186,"RequestIdentifier":"","EnvConfigOverrideId":11111,"PipelineOverrideValues":"{\"server\":{\"deployment\":{\"image_tag\":\"11111-11111-11111\",\"image\":\"11111.11111.io/uat/saf\"}},\"pipelineName\": \"cd-11-11111\",\"releaseVersion\":\"18\",\"deploymentType\": \"BLUE-GREEN\", \"app\": \"11111\", \"env\": \"11111\", \"appMetrics\": false}","PipelineMergedValues":"{\"ConfigMaps\":{\"enabled\":true,\"maps\":[{\"esoSecretData\":{},\"external\":true,\"externalType\":\"\",\"filePermission\":\"\",\"mountPath\":\"\",\"name\":\"73s-.{\"Ma[],\"waitForSecondsBeforeScalingDown\":30}","Status":0,"GitHash":"sha256:11111","CommitTime":"2024-03-19T06:43:20.516548Z","PipelineId":11111,"CiArtifactId":11111,"PipelineReleaseCounter":11111,"CdWorkflowId":11111,"DeploymentType":1,"CreatedOn":"2024-03-19T06:43:19.544465Z","CreatedBy":11111,"UpdatedOn":"2024-03-19T06:43:19.544465Z","UpdatedBy":11111,"EnvConfigOverride":null,"CiArtifact":null,"Pipeline":{"Id":11111,"AppId":11111,"App":{"Id":0,"AppName":"","DisplayName":"","Active":false,"TeamId":0,"AppType":0,"AppOfferingMode":"","Description":"","Team":{"Id":0,"Name":"","Active":false,"CreatedOn":"0001-01-01T00:00:00Z","CreatedBy":0,"UpdatedOn":"0001-01-01T00:00:00Z","UpdatedBy":0},"CreatedOn":"0001-01-01T00:00:00Z","CreatedBy":0,"UpdatedOn":"0001-01-01T00:00:00Z","UpdatedBy":0},"CiPipelineId":337,"TriggerType":"MANUAL","EnvironmentId":11111,"Name":"cd-11111-11111","Deleted":false,"PreStageConfig":"","PostStageConfig":"","PreTriggerType":"","PostTriggerType":"","PreStageConfigMapSecretNames":"{\"configMaps\":[],\"secrets\":[]}","PostStageConfigMapSecretNames":"{\"configMaps\":[],\"secrets\":[]}","RunPreStageInEnv":true,"RunPostStageInEnv":true,"DeploymentAppCreated":false,"DeploymentAppType":"manifest_push","DeploymentAppName":"xxxx","DeploymentAppDeleteRequest":false,"UserApprovalConfig":"","Environment":{"Id":0,"Name":"","ClusterId":0,"Cluster":null,"Active":false,"Default":false,"GrafanaDatasourceId":0,"Namespace":"","EnvironmentIdentifier":"","Description":"","IsVirtualEnvironment":false,"CreatedOn":"0001-01-01T00:00:00Z","CreatedBy":0,"UpdatedOn":"0001-01-01T00:00:00Z","UpdatedBy":0},"CreatedOn":"2023-11-16T11:08:50.433488Z","CreatedBy":11111,"UpdatedOn":"2023-11-29T07:09:18.450388Z","UpdatedBy":11111}},"cdWorkflowId":0,"pipelineId":0,"pluginRegistryImageDetails":null}

Subject: _INBOX.Jr84fWWpvmJlqfXgsgOPfI Reply: 

  Status: 408
  Description: Request Timeout

nil body
08:19:32 Reached apparent end of data

### 👟 Reproduction steps

1. deploy in virtual cluster

### 👍 Expected behavior

no pending ack

### 👎 Actual Behavior

getting pending ack

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by kartik-579** [comment]
fixed with #4775
