### ISSUE TITLE
Bug: [Prod]Able to trigger jobs with "View only" permission

### ISSUE THREAD

**Issue by Harpreet-kaur08** [devtron-labs/devtron#4846]
### 📜 Description

It is a production bug related to user permission

### 👟 Reproduction steps

1. Go to user permission, in devtron apps  give manager permission to a particular project.
2. In jobs , select the same project as devtron apps and select all for other permissions and select view only.
3. Now login with the user and try to trigger the jobs of that project.

### 👍 Expected behavior

The jobs should not be triggered with view only permission.

### 👎 Actual Behavior

The jobs are getting triggered with view only permission.

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
Cloud
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment]
Similar Issue: [prod]Able to create a job after giving "view" permission. 

Go to user permissions under authentication of Global Configuraton
 After selecting specific permission for the desired email id, I went to the 'direct permissions' section.
      3. In devtron apps, select any project and all the environments and all the applications and give admin/Manager      permission.
       4. In jobs, select all the jobs and environments and give view only / run job.

Expected result:
        The user should not be able to create new jobs .

Actual result:
        The user is able to create new jobs but not the workflows.

**Comment by vikramdevtron** [comment]
Fixed Reverted In https://github.com/devtron-labs/devtron/pull/5206
