### ISSUE TITLE
Unable to install agent on an EKS Cluster

### ISSUE THREAD

**Issue by ApoorvMangal** [devtron-labs/devtron#4851]
### 📜 Description

Clicking on Install Agent gives an error.

### 👟 Reproduction steps

Click on Install Agent for an EKS cluster.

![image](https://github.com/devtron-labs/devtron/assets/64570087/b89fbf0a-990f-46e4-903d-60b786c6a383)

### 👍 Expected behavior

Agent should get installed

### 👎 Actual Behavior

Agent installation failing with message pg: no rows in result set

![image](https://github.com/devtron-labs/devtron/assets/64570087/d20ce8af-fa52-4795-bee5-41c3aac551dc)

### ☸ Kubernetes version

EKS 1.29

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
The agent has been deprecated and all the functionality of devtron will work without agent. Installing of agent is not required now.
