### ISSUE TITLE
Bug: jobConfigs.suspend: true doesn't works in case of helm devtron apps

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#4860]
### 📜 Description

The following configurations do not include `suspend: true` when manifest generation is done for comparison while editing deployment template as well as when it is deployed to the target cluster.
The issue seems to be from the KubeVersion condition as it works fine after removal of this line, however the helm template works fine with it https://github.com/devtron-labs/devtron/blob/4874646eb83671f2b6898163ab6e58ef43faf70c/scripts/devtron-reference-helm-charts/cronjob-chart_1-5-0/templates/_job_template_spec.yaml#L15

Deployment template config
```yaml
jobConfigs
  suspend: true 
```

### Affected areas

CD

### Additional affected areas

None

### Prod/Non-prod environments?

Non-prod

### Is User unblocked?

Yes

### How was the user un-blocked?

TEMPORARILY - By doing some changes from the backend/DB

### Impact on Enterprise

Users were unable to suspend the execution of job which affected the execution of dependent jobs.

### 👟 Steps to replicate the Issue

1. Create a devtron application selecting chart type as `Job and Cronjob`.
2. Create a Helm CD pipeline.
3. Set `jobConfigs.suspend: true` and `kind: Job`
4. Deploy it, `suspend: true` would not reflect in the Job manifest deployed.
5. Check manifest generation in the deployment template, suspend: true will not appear there as well in the generated manifest.

### 👍 Expected behavior

`suspend: true` should reflect in the job manifest as well as generated manifest in deployment template.

### 👎 Actual Behavior

`suspend: true` not reflecting in the job manifest as well as generated manifest in deployment template.

### ☸ Kubernetes version

EKS 1.27, EKS 1.28

### Cloud provider

<details>
AWS, GCP
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4805] Bug: All Helm Apps of a namespace is not visible in Devtron UI (65.36%)
