### ISSUE TITLE
Feature: Add BitBucket Server (not Cloud) as supported GitOps provider

### ISSUE THREAD

**Issue by u72z** [devtron-labs/devtron#4887]
### 🔖 Feature description

Would be nice to support BitBucket Server as well. The configuration shouldn't be very different, but as far as I know BitBucket doesn't have the concept of Workspace, which is a mandatory field when configuring BitBucket (Cloud) as a GitOps provider.

https://en.wikipedia.org/wiki/Bitbucket
https://support.atlassian.com/migration/docs/differences-administering-bitbucket-data-center-and-cloud/

### 🎤 Pitch / Usecases

For the ones who want to host their GitOps repos on-prem, right now the only possibility is GitLab

### 🔄️ Alternative

The only alternative to have the GitOps on-prem is GitLab

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9134

**Comment by abhibhaw** [comment]
Fixed with attached PRs
