### ISSUE TITLE
Feature: More configuration options for the mail SMTP notifier

### ISSUE THREAD

**Issue by u72z** [devtron-labs/devtron#4888]
### 🔖 Feature description

Add a drop down list "Encryption Method" SSL/TLS or None (maybe automatically adjust the port, 25, 465 or 587)
Add a checkbox "The mail server requires authentication" which would then show/hide both username and password fields

Example of another mail client:

![image](https://github.com/devtron-labs/devtron/assets/138193092/285deffc-0204-4d38-a0f8-191eb8e54b2c)

### 🎤 Pitch / Usecases

Currently the mail client (SMTP configuration for notifications) is not flexible.

Only encrypted and authenticated smtp is supported, which poses certificates challenges in some environment, where encryption nor authentication isn't required, for example when both devtron and the email server run in the same network.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9136

**Comment by u72z** [comment]
any update on this one ?

**Comment by abhibhaw** [comment]
Hey @u72z we're working on this request. You can expect this with our next release. If this one is a blocker for your org, let's connect on discord (my username abhibhaw) and I could try to see how quickly we can unblock you.

**Comment by u72z** [comment]
> Hey @u72z we're working on this request. You can expect this with our next release. If this one is a blocker for your org, let's connect on discord (my username abhibhaw) and I could try to see how quickly we can unblock you.

thanks for the update
