### ISSUE TITLE
Bug: select material functionality breaking for ci pipeline,  when communication between orch and git-sensor is on REST rather than GRPC.

### ISSUE THREAD

**Issue by kushagra-devtron** [devtron-labs/devtron#4905]
### 📜 Description

select material functionality breaking for ci pipeline,  when communication between orch and git-sensor is on REST rather than GRPC.

### 👟 Reproduction steps

change the CM keys for REST communication between gitsensor and orch.
GIT_SENSOR_URL: git-sensor-enterprise-automation-dcd-service.devtroncd:90

GIT_SENSOR_PROTOCOL: GRPC
​Bounce the orch pod 
click on select material for any ci pipeline.

### 👍 Expected behavior

Commits from the respective git repo should be show.

### 👎 Actual Behavior

Internal Server Error

### ☸ Kubernetes version

latest

### Cloud provider

<details>
Azure
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9212

**Comment by ashishdevtron** [comment]
this is working fine, there might be any configuration issue on git-sensor, like 
- it is possible that at the time of creation of this bug, in git-sensor-service, port for REST protocol was not configured
