### ISSUE TITLE
Bug: resource browser UI issues

### ISSUE THREAD

**Issue by kushagra-devtron** [devtron-labs/devtron#4917]
### 📜 Description

conenection closing in terminal chaneg
pod manifest and terminal not persist
single terminal - pod terminal state connection not persisting , after moving to resource tree and back

### 👟 Reproduction steps

conenection closing in terminal chaneg
pod manifest and terminal not persist
single terminal - pod terminal state connection not persisting , after moving to resource tree and back

### 👍 Expected behavior

state should persist 

### 👎 Actual Behavior

state should not persist 

### ☸ Kubernetes version

latest

### Cloud provider

<details>
azure
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9254

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4914] Bug:[prod**] pagination bug on resource browser (67%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4914] Bug:[prod**] pagination bug on resource browser (67%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4914] Bug:[prod**] pagination bug on resource browser (67%)
