### ISSUE TITLE
logs of init container is missing from devtron UI

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#492]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

there is no option for viewing logs of init container from devtron UI 
**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1.  add init container in deployment template
2. deploy the new config 
3. there is no option to select init container from devtron UI in logs section

**Expected behaviour **

option to select init container in logs section
**Current behaviour** 

only main containers are available for selection

**Comment by tbnjha** [comment]
Any ETA on this bug?
