### ISSUE TITLE
Bug: [Prod] Not able to copy secret values in cloned applications

### ISSUE THREAD

**Issue by anand-swrp** [devtron-labs/devtron#4924]
### 📜 Description

[Prod] Not able to copy secret values in cloned applications

### 👟 Reproduction steps

1. Create an application and Clone it with some other Application initially.
2. The App that was cloned has CM & CS applied.

### 👍 Expected behavior

If we clone any existing application with a new application, the new application shall inherit all the CM & CS that was applied in it.
In the case of Secrets, the Key Values in the new application shall come exactly same from the app which was used for clonning.

### 👎 Actual Behavior

Here in the Case of Secrets, in the new Application only Keys are coming and leaving the Values. In Key-Values of Secrets, Key is inherited from the Cloned app and not the Values.

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9280

**Comment by abhibhaw** [comment]
This is an expected behaviour. Reason: It can lead to security loop holes. Imagine a person X, who is not an admin of an application A, cannot see secrets of that application A. But if we allow this if he/she/they creates a new application B by cloning application A, he will be able to see the secrets.
