### ISSUE TITLE
Bug: AutoTrigger stops working sometimes

### ISSUE THREAD

**Issue by drpdishant** [devtron-labs/devtron#4925]
### 📜 Description

It happens randomly that the autotrigger doesn't work when developers push a new commit. Reason for this is unknown but autotrigger is executed for all the pending commits if we recreate the pods in devtroncd namespace.

### 👟 Reproduction steps

No such steps for reproduction. I am not sure whether others are facing the issue, but need to understand where can we observe the logs for any errors.

### 👍 Expected behavior

Autotrigger should run indefinitely for all the new commits for the configured branch.

### 👎 Actual Behavior

![Screenshot from 2024-04-10 16-08-29](https://github.com/devtron-labs/devtron/assets/27772366/fbf58b7e-2d6d-4634-873e-b1c06ba09f2c)

If you observe the commite timestamp and autotrigger time you see there's a big difference.
And that too was triggered when I restarted all the pods in devtron namespace.

There's another issue which is also related devtron service that led me to abort the manually created builds in between. I'll raise it separately.

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

AWS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9290

**Comment by abhibhaw** [comment]
This has been fixed in our recent release, feel free to reopen if you still encounter this issue
