### ISSUE TITLE
Bug: Devtron Backgroud Events fail to propagate

### ISSUE THREAD

**Issue by drpdishant** [devtron-labs/devtron#4926]
### 📜 Description

Event status across devtron pods and pipeline fail to propagate effectively.
- This behviour I have observed during build run.
- The build would start, but as expected worker pod details are not returned and it remains in starting state.
- Simultaneously, pod as actually started and running the build, and it completes too.
- Running status and completions status are not reflected in the devtron build pipeline and hence it doesn't have the build artifacts to proceed with the deployment.

### 👟 Reproduction steps

Not sure if it can be reproduced somewhere else.

### 👍 Expected behavior

Build status should be effectively be returned to devtron service from the runner pod.

### 👎 Actual Behavior

<img width="1512" alt="image3" src="https://github.com/devtron-labs/devtron/assets/27772366/78f581ed-cb62-4b57-911a-1433a979bdcc">
<img width="1512" alt="image2" src="https://github.com/devtron-labs/devtron/assets/27772366/c98c3113-8491-4f3c-91d0-63013bca9b62">
<img width="1453" alt="image" src="https://github.com/devtron-labs/devtron/assets/27772366/958ab7fe-287f-4cbf-a87d-d739d4360772">

As observed you can see the pod is running build, but the dashboard is not getting the actual status and logs.

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

AWS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9292

**Comment by abhibhaw** [comment]
This has been fixed, feel free to reopen if still exist
