### ISSUE TITLE
Bug: Gitops config with self managed Gitlab error

### ISSUE THREAD

**Issue by memoverflow** [devtron-labs/devtron#4938]
### 📜 Description

Hi All,

When I try to config the gitops with Gitlab, I got Internal Error on the web page
![Xnip2024-04-13_20-53-29](https://github.com/devtron-labs/devtron/assets/3076910/aae72a0f-48b6-4072-b37a-1c69cc41184a)
![Xnip2024-04-13_20-53-47](https://github.com/devtron-labs/devtron/assets/3076910/59e9f99f-6b79-4f46-b1c4-956c0ee0de33)

### 👟 Reproduction steps

1. Configure GitOps
2. Choose Gitlab
3. Full fill the inputs 

### 👍 Expected behavior

Works fine

### 👎 Actual Behavior

Internal error
![Xnip2024-04-13_20-54-15](https://github.com/devtron-labs/devtron/assets/3076910/3aba7baf-3129-4948-9483-a372caff7dc4)

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

AWS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9329

**Comment by abhibhaw** [comment]
This has been fixed, please feel free to reopen, if still exists
