### ISSUE TITLE
Bug: Getting context deadline cancelled post deployment

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#4943]
### 📜 Description

Getting context deadline canceled post-deployment

### Affected areas

CD

### Additional affected areas

None

### Prod/Non-prod environments?

Prod

### Is User unblocked?

No

### How was the user un-blocked?

PERMANENTLY - By giving a workaround (From outside Devtron)

### Impact on Enterprise

Deployment fails and user need to redeploy.

### 👟 Steps to replicate the Issue

1. Trigger the deploy button
2. Refresh the page immediately 

### 👍 Expected behavior

It should deploy successfully

### 👎 Actual Behavior

It is throwing context deadline cancelled canceled

### ☸ Kubernetes version

1.28

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9351

**Comment by vikramdevtron** [comment]
@Ash-exp please confirm still exists or not ?

**Comment by vikramdevtron** [comment]
Fixed in https://github.com/devtron-labs/devtron/pull/5412
