### ISSUE TITLE
Bug: Page automatically getting redirected to another page in case of helm apps

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#4945]
### 📜 Description

It bugs out when you deploy a helm app and switch the page just after deploying, it'll redirect you back to original app which you deployed. 

### 👟 Reproduction steps

1. Deploy a heavy helm app (let say kube-prometheus-stack), lets call this "x" 
2. Immediately Go to another helm app, lets call this "y". 
3. You shall be redirected back to application "x" after a few seconds. 

### 👍 Expected behavior

automatic page redirection should not happen 

### 👎 Actual Behavior

automatic page redirection is happening 

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9353

**Comment by vikramdevtron** [comment]
@tayalrishabh96

**Comment by vivek-devtron** [comment]
Fixed with Prompt
