### ISSUE TITLE
Error handling can be improved while creating a new App

### ISSUE THREAD

**Issue by Abhinav-26** [devtron-labs/devtron#496]
Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [X] I've included steps to reproduce the bug.

**Describe the bug**

An error is occurred if wrong naming conventions are used while giving a new app name which is difficult to understand.

<img width="1436" alt="Screenshot 2021-06-02 at 11 04 39 PM" src="https://user-images.githubusercontent.com/48083659/120596891-ece16b80-c461-11eb-821c-a26bd0b23344.png">

**To Reproduce**

1. User goes to Create an application (to save space or whatever)
2. User selects Add New App
3. User follows the wrong naming convention to enter app name 
4. Error is occurred which is difficult to understand for users

**Expected behavior**

Naming Convention should be given initially to enter the App Name or it can be given while error handling in user readable format. 

**Current behavior** 

It doesn't give any examples/ naming conventions to follow while giving App Name and if wrong convention is followed, an error is occurred which is difficult to understand.

**Comment by uxarya-d** [comment]
Please show error below the app name field.
Refer: https://zpl.io/bAQqrxP

<img width="426" alt="Screenshot 2021-06-11 at 11 12 07 AM" src="https://user-images.githubusercontent.com/73632042/121636666-de203780-caa5-11eb-9d07-f67b51d8c237.png">
