### ISSUE TITLE
Bug: Update operation not working for AWS public helm registry

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#4969]
### 📜 Description

getting error like 
rpc error: code = Unknown desc = MissingRegion: could not find region configuration
 
 in case of redeploying karpenter chart

### Affected areas

Deployment from Chart store

### Additional affected areas

Other CRITICAL functionality

### Prod/Non-prod environments?

Prod

### Is User unblocked?

No

### How was the user un-blocked?

PERMANENTLY - By giving a workaround (From outside Devtron)

### Impact on Enterprise

SP 

### 👟 Steps to replicate the Issue

use karpenter helm chart with AWS helm repo (OCI)

### 👍 Expected behavior

should able to  redeploy the chart 

### 👎 Actual Behavior

giving issue like 
rpc error: code = Unknown desc = MissingRegion: could not find region configuration

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9433

**Comment by vikramdevtron** [comment]
Closed
