### ISSUE TITLE
Obfuscate / Skip logging sensitive info in the console until debug mode is enabled

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#499]
Obfuscate or skip logging sensitive info (passwords, keys etc) in the console until debug mode is enabled

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Some micro-services log sensitive info in the console logs, which should not be done until debug mode is enabled. Check the following micro-services:

1. Git-sensor
2. Devtron Orchestrator
3. Ci-runner

**Expected behavior**

Logs should not contain any sensitive info like passwords, keys, tokens etc.

**Current behavior** 

Some micro-services log sensitive info on console.

**Comment by pghildiyal** [comment]
Git related details are also logged

**Comment by hariprasadiit** [comment]
I can see my GitLab access token in Devtron logs. I don't think I've changed log level. is there anything that needs to be done that I missed?

**Comment by kripanshdevtron** [comment]
Let me check on this.

**Comment by prakarsh-dt** [comment]
This is not yet released in OSS stack. Will be available in the next release.
