### ISSUE TITLE
Bug: Inception is not getting healthy while upgrading Devtron to latest version

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#4990]
### 📜 Description

We are getting below error in  inception pod when we upgrade Devtron to latest version.

```
Starting workers	{"reconcilerGroup": "installer.devtron.ai", "reconcilerKind": "Installer", "controller": "installer", "worker count": 1}
url changed
updating
2024-02-01T07:40:52.132Z	ERROR	controllers.Installer	error while requesting	{"error": "Get \"http://metadata.google.internal/computeMetadata/v1/instance/tags\": dial tcp: lookup metadata.google.internal on 10.100.0.10:53: no such host", "requestError": "json: unsupported type: func() (io.ReadCloser, error)", "error": "Get \"http://metadata.google.internal/computeMetadata/v1/instance/tags\": dial tcp: lookup metadata.google.internal on 10.100.0.10:53: no such host"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.3.0/zapr.go:132
github.com/devtron-labs/inception/pkg/providerIdentifier/providers.(*IdentifyGoogle).IdentifyViaMetadataServer
	/workspace/pkg/providerIdentifier/providers/google.go:37
panic: send on closed channel

goroutine 247 [running]:
github.com/devtron-labs/inception/pkg/providerIdentifier/providers.(*IdentifyGoogle).IdentifyViaMetadataServer(0xc000ccfa70, 0xc00018cb40)
	/workspace/pkg/providerIdentifier/providers/google.go:38 +0x3b8
created by github.com/devtron-labs/inception/pkg/providerIdentifier.(*ProviderIdentifierServiceImpl).IdentifyProvider
	/workspace/pkg/providerIdentifier/ProviderIdentifierService.go:61 +0x479
```

### 👟 Reproduction steps

1. Install the Devtron version 0.6.26.
2. Try to upgrade to 0.6.27 from Devtron UI page and see the logs of inception pod.

### 👍 Expected behavior

Inception pod shouldn’t through this error.

### 👎 Actual Behavior

Currently inception through above error.

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9525

**Comment by ShashwatDadhich** [comment]
https://github.com/devtron-labs/inception/pull/20
This has been fixed in this PR and the latest version v0.6.29 contains this fix.
