### ISSUE TITLE
Bug: Error in pipelines crude operations, required validations. 

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#4999]
### 📜 Description

We have faced 2 issues while creating the applications through API operations. like linked CI creation and deletion of applications created through linked CI, issues that occur due to validation checks were not implemented. 

Issue 1: 
Linked Pipeline created through the parent ci even if parent ci is deleted.

Issue 2:
linked ci pipeline creation through the Invalid git material ID. 

### 👟 Reproduction steps

Can create an application through deleted linked CI pipeline ID. 
Can create an linked pipeline by passing invalid git material ID.

### 👍 Expected behavior

In normal behaviour, we should have failed the linked ci pipeline creation. 

### 👎 Actual Behavior

pipelines were getting created without any validations. 

### ☸ Kubernetes version

eks 1.28

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9553

**Comment by vikramdevtron** [comment]
Probable duplicate https://github.com/devtron-labs/devtron/issues/4983
