### ISSUE TITLE
Bug: Adding or updating user taking long response time

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#5002]
### 📜 Description

in case of huge existing user base the adding user or updating permissions taking long time to response. 

### 👟 Reproduction steps

use huge database of casbin with multiple policies and try to add new user the API is taking long time

### 👍 Expected behavior

it must give response in minimal time

### 👎 Actual Behavior

taking long time

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9567

**Comment by vikramdevtron** [comment]
may be duplicate https://github.com/devtron-labs/devtron/issues/5240
