### ISSUE TITLE
Bug: Kubelink Requests getting Failed for gRPC method GetAppDetails  

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5008]
### 📜 Description

Kubelink requests fail with below error : 
`{"level":"error","ts":1713965180.331496,"caller":"appList/AppListingRestHandler.go:1074","msg":"error in fetching app detail","err":"rpc error: code = Unknown desc = release not exists for this app"`
This happens even when application is not deployed 
Ideally request should not go to kubelink in the first place.

### Affected areas

CD

### Additional affected areas

None

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

None

### Impact on Enterprise

Unnecessarily requests are going to Kubelink and failing

### 👟 Steps to replicate the Issue

1. create an application with deployment app type as helm.
2. create CI, CD but do not deploy
3. go to app details page and parallelly check orchestrator logs.

### 👍 Expected behavior

Requests should not go to kubelink searching for release as application is not even deployed yet.

### 👎 Actual Behavior

Kubelink throws an error that `release not exists`

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9576

**Comment by ShashwatDevtron** [comment]
This issue was happening because we were fetching the app details of a helm app for an environment in which there was not even a single deployment triggered yet. Need to handle it from the code side by putting a check and not calling the GetAppDetail function in this case.

**Comment by ShashwatDevtron** [comment]
This issue was happening because we were fetching the app details of a helm app for an environment in which there was not even a single deployment triggered yet. Need to handle it from the code side by putting a check and not calling the GetAppDetail function in this case.

**Comment by ShashwatDadhich** [comment]
This issue was happening because we were fetching the app details of a helm app for an environment in which there was not even a single deployment triggered yet. Need to handle it from the code side by putting a check and not calling the GetAppDetail function in this case.
