### ISSUE TITLE
Feature: Support for custom schema for deployment template 

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#5010]
### 🔖 Feature description

Support for custom schema for deployment template 

### 🎤 Pitch / Usecases

As of now, we have pre-defined values for the deployment template which is available in GUI, and want to add some custom value so need support for custom schema json which will allow us to use our own per defined values.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9595

**Comment by abhibhaw** [comment]
Should be closed with #5011
