### ISSUE TITLE
Bug: getting permission denied error in orchestrator 

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#5018]
### 📜 Description

- while opening old ci-logs the devtron container is restarting 
- the issue will be faced in other file operations 

CAUSE 
- in security context the devtron user-id is 1000
- new ubuntu release have 24.04 version is latest and on dockerfile ubuntu latest image is used as base image. 
- in ubuntu 24.04 they introduced new user which is 'ubuntu' with user-id '1000' and thus devtron user is created with id 1001.

### 👟 Reproduction steps

- build devtron image with ubuntu 24.04 version 

### 👍 Expected behavior

- devtron user must able to do all operations without permission issues

### 👎 Actual Behavior

- container getting restarted

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### ✅ Proposed Solution

1. add digest in base image at dockerfile
2. change user id of devtron user
3. replace ubuntu user with devtron (need testing)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9627

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4988] Bug: Orchestrator pod is getting restarting  (65%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4988] Bug: Orchestrator pod is getting restarting  (65%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#4988] Bug: Orchestrator pod is getting restarting  (65%)
