### ISSUE TITLE
Bug:  Not able to connect with terminal of the application pod or cluster terminal 

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#5034]
### 📜 Description

Getting 400 response when trying to get terminal of pod for below api .

**/orchestrator/k8s/pod/exec/sockjs**

When we rotate the orchestrator pod , it was working fine .

### Affected areas

CI/CD Plugins

### Additional affected areas

CD

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

TEMPORARILY - By doing some changes from the backend/DB

### Impact on Enterprise

ENT-DEY

### 👟 Steps to replicate the Issue

NA

### 👍 Expected behavior

It should connect with pod terminal 

### 👎 Actual Behavior

It fails to connect with terminal of pod

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9655

**Comment by vikramdevtron** [comment]
issue with http not with http2
