### ISSUE TITLE
Bug: Build fails when utilizing a container registry with a self-signed certificate in the context of buildx

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#5058]
### 📜 Description

1. Create a container registry with a self-signed cert and try to implement it through Devtron and pass your ca.crt as below 

<img width="916" alt="Screenshot 2024-05-03 at 11 25 42 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/ce7fb9ad-290d-4009-8fd2-9c430dd0270f">

2.  Now try to build it through Devtron and don't implement BUILDX , it will be push to registry without any issue

<img width="1376" alt="Screenshot 2024-05-03 at 11 34 02 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/8447d835-e921-47e4-9fe7-f9d3b2d7c834">

3.  Now try to enable Buildx and try to build, you will be face this issue 

`#10 ERROR: failed to push <registry.domain.com>/library/test:0fd5e184-120-10493: failed to do request: Head "https://registry.domain.com/v2/library/test/blobs/sha256:9368c4e892c0c964d50c773bb1224d98573c77ed05018b2f935fc57f792c64e2": tls: failed to verify certificate: x509: certificate signed by unknown authority
`

Work around , you can exec into buildkit pod and try to store your cert 

- docker ps|grep -i 'buildkit'
- docker exec -it containerID  sh
- docker exec -it containerID  sh
$$ cat >> /etc/ssl/certs/ca-certificates.crt <<'EOF'
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
EOF
$$ exit
- docker restart containerID

Now try to build with build, It will be successful [
<img width="1384" alt="Screenshot 2024-05-03 at 11 40 36 AM" src="https://github.com/devtron-labs/devtron/assets/130441461/24f360f8-74ec-4916-8a47-1087b9e77719">
](url)

### 👟 Reproduction steps

try to setup a selfsigned registry and try to build with buildx in  devtron , the workaround https://github.com/docker/buildx/issues/80#issuecomment-533844117

### 👍 Expected behavior

It should work fine

### 👎 Actual Behavior

Not working 

### ☸ Kubernetes version

1.29

### Cloud provider

<details>
aws
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9707

**Comment by prkhrkat** [comment]
https://github.com/devtron-labs/ci-runner-enterprise/pull/78/files
