### ISSUE TITLE
Bug: devtron-UI get slow caused by timeout in `/orchestrator/module` api

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#5076]
### 📜 Description

even though all the apis giving 200 but the `/orchestrator/module` api is giving timeout and whole page becomes slow.

### Affected areas

Devtron dashboard completely down

### Additional affected areas

Devtron dashboard completely down

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

TEMPORARILY - By disabling a CRITICAL functionality

### Impact on Enterprise

all

### 👟 Steps to replicate the Issue

in the `/orchestrator/module` api give the wrong or time taking process

### 👍 Expected behavior

there should be no dependence on this api

### 👎 Actual Behavior

whole page is slow 

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9744

**Comment by Shivam-nagar23** [comment]
This was closed with [central-api](https://github.com/devtron-labs/central-api/pull/35). Also this was specific wo case when central-api was down.
