### ISSUE TITLE
Trigger job to fetch and update charts as soon as a new helm repo is added

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#508]
# Summary

When a user adds a new Helm repo, he expects that the charts in that repo will be available in the Discover section but the charts aren't available unless the app-sync-cronjob runs next.

<img width="1363" alt="Screenshot 2021-06-09 at 12 54 58 PM" src="https://user-images.githubusercontent.com/71125043/121311344-f109ff00-c921-11eb-95aa-b5d6bd5cfe5e.png">

# Motivation

Charts should be available just after (a delay of a few mins is acceptable) the user has added the helm repo.

# Proposal

Trigger a job that fetches all the charts in the added repo as soon as a chart is added or updated from the devtron UI. The job that updates the charts can be found at https://github.com/devtron-labs/devtron/blob/main/manifests/yamls/migrator.yaml by the name app-sync-job

**Comment by prakarsh-dt** [comment]
@ankutty Can you pick this one?

**Comment by prakarsh-dt** [comment]
@ArunNKutty Can you pick this one?

**Comment by ArunNKutty** [comment]
Sure @prakarsh-dt

**Comment by prakarsh-dt** [comment]
This is done
