### ISSUE TITLE
Remove image related inconsistencies from devtron reference charts

### ISSUE THREAD

**Issue by strawhat5** [devtron-labs/devtron#509]
# Summary

Devtron reference charts has some inconsistencies in picking `imagePullPolicy` from `values.yaml`.

# Motivation

Reference: https://github.com/devtron-labs/devtron/blob/main/scripts/devtron-reference-helm-charts/reference-chart_3-11-0/templates/deployment.yaml#L84-L85

# Proposal

We would like to streamline this so that both `image` and `imagePullPolicy` generate from the same root in `values.yaml`.

**Comment by strawhat5** [comment]
Will raise a PR soon.

**Comment by prakarsh-dt** [comment]
Default is always
`imagePullPolicy: IfNotPresent`

The above referred link points to imagePullSecrets so there seems to be a confusion. Please re-open the issue and clarify if you feel this is indeed an issue.
