### ISSUE TITLE
Bug: Bulk hibernate api is getting timed out as increased timeout is not getting reflected

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5121]
### 📜 Description

Bulk hibernate API is getting timed out after 1 min even after increasing the global_api_timeout in dashboard configMap. A hard reload is required to implement the configMap changes.  

### 👟 Reproduction steps

1. Hibernate 50+ applications in bulk. The api shall timeout after 1 min.
2. Increase global_api_timeout from dashboard CM and deploy.
3. Retry bulk hibernation and still api will get timeout out in 1 min until you do a hard reload.

### 👍 Expected behavior

A hard reload should not be required to reflect the changes. 

### 👎 Actual Behavior

A hard reload needs to be done to implement the dashboard configMap changes.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9810

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5084] Bug: Git Material API getting timed out while saving existing git repository (62.09%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5084] Bug: Git Material API getting timed out while saving existing git repository (62.09%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5084] Bug: Git Material API getting timed out while saving existing git repository (62.09%)
