### ISSUE TITLE
Bug: esc button is malfunctioning 

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5127]
### 📜 Description

It bugs out if you open a CD modal and enter `esc` button for app-1. You will always be redirected to workflow editor of app-1 on pressing `esc` until you refresh.

### Affected areas

Other NON-CRITICAL functionality

### Additional affected areas

Other NON-CRITICAL functionality

### Prod/Non-prod environments?

Prod

### Is User unblocked?

No

### How was the user un-blocked?

PERMANENTLY - By giving a workaround (Within Devtron)

### Impact on Enterprise

User might lose config changes if by mistakenly `esc` is pressed. 

### 👟 Steps to replicate the Issue

1. Open CD pipeline modal in app-1
2. Enter Escape button
3. Now if you go to another application (say app-2) and enter Esc you will be redirected back to app-1.

### 👍 Expected behavior

`esc` should not switch to different page

### 👎 Actual Behavior

`esc` is switching is redirecting back to workflow editor of first application.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9813

**Comment by vivek-devtron** [comment]
Fixed in https://github.com/devtron-labs/dashboard/pull/1760
