### ISSUE TITLE
Bug: oss build was failing 

### ISSUE THREAD

**Issue by ashishdevtron** [devtron-labs/devtron#5167]
### 📜 Description

oss build was failing, due to missing vendor files

### 👟 Reproduction steps

.

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### ☸ Kubernetes version

.

### Cloud provider

<details>
.
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9850

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5127] Bug: esc button is malfunctioning  (60.48%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5127] Bug: esc button is malfunctioning  (60.48%)
