### ISSUE TITLE
Bug: Getting bad request after clicking on approve button for protect approval.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#5171]
### 📜 Description

Getting below error while trying to save the approve button from mail subject for config approval.

<img width="1433" alt="Screenshot 2024-05-27 at 11 47 39 AM" src="https://github.com/devtron-labs/devtron/assets/99399155/d5d5ce78-6410-45a6-b5db-eda51a80741a">

Logs of orchestrator 

{"level":"error","ts":1716793656.4566267,"caller":"drafts/ConfigDraftService.go:267","msg":"user contributed to this draft","draftId":11,"userId":509,"stacktrace":"github.com/devtron-labs/devtron/enterprise/pkg/drafts.(*ConfigDraftServiceImpl).validateDraftAction\n\t/go/src/github.com/devtron-labs/devtron/enterprise/pkg/drafts/ConfigDraftService.go:267\ngithub.com/devtron-labs/devtron/enterprise/pkg/drafts.(*ConfigDraftServiceImpl).ApproveDraft\n\t/go/src/github.com/devtron-labs/devtron/enterprise/pkg/drafts/ConfigDraftService.go:410\ngithub.com/devtron-labs/devtron/enterprise/api/drafts.(*ConfigDraftRestHandlerImpl).CheckAccessAndApproveDraft\n\t/go/src/github.com/devtron-labs/devtron/enterprise/api/drafts/ConfigDraftRestHandler.go:410\ngithub.com/devtron-labs/devtron/api/restHandler.NotificationRestHandlerImpl.ApproveConfigDraftForNotification\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/NotificationRestHandler.go:1180\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/mux.go:179\ngithub.c

 requestMethod: POST, urlPath: /orchestrator/notification/channel/config/approve, queryParams: , updatedBy: , updatedOn: 2024-05-27 07:07:36.444772468 +0000 UTC m=+333898.273793262, apiResponseCode: 400, requestPayload:

### Affected areas

CD

### Additional affected areas

Other CRITICAL functionality

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

TEMPORARILY - By disabling a CRITICAL functionality

### Impact on Enterprise

Currently We need to apply protect configuration for all the prod applications , before that I was testing end to end and getting this error due to this client is not able to use this feature.

### 👟 Steps to replicate the Issue

1. Apply the protect configuration for an env for an Devtron application .
2. Use SES to get the mail for protect configuration.
3. Try to click on approve button from mail.

### 👍 Expected behavior

It should approved .

### 👎 Actual Behavior

Currently It through bad request .

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9853

**Comment by adi6859** [comment]
In this case, when a user requests configuration approval and then tries to approve it themselves, we are displaying an appropriate message from the API. However, this message is not handled properly by the UI. Product intervention is needed to display the correct message in the UI. @uxarya-d @abhibhaw

**Comment by abhibhaw** [comment]
If the API throws an error, by default UI shows a toast with error details I believe cc: @vivek-devtron ?

**Comment by uxarya-d** [comment]
@abhibhaw This is via Email approval flow. Currently I believe "Something went wrong" is generic handling for any error state. While approving from the dashboard we have proper messaging. We'll do the same in email approval flow as well.
