### ISSUE TITLE
Bug: Application Status changes to hibernating even after hibernation fails and vice versa in case of KEDA AutoScaling

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5202]
### 📜 Description

This is the case when Keda autoscaling is enabled. In case of Keda Devtron doesn't support hibernation of application. There is a separate feature request opened to cater the same. But the problem is if we are not hibernating the application we shouldn't change the application status. The same is true if you unhibernate an application. 

### Affected areas

Other CRITICAL functionality

### Additional affected areas

None

### Prod/Non-prod environments?

Prod

### Is User unblocked?

No

### How was the user un-blocked?

None

### Impact on Enterprise

The source of truth is shaken if we show application status as hibernating but if pods of the application are running. The reverse is also true.

### 👟 Steps to replicate the Issue

1. enable keda autoscaling in application.
2. hibernate the application.
3. application will be hibernated but infact pods would still be in running state.

### 👍 Expected behavior

application status should not have changed from healthy to hibernating.

### 👎 Actual Behavior

application status is changing from healthy to hibernating.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9872

**Comment by Ash-exp** [comment]
fixed in https://github.com/devtron-labs/devtron/issues/3791
