### ISSUE TITLE
Introduce Historical Task Definitions at Devtron UI

### ISSUE THREAD

**Issue by caffySingla** [devtron-labs/devtron#525]
# Summary

Task definitions should be visible at UI which should include image and config used for that particular deployment, so that one can revert on any historical deployment whenever required.

# Motivation
We do have use-cases where we sometimes want to revert our app to last deployed config and image, but not every time we do save configs at our local history, thats why want devtron to provide us the same functionality.

# Proposal

According to me, devtron must be logging its task definitions somwhere in EKS cluster, just need to expose the same to UI, like they do for pods.

**Comment by prakarsh-dt** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Devtron-600cf5416a1159001797873d/issues/devtron-labs/devtron/525?planning-poker) with ZenHub @uxarya-d @manish-agrawal-ai @shivani170

**Comment by pghildiyal** [comment]
In the first phase, dump all configuration changes whether deployment template, config map or secret in the dump table.
