### ISSUE TITLE
Feature: NATS Fine Tuning

### ISSUE THREAD

**Issue by komalreddy3** [devtron-labs/devtron#5254]
### 🔖 Feature description

Introduce consumer and stream replicas configuration: In clustered mode, NATS allows for the setup of multiple consumers and stream replicas, enhancing scalability and fault tolerance by distributing workload and data across multiple instances. In non-clustered mode, these configurations ensure reliability and resilience by providing redundancy and failover mechanisms, enabling seamless operation even in the event of node failures or network disruptions.

### 🎤 Pitch / Usecases

NATS ensures robust data persistence for messages, safeguarding their integrity and availability within the platform

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9929

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5253] Feature: Notifier behind nats (64.58%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5253] Feature: Notifier behind nats (64.58%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5253] Feature: Notifier behind nats (64.58%)
