### ISSUE TITLE
Enhancement: Trim spaces from cluster token field

### ISSUE THREAD

**Issue by akshatsinha007** [devtron-labs/devtron#5261]
### 🔖 Feature description

When pasting the cluster bearer token the extra spaces should get trimmed automatically.

### 🎤 Pitch / Usecases

Due to extra spaces it throws an unauthorized error.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9936

**Comment by abhibhaw** [comment]
Fixed with attached PR
