### ISSUE TITLE
Bug: scroller not coming while viewing pod logs in app details page

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5262]
### 📜 Description

Scroller not coming while viewing pod logs in app details page.

### 👟 Reproduction steps

Just go to pod logs in app details page and try scrolling, page will not scroll.

### 👍 Expected behavior

page was expected to scroll while viewing pod logs similar to that of while viewing pod manifest or pod terminal. 

### 👎 Actual Behavior

page doesn't scroll while viewing pod logs in app details page.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9937

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5226] Bug: Getting 403 on app details page while opening pod restart snapshot (69.64%)

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5226] Bug: Getting 403 on app details page while opening pod restart snapshot (69.64%)
