### ISSUE TITLE
Bug: Anomalies in case user permission for combination of `build and deploy` and `admin` in different  envs 

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#5263]
### 📜 Description

let say i have 2 permission group for one application 
1. admin for env 1
2. build and deploy in env 2

<img width="1432" alt="Screenshot 2024-06-06 at 8 20 22 PM" src="https://github.com/devtron-labs/devtron/assets/122791251/48d4b18d-b456-439d-ba6b-e357dbeadb29">
<img width="1432" alt="Screenshot 2024-06-06 at 8 20 30 PM" src="https://github.com/devtron-labs/devtron/assets/122791251/1d8f1755-a0c7-4e11-9cdf-696ca55dc11a">

here when we add both access to user 
he/she able to edit branch i workflow of env2 where only build and deploy permission is given

### Affected areas

RBAC Issues

### Additional affected areas

Security features

### Prod/Non-prod environments?

Prod

### Is User unblocked?

No

### How was the user un-blocked?

None

### Impact on Enterprise

otp

### 👟 Steps to replicate the Issue

give the permission explained above and give the combination of those permissions

### 👍 Expected behavior

must not able to edit branch in env where build and deploy is given

### 👎 Actual Behavior

 able to edit branch in env where build and deploy is given

### ☸ Kubernetes version

any

### Cloud provider

any

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9939

**Comment by gireesh-devtron** [comment]
after discussing with @abhibhaw . we will allow the user to edit the ci-pipeline if he has at least admin access on any on of the environment that exists int the same workflow as ci pipeline
