### ISSUE TITLE
Feature: Required Mandatory Group for deployment approval

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#5288]
### 🔖 Feature description

We required to setup the mandatory group for deployment approval. If the approval was not given from any member from that group, we do not proceed with that image. 

### 🎤 Pitch / Usecases

For us we have the different team and we required approval from each team to proceed with the respective image. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9962

**Comment by sathish-ather** [comment]
Hey @abhibhaw thanks for reverting back and yes, it would be great if we can connect on a quick call and remove the blockers we have currently. we are available on ather-devtron slack channel.

**Comment by sathish-ather** [comment]
hey @abhibhaw as discussed last week, hope we can cover this feature release.! else please let us know the updated ETA to align the team internally.

**Comment by abhibhaw** [comment]
Yes @sathish-ather you can expect this feature release at your environment by end of this week

**Comment by sathish-ather** [comment]
@abhibhaw awesome.! Thanks for the update.

**Comment by abhibhaw** [comment]
Closed with attached PR
