### ISSUE TITLE
Bug: Need to check subPath after cloning the application

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#5289]
### 📜 Description

We are cloning the application and in the source application we were using subPath in the config map, but on cloning the application this subPath gets unchecked for the same config map in the newly cloned application.

### 👟 Reproduction steps

1. Create an application and define a config map with a data volume option using the subPath option.
2. Clone the application using a previously created application.

### 👍 Expected behavior

The cloned application should have enabled subPath in the config map.

### 👎 Actual Behavior

Right now the newly created application unchecks the subPath option from the config map.

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9964

**Comment by gireesh-devtron** [comment]
closing this as it is not reproducible cc: @pawan-59
