### ISSUE TITLE
Bug: OCI helm Repository Addition Issue

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#5290]
### 📜 Description

When adding Helm charts in OCI, extra spaces are added by default in the list of repositories. This prevents saving the configuration until all extra spaces are manually removed.

<img width="1000" alt="Screenshot 2024-06-12 at 1 54 04 PM" src="https://github.com/devtron-labs/devtron/assets/130441461/ce392e0a-8882-48de-8e85-0af3b37a33b4">

After adding a default space, it will be treated as a new Helm chart. Consequently, the user will not be able to add a new Helm chart until the space is removed

<img width="462" alt="Screenshot 2024-06-12 at 3 28 27 PM" src="https://github.com/devtron-labs/devtron/assets/130441461/80cf41ff-6aca-4093-b940-4c0a5bba0064">

### 👟 Reproduction steps

1. Add any Helm chart in OCI.
2. Deploy the chart.
3. Attempt to add another repository.
4. Notice the error indicating that you cannot save the configuration due to extra spaces.

### 👍 Expected behavior

Users should be able to add repositories without extra spaces being added by default, and should be able to save the configuration without manual adjustments.

### 👎 Actual Behavior

NA

### ☸ Kubernetes version

1.28

### Cloud provider

<details>
aws
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9965

**Comment by vikramdevtron** [comment]
duplicate https://github.com/devtron-labs/devtron/issues/5234
