### ISSUE TITLE
Feature: webhook to trigger build pipeline 

### ISSUE THREAD

**Issue by kappertj** [devtron-labs/devtron#5292]
### 🔖 Feature description

I would like to see the ability to trigger a pipeline through a webhook. 

### 🎤 Pitch / Usecases

When you have a branch where you push code through an MR to a protected branch a webhook is triggered to start the pipeline. We use bitbucket cloud and there you have the ability to configure a webhook to also send a message to Slack, the same mechanism you could also use to do a post on devtron's api to start a particular pipeline. 

### 🔄️ Alternative

there is no such option right now, only way is to change the poling interval to 1 minute

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9967

**Comment by abhibhaw** [comment]
@kappertj Why don't you use devtron APIs, that should work same as a webhook trigger

**Comment by abhibhaw** [comment]
I believe this can be achieved by directly calling the devtron APIs, closing this as of now @kappertj feel free to reopen if u need to discuss more on this!!
