### ISSUE TITLE
ECR Support with IAM Roles (Instance / kube2iam / OIDC)

### ISSUE THREAD

**Issue by marcelobartsch** [devtron-labs/devtron#531]
# Summary

on the ECR Repositories, currently is mandatory to have an AWS ACCESS KEY  ID and SECRET ACCESS KEY , but in our environment we don't use 'fixed keys' we use only IAM Roles to grant access, it would be nice to support to use either the instance IAM Role or the service account role (when using IRSA) or simlar

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

**Comment by tarunptala** [comment]
+1
