### ISSUE TITLE
Bug: Deployment History of External Secret Not Displaying in UI

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#5321]
### 📜 Description

There is a bug where the deployment history of external secrets is not displayed in the UI. This issue makes it difficult to track changes in secrets and see if any modifications have been made and deployed. Currently, the deployment history is only visible on the Build and Deploy page at the time of deployment. Once a new deployment occurs, there is no way to check the differences between the current and previous deployments. This lack of visibility hampers our ability to audit and manage secret changes effectively.

**BUILD AND DEPLOY PAGE**
<img width="925" alt="Screenshot 2024-06-17 at 7 01 36 PM" src="https://github.com/devtron-labs/devtron/assets/130441461/51bb253d-4fa3-492f-9828-78ffbbfa5a0b">

**DEPLOYMENT HISTORY**
<img width="1440" alt="Screenshot 2024-06-17 at 7 01 16 PM" src="https://github.com/devtron-labs/devtron/assets/130441461/f9ca17a1-88e1-46eb-ab65-371ce095a4b8">

### 👟 Reproduction steps

Please try to  use a external secret in application 
<img width="1123" alt="Screenshot 2024-06-17 at 7 03 25 PM" src="https://github.com/devtron-labs/devtron/assets/130441461/1f97b6a9-4dbc-496f-b849-07713c35ad60">

### 👍 Expected behavior

NA

### 👎 Actual Behavior

NA

### ☸ Kubernetes version

NA

### Cloud provider

<details>
aws
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9996

**Comment by abhibhaw** [comment]
Fixed with attached PR
