### ISSUE TITLE
Bug: Access Denied (error 404) when we Refresh Restart Workload in AppGroup

### ISSUE THREAD

**Issue by anand-swrp** [devtron-labs/devtron#5338]
### 📜 Description

After Selecting some apps in the App Group when we click on restart workload, we can see the files but the moment you refresh the Page, it shows Access denied & error 404.

### 👟 Reproduction steps

1. Select an App Group.
2. Select the Apps and Click on Restart Workload.
3. Check the details of the Page.
4. Now Refresh the page.
5. The URL remans the same but the page goes blank and shows Access denied.

### 👍 Expected behavior

After Refresh, the Restart Workload page shall remain the same like the URL.

### 👎 Actual Behavior

After Refresh, the Restart Workload page goes blank and shows access denied.

### ☸ Kubernetes version

.

### Cloud provider

<details>

</details>
.

### 🌍 Browser

Chrome

### 🧱 Your Environment

QA

### ✅ Proposed Solution

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10009

**Comment by satyampsoni** [comment]
Closing this as completed!
