### ISSUE TITLE
Support for adding the "Host" entry when deploying Ingress using the operator.

### ISSUE THREAD

**Issue by GreenCappuccino** [devtron-labs/devtron#534]
# Summary

When deploying Devtron with Ingress using the operator, automatically adding the "Host" entry is unsupported. Support for configuring the Ingress host should be added to the operator.

# Motivation

When deploying Devtron using the operator with `ENABLE_INGRESS: "true"`, Ingress is deployed, but with the "Host" entry omitted. It would be convenient to have the operator set this entry automatically, perhaps using the `BASE_URL` specified in the Helm values.

# Proposal

When deploying Ingress, attempt to read `BASE_URL` (from the ConfigMap?), validate it, and use it as the host entry in Ingress.

Alternatively, provide a method to specify a custom Ingress configuration in the values.

**Comment by prakarsh-dt** [comment]
Resolved by https://github.com/devtron-labs/devtron/pull/1321
