### ISSUE TITLE
Feature: Some enhancements for Helm/ No-gitops Devtron Apps

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#5354]
### 📜 Description

There are multiple issues with helm apps, I am writing here with respect of NO_GITOPS, issues mentioned may be existing in GITOPS as well

### 👟 Reproduction steps

- Deploy a helm app which should throw any error on helm upgrade. You can try something like updating immutable matchLables in deployment spec.
- Try templating a helm app with preset values

### 👍 Expected behavior

- Errors in helm upgrade should be visible on UI
- Templating should work fine

### 👎 Actual Behavior

- Errors in helm upgrade are not visible on UI. Not even in deployment history.
- Templating doesn't show most of the resources while using preset values.

### ☸ Kubernetes version

OCI 1.29

### Cloud provider

<details>
Oracle
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10028

**Comment by prakarsh-dt** [comment]
@pawan-mehta-dt Can you please confirm if this still exists?

**Comment by abhibhaw** [comment]
@pawan-mehta-dt Follow up to confirm if this still exists

**Comment by pawan-mehta-dt** [comment]
1st issue is resolved, have opened a separate issue for the 2nd point - https://github.com/devtron-labs/devtron/issues/6000
