### ISSUE TITLE
Bug: PR based build is not showing any commit metadata in UI.

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#5356]
### 📜 Description

We have PR based pipeline , webhook events got successfully delivered , but on Devtron UI we are not seeing any PR information .

<img width="906" alt="Screenshot 2024-06-25 at 2 02 53 PM" src="https://github.com/devtron-labs/devtron/assets/99399155/503dd99e-72c4-4180-95b3-dd3cdcbbfd5f">

### Affected areas

CI

### Additional affected areas

CI

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

None

### Impact on Enterprise

The latest PR metadata is not showing on UI

### 👟 Steps to replicate the Issue

NA

### 👍 Expected behavior

It should show the latest PR metadata

### 👎 Actual Behavior

Sowing no commit

### ☸ Kubernetes version

1.30

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10031

**Comment by Ash-exp** [comment]
Environment specific issue.
