### ISSUE TITLE
Bug: Hide the release note under the "About Devtron" section in Devtron Stack Manager for enterprises.

### ISSUE THREAD

**Issue by YashasviDevtron** [devtron-labs/devtron#5359]
### 📜 Description

The release notes are for the open-source Devtron cluster. They shouldn't be in the Enterprise version.

### 👟 Reproduction steps

1. Go to Devtron Stack Manager.
2. Go to the "About Devtron" section.
3. Click on "Releases" to check the release notes.

### 👍 Expected behavior

It should not have release notes in the Enterprise version.

### 👎 Actual Behavior

The "About Devtron" section in the Enterprise version displays release notes intended for the open-source Devtron cluster.

### ☸ Kubernetes version

1.3

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10035

**Comment by abhibhaw** [comment]
Already fixed
