### ISSUE TITLE
Bug: The cluster and environment filter does not work as intended

### ISSUE THREAD

**Issue by akshatsinha007** [devtron-labs/devtron#5366]
### 📜 Description

When we are applying filter of both cluster and environment then the UI shows all the applications of that cluster instead of environment specific apps of that cluster.

### 👟 Reproduction steps

1.First add a cluster filter.
2.Now add the filter based on environment.

### 👍 Expected behavior

Show the applications of only that cluster  environment which is filtered.

### 👎 Actual Behavior

Shows all the applications of that cluster instead of environment specific apps of the filtered cluster.

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10042

**Comment by satyampsoni** [comment]
How can you apply both the filters at the same time ?

<img width="1378" alt="Screenshot 2024-12-30 at 11 47 27 PM" src="https://github.com/user-attachments/assets/8471c5be-7f97-4dbe-88e8-abc0d85fa6c3" />

**Comment by satyampsoni** [comment]
Closing as the issue has been fixed.
