### ISSUE TITLE
Feature: Differentiate OS and Code Level vulnerabilities on Security dashboard

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#5380]
### 🔖 Feature description

Differentiate OS and Code Level vulnerabilities on Security dashboard

### 🎤 Pitch / Usecases

Trivy CLI gives you differentiated view of OS and Code/Library level vulnerabilities but devtron dashboard combines all of them and show as a single entity of all vulnerabilities together. Separating both will give clarity to Dev and Ops team which vulnerabilities they need to own respectively so that these can be fixed on time.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10058

**Comment by abhibhaw** [comment]
Duplicate of #5302
