### ISSUE TITLE
Feature: Set Advanced(YAML) as default view in deployment template page

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#5388]
### 🔖 Feature description

We need to set the advanced(Yaml) as the default view for the deployment template page. As in our case, we are mostly working with advances configuration

### 🎤 Pitch / Usecases

We need to set the advanced(Yaml) as the default view for the deployment template page. As in our case, we are mostly working with advances configuration

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10067

**Comment by prakarsh-dt** [comment]
This is resolved
