### ISSUE TITLE
Bug: Not able to add cluster via ssh tunneling and via proxy.

### ISSUE THREAD

**Issue by amit24nov2000** [devtron-labs/devtron#5394]
### 📜 Description

1. Add one cluster via proxy and ssh tunneling.

### 👟 Reproduction steps

Add one cluster via proxy and ssh tunneling.

### 👍 Expected behavior

Should get added.

### 👎 Actual Behavior

Not able to add.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10075

**Comment by kartik-579** [comment]
fixed https://github.com/devtron-labs/enterprise-release/pull/1053
