### ISSUE TITLE
feat: Application Permissions not working if no Environment is selected

### ISSUE THREAD

**Issue by akshatsinha007** [devtron-labs/devtron#5400]
### 📜 Description

If an application contains only build pipelines and no environment pipelines or deployment pipelines  we do not allow user build in that application until the access to All Environments is provided to the user.

### 👟 Reproduction steps

*

### 👍 Expected behavior

*

### 👎 Actual Behavior

*

### ☸ Kubernetes version

EKS 1.28

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10084

**Comment by vikramdevtron** [comment]
@akshatsinha007 need some more info, we need some environment or all environment selected while giving permission, without that we can do anything that is expected behaviour.

**Comment by akshatsinha007** [comment]
Same as https://github.com/devtron-labs/devtron/issues/5612
