### ISSUE TITLE
Support for Cloud Native Buildpacks as a workload.

### ISSUE THREAD

**Issue by GreenCappuccino** [devtron-labs/devtron#543]
# Summary

[Cloud Native Buildpacks](https://buildpacks.io/) are one of the standard ways to deploy applications to Platforms as a Service. They're in use by PaaS such as Heroku and Cloud Foundry. Buildpacks are enjoyed by developers because of their ease of use (almost 0 manual configuration).

Adding support for Cloud Native Buildpacks would complement the other workloads that DevTron can deploy.

# Motivation

Buildpacks fulfill the case of simply being to write code without configuration of the underlying infrastructure, especially helpful for [twelve-factor apps](https://12factor.net/). Users looking for simplicity may choose to deploy a Buildpack using DevTron similar to other platforms that provide AppOps such as Heroku or certain Tanzu features.

# Proposal

Create a workflow to deploy apps using Buildpacks. Add relevant templates, CI/CD pipelines.

**Comment by pawan-mehta-dt** [comment]
Support was added in https://github.com/devtron-labs/devtron/pull/2562
