### ISSUE TITLE
Support ingress values for operator deployment to devtron-service.

### ISSUE THREAD

**Issue by ruckc** [devtron-labs/devtron#544]
# Summary

Looking to deploy this into an existing (empty) kubernetes cluster with an ingress to devtron-service (instead of using the LoadBalancer service).  Mainly to make use of ALB with AWS Certificates. 

# Motivation

 Currently there seems to be no way to make the service be a `ClusterIP` and enabling an ingress with custom configuration.

# Proposal

Ideally, expose service/ingress settings via helm values, like standard helm charts, which would allow the operator to consume and mix into the deployments.

**Comment by prakarsh-dt** [comment]
Support was added in https://github.com/devtron-labs/devtron/pull/1321
