### ISSUE TITLE
Bug: Pipelines Pre/Post Task > three dot menu does not close on clicking outside

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#5452]
### 📜 Description

We can’t disable the toggle in pre post CI (remove and move to pre post) while we adding the plugin

### 👟 Reproduction steps

1- Create an app
2- Add any plugin in pre CI
3- Add another plugin in pre CI
4- go first plug in to remove (Note:- do not remove)
5- Now try to work any think on this page 

### 👍 Expected behavior

We can able to hide the toggle in pre post CI (remove and move to pre post) while we adding the plugin

### 👎 Actual Behavior

We can’t disable the toggle in pre post CI (remove and move to pre post) while we adding the plugin

### ☸ Kubernetes version

AKS : 1.26

### Cloud provider

Azure

### 🌍 Browser

Chrome

### 🧱 Your Environment

QA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10128

**Comment by vivek-devtron** [comment]
Fix merge in main
