### ISSUE TITLE
Feature: Sync Environment Configurations

### ISSUE THREAD

**Issue by Abhinav-26** [devtron-labs/devtron#5458]
### 🔖 Feature description

Currently, at Devtron we can sync container images that are deployed across different environments. But if we want to sync the configurations as well along with the container image, that is not done automatically. 

### 🎤 Pitch / Usecases

Use-case: If I want to set an active-active environment where I want to sync images as well as configurations for two environments, it cannot be done automatically as of today. The image of two environments can be synced but configurations need to be checked manually. 

### 🔄️ Alternative

An alternative approach would be to check the configuration diff between the two environments and carry the configurations from the source environment to the target environment manually. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10132

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5423] Feature: Lock configuration at environment scope (63.21%)
