### ISSUE TITLE
Bug: Internal server error page is coming , in lock config if we try to change the key in  base deployment template

### ISSUE THREAD

**Issue by aman10000q** [devtron-labs/devtron#5467]
### 📜 Description

make a lock on root level by just adding $ , then try to change any field , page will break

### 👟 Reproduction steps

make a lock on root level by just adding $ , then try to change any field , page will break

### 👍 Expected behavior

page should not break

### 👎 Actual Behavior

page is breaking 

### ☸ Kubernetes version

e

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

e

### ✅ Proposed Solution

e

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10139

**Comment by vivek-devtron** [comment]
Fix merged in main
