### ISSUE TITLE
Bug: No data in few metrics exposed by orchestrator and git-sensor

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5476]
### 📜 Description

Below mentioned metrics fail to publish any data if `status="Failed"`
`orchestrator metrics` :
i) git_ops_duration_seconds_*
ii) cd_duration_seconds_*
`get-sensor metrics` :
i) git_operation_duration_seconds_*

### 👟 Reproduction steps

Try failing git_ops operation like while committing to git_ops during CD. Then check the metrics whether count in git_ops_duration_seconds_count{status="Failed"} increased or not.

### 👍 Expected behavior

If git_ops operation fails then metrics in {status="Failed"} should have been published.

### 👎 Actual Behavior

no data point in {status="Failed"} even when git_ops operation fails.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10149

**Comment by satyampsoni** [comment]
with reference of this pr #5582  this issue can be closed.
