### ISSUE TITLE
Bug: Unable to delete git repository if workflow not added

### ISSUE THREAD

**Issue by nitish6660** [devtron-labs/devtron#5537]
### 📜 Description

Unable to delete git repository if workflow not added either u creating with multiple git repo or already added and u deleted the workflow.

### 👟 Reproduction steps

- Create an app
- Note - work flow should not be added and git repo should be multiple

### 👍 Expected behavior

If delete git repository for multiple case if workflow not added it should be deleted successfully 

### 👎 Actual Behavior

when we deleting git repository for multiple case if workflow not added it should be deleted successfully 

### ☸ Kubernetes version

AKS 1.26

### Cloud provider

Azure

### 🌍 Browser

Chrome

### 🧱 Your Environment

QA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10202

**Comment by satyampsoni** [comment]
This has been solved, closing it.
