### ISSUE TITLE
Bug: Issue in EA Mode Cluster - error: pg: multiple rows in result set.

### ISSUE THREAD

**Issue by badal773** [devtron-labs/devtron#5547]
### 📜 Description

 Upon installing a fresh EA mode cluster and attempting to deploy Helm apps, several issues have been identified:

  1. Error on Configure Page:
  
            After installing a fresh EA mode cluster and deploying Helm apps, navigating to the configure page results in the following error: pg: multiple rows in result set.
   
       

### 👟 Reproduction steps

1. Install a fresh EA mode cluster.
2. Attempt to deploy Helm apps.
3. Navigate to the configure page.

### 👍 Expected behavior

1. No `pg: multiple rows in result set"` errors should be encountered.
2. Helm apps should be visible without needing to delete the kubelink pod.
<img width="1440" alt="Screenshot 2024-07-24 at 4 33 30 PM" src="https://github.com/user-attachments/assets/501c3505-f5f7-4156-b8cf-96ac6d4c5c06">

3. The app details page should have options to delete or check events.

<img width="1440" alt="Screenshot 2024-07-24 at 4 22 53 PM" src="https://github.com/user-attachments/assets/9482ac49-827a-4684-90f4-89830de503fb">

### 👎 Actual Behavior

1. Encountering a `pg: multiple rows in result set"`  error  in configure page.

```
 {"level":"error","ts":1721816599.6739595,"caller":"appInfo/AppInfoRestHandler.go:183","msg":"service err, GetAppMetaInfo","err":"pg: multiple rows in result set","stacktrace":"github.com/devtron-labs/devtron/api/restHandler/app/appInfo.AppInfoRestHandlerImpl.GetHelmAppMetaInfo\n\t/go/src/github.com/devtron-labs/devtron/api/restHandler/app/appInfo/AppInfoRestHandler.go:183\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2141\ngithub.com/devtron-labs/common-lib/middlewares.Recovery.func1\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/common-lib/middlewares/recovery.go:44\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2141\ngithub.com/devtron-labs/devtron/internal/middleware.PrometheusMiddleware.func1\n\t/go/src/github.com/devtron-labs/devtron/internal/middleware/instrument.go:141\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2141\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/gorilla/mux/mux.go:210\nmain.(*App).Start.(*App).Start.Authorizer.func1.func2\n\t/go/src/github.com/devtron-labs/devtron/vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go:91\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2141\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2943\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2014"}
[Jul 24 2024 15:53:19 GMT+0530] devtron-5748b69f5-vwnw6: {"level":"info","ts":1721816599.674006,"caller":"common/apiError.go:117","msg":"ERROR RES","TYPE":"API-ERROR","RES":500,"ERROR-MSG":[{"code":"000","internalMessage":"[{pg: multiple rows in result set}]","userMessage":"pg: multiple rows in result set"}],"err":null}
```
<img width="1440" alt="Screenshot 2024-07-24 at 3 59 01 PM" src="https://github.com/user-attachments/assets/36b97cd4-8b0a-44b5-a90f-b19c473e1762">

2. Helm apps are not visible until the kubelink pod is deleted.

<img width="1440" alt="Screenshot 2024-07-24 at 4 31 48 PM" src="https://github.com/user-attachments/assets/c78a5a3f-5200-4bca-9c0a-203ae7b014d9">

3. The app details page lacks options to delete or check events.
<img width="1439" alt="Screenshot 2024-07-24 at 4 38 43 PM" src="https://github.com/user-attachments/assets/4ee5e90d-62d2-4e4a-9917-edd4bbd3fd8c">

### ☸ Kubernetes version

1.28

### Cloud provider

<details>
aws
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

prod

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10211

**Comment by mayank-devtron** [comment]
we have only fixed pt1 pg: multiple rows in result set" via https://github.com/devtron-labs/sprint-tasks/issues/671
