### ISSUE TITLE
Possible to use basic authentication?

### ISSUE THREAD

**Issue by Phantom-Intruder** [devtron-labs/devtron#5548]
I was wondering if we could use basic auth to create users & login instead of SSO since we don't want to expose devtron to the internet as it is only going to be used from within our VPC. Without exposing devtron to the internet, SSO is not possible. So I would like to know if we can use a basic username/password which will be used to divide up roles (security won't be a concern since this won't be accessible from outside anyway)...

AB#10212

**Comment by abhibhaw** [comment]
Hey @Phantom-Intruder, No you cannot use basic auth for creating additional users apart from admin user at devtron. You can try something like keyclock(Hosted in your local network) with devtron, that way you may need not to expose devtron to internet for SSO. I haven't tried it personally but I believe this should work in your case

**Comment by Phantom-Intruder** [comment]
Thanks for the info @abhibhaw
