### ISSUE TITLE
Doc: Create a documentation for Pull-images-from-container-repository

### ISSUE THREAD

**Issue by bhushan-nemade-dt** [devtron-labs/devtron#5553]
### 💭 Description

Documentation for Pull-images-from-container-repositories is not present in docs, it needs to be created and added in docs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10216

**Comment by systemsdt** [comment]
Potential duplicates: 
  - [#5555] Doc: Create a documentation for Code-Scan plugin (68.78%)

  - [#5554] Doc: Create a documentation for Copacetic plugin (68.78%)
