### ISSUE TITLE
Bug: [Prod]View all incoming webhook payloads ->URL is being appended multiple times on edit configured icon click .improper handling of navigation events also when you switch between multiple ci trigger modal

### ISSUE THREAD

**Issue by mayank-devtron** [devtron-labs/devtron#5559]
### 📜 Description

[High][Prod]View all incoming webhook payloads ->URL is being appended multiple times on edit configured icon click .improper handling of navigation events also when you switch between multiple ci trigger modal

### 👟 Reproduction steps

[High][Prod]View all incoming webhook payloads ->URL is being appended multiple times on edit configured icon click .improper handling of navigation events also when you switch between multiple ci trigger modal

### 👍 Expected behavior

It should be handled

### 👎 Actual Behavior

Breaking

### ☸ Kubernetes version

azure

### Cloud provider

<details>
azure
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

test

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10222

**Comment by shivani170** [comment]
Merged in https://github.com/devtron-labs/dashboard/pull/2070
