### ISSUE TITLE
Bug: [Prod][UI]Expand incoming payload it is empty 

### ISSUE THREAD

**Issue by mayank-devtron** [devtron-labs/devtron#5561]
### 📜 Description

In case of view incoming payload -> expand-> it is empty

<img width="1438" alt="helloadgin" src="https://github.com/user-attachments/assets/82207ac7-d46b-4cf1-b486-21f2fb3ceed7">

### 👟 Reproduction steps

as mentioned

### 👍 Expected behavior

incoming payload details should be visible

### 👎 Actual Behavior

empty state yet

### ☸ Kubernetes version

azure

### Cloud provider

<details>
azure
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10225

**Comment by satyampsoni** [comment]
Close as this has been resolved!
