### ISSUE TITLE
Feature: Capability to provide custom tag based upon existing image tag and manipulate the same

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5574]
### 🔖 Feature description

This feature request enhances the existing custom image tag capability to add suffix / prefix on existing image tag.

### 🎤 Pitch / Usecases

Im my use case I am adding custom tag for QA / Pre-Prod env. Lets call this tag : `orchestrator-rel`
Now as i proceed into prod I want to modify the tag on existing application and remove `rel`. 
PS : Prod cd pipeline will be part of same workflow as that of QA / Pre-Prod. 

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10232

**Comment by abhibhaw** [comment]
Fixed with PR #5760
