### ISSUE TITLE
Bug: Scoped variable doesn't allow any changes if reference to a deleted env is present 

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#5590]
### 📜 Description

Scoped variable doesn't allow any changes if reference to a deleted env is present 

### 👟 Reproduction steps

1. Add some scoped variables with any scope
2. In any one of the variables add an env scoped value
3. Save the above setup
4. Delete the environment to which the env scoped value was added
5. Try making any changes to any scoped variable

### 👍 Expected behavior

Changes should work as expected

### 👎 Actual Behavior

It blocks all changes until reference to deleted env scoped values are removed

### ☸ Kubernetes version

OKI 1.29

### Cloud provider

<details>
Oracle
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10247

**Comment by kartik-579** [comment]
fixed with
