### ISSUE TITLE
Bug: We are not able to delete the application when cluster is unreachable and Argo application was deleted

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#5593]
### 📜 Description

We have deployed some helm chart using argocd and their , we have deleted its argo application as this was not getting deleted from UI .
Now trying to delete the helm apps it is not getting completed , it try to find the argo application.

<img width="1250" alt="Screenshot 2024-07-30 at 6 04 48 PM" src="https://github.com/user-attachments/assets/ef4a5653-a677-4edc-b777-039a190d04f4">

<img width="893" alt="Screenshot 2024-08-12 at 8 16 52 PM" src="https://github.com/user-attachments/assets/63838fe6-0316-4852-b4e9-cb837b55f119">

In the below screenshot, It shows that the pipeline is already present there but there is not any deployed pipeline in the qa-devtroncd-5
<img width="1021" alt="Screenshot 2024-08-12 at 8 18 18 PM" src="https://github.com/user-attachments/assets/efc61e7e-1e47-4557-b3d3-7130c0ffc539">

### 👟 Reproduction steps

1. Deploy a helm app using argocd
2. Delete the argo application from argocd 
3. try to delete the that helm app from Devtron UI

### 👍 Expected behavior

It should delete helm app as well if argo application is deleted .

### 👎 Actual Behavior

It is not getting deleted 

### ☸ Kubernetes version

1.30

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10251

**Comment by satyampsoni** [comment]
This is similar to #5365, closing!
