### ISSUE TITLE
Bug: lens didn't retry / restart or go in crashloopbackoff when was unable to subscribe with NATS topic

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5595]
### 📜 Description

**error logs :** 

`[Jul 22 2024 22:01:22 GMT+0530] lens-dcd-6d894948f-fwsnx: {"level":"info","ts":1721665882.957072,"caller":"pubsub-lib/PubSubClientService.go:139","msg":"Subscribed to pubsub client","topic":"CD.TRIGGER"}
[Jul 22 2024 22:01:23 GMT+0530] lens-dcd-6d894948f-fwsnx: 2024/07/22 16:31:23 No stream was created already. Need to create one. Stream name: ORCHESTRATOR
[Jul 22 2024 22:01:23 GMT+0530] lens-dcd-6d894948f-fwsnx: 2024/07/22 16:31:23 Error while creating stream.  stream name:  ORCHESTRATOR error:  nats: stream name already in use
[Jul 22 2024 22:01:23 GMT+0530] lens-dcd-6d894948f-fwsnx: {"level":"error","ts":1721665883.9656017,"caller":"pubsub-lib/PubSubClientService.go:305","msg":"unable to retrieve consumer info from NATS-server","stream":"ORCHESTRATOR","consumer":"CD-TRIGGER-DURABLE1","err":"nats: consumer is offline","stacktrace":"github.com/devtron-labs/common-lib/pubsub-lib.PubSubClientServiceImpl.updateConsumer\n\t/go/src/github.com/devtron-labs/lens/vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go:305\ngithub.com/devtron-labs/common-lib/pubsub-lib.PubSubClientServiceImpl.Subscribe\n\t/go/src/github.com/devtron-labs/lens/vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go:161\ngithub.com/devtron-labs/lens/client.NewNatsSubscription\n\t/go/src/github.com/devtron-labs/lens/client/NatsSubscription.go:71\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/lens/wire_gen.go:55\nmain.main\n\t/go/src/github.com/devtron-labs/lens/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
[Jul 22 2024 22:01:24 GMT+0530] lens-dcd-6d894948f-fwsnx: {"level":"error","ts":1721665884.4666336,"caller":"pubsub-lib/PubSubClientService.go:170","msg":"error while subscribing to nats ","stream":"ORCHESTRATOR","topic":"CD.TRIGGER","error":"nats: consumer is offline","stacktrace":"github.com/devtron-labs/common-lib/pubsub-lib.PubSubClientServiceImpl.Subscribe\n\t/go/src/github.com/devtron-labs/lens/vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go:170\ngithub.com/devtron-labs/lens/client.NewNatsSubscription\n\t/go/src/github.com/devtron-labs/lens/client/NatsSubscription.go:71\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/lens/wire_gen.go:55\nmain.main\n\t/go/src/github.com/devtron-labs/lens/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
[Jul 22 2024 22:01:24 GMT+0530] lens-dcd-6d894948f-fwsnx: {"level":"error","ts":1721665884.466705,"caller":"client/NatsSubscription.go:73","msg":"Error while subscribing to pubsub client","topic":"CD.TRIGGER","error":"nats: consumer is offline","stacktrace":"github.com/devtron-labs/lens/client.NewNatsSubscription\n\t/go/src/github.com/devtron-labs/lens/client/NatsSubscription.go:73\nmain.InitializeApp\n\t/go/src/github.com/devtron-labs/lens/wire_gen.go:55\nmain.main\n\t/go/src/github.com/devtron-labs/lens/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
[Jul 22 2024 22:01:24 GMT+0530] lens-dcd-6d894948f-fwsnx: {"level":"info","ts":1721665884.4668856,"caller":"lens/App.go:58","msg":"starting server on ","port":8080}`

### Affected areas

Other CRITICAL functionality

### Additional affected areas

Other CRITICAL functionality

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

TEMPORARILY - By doing some changes from the backend/DB

### Impact on Enterprise

User was not able to see deployment metrics for the past couple of days 

### 👟 Steps to replicate the Issue

1. bounce nats and lens, and make sure lens comes before NATS does.

### 👍 Expected behavior

lens should have been retried subscribing to topic : `CD-TRIGGER-DURABLE-1`

### 👎 Actual Behavior

lens did not retry.

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by prkhrkat** [comment]
https://github.com/devtron-labs/lens/pull/29
