### ISSUE TITLE
Bug: Multi architecture build not building even after setting target platform for arm64 and amd64

### ISSUE THREAD

**Issue by SATYAsasini** [devtron-labs/devtron#5600]
### 📜 Description

- Even after opting for multi arch build , the image built is mono arch

### 👟 Reproduction steps

1. In build configuration, Set target platform for the build to arm64 and amd64
2. Then initiate CI

### 👍 Expected behavior

A multi-arch image should have been built

### 👎 Actual Behavior

Mono arch image is built

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by gireesh-naidu** [comment]
fixed in above linked PR https://github.com/devtron-labs/ci-runner/pull/159
