### ISSUE TITLE
Bug: Build is getting failed but still image is getting pushed

### ISSUE THREAD

**Issue by akshatsinha007** [devtron-labs/devtron#5604]
### 📜 Description

The Docker build is getting failed but still the image is getting tagged, pushed and deployed.
<img width="1189" alt="Screenshot 2024-08-01 at 12 27 06 PM" src="https://github.com/user-attachments/assets/cf2d28e5-7333-4f96-a01d-8f48beba1aae">

### Affected areas

CI

### Additional affected areas

CD

### Prod/Non-prod environments?

Prod

### Is User unblocked?

No

### How was the user un-blocked?

None

### Impact on Enterprise

The build is getting failed but still the image is being pushed to registry and is getting deployed.

### 👟 Steps to replicate the Issue

NA

### 👍 Expected behavior

If the build gets failed then the next stages should be aborted.

### 👎 Actual Behavior

The build is getting failed but still the image is being pushed to registry and is getting deployed.

### ☸ Kubernetes version

1.28.9

### Cloud provider

<details>
AKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by prkhrkat** [comment]
https://github.com/devtron-labs/ci-runner-enterprise/pull/58
