### ISSUE TITLE
Disabling TargetMemoryUtilizationPercentage does not disable memory based autoscaling

### ISSUE THREAD

**Issue by strawhat5** [devtron-labs/devtron#561]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

We tried to disable memory based autoscaling on some of our apps, but even after disabling `TargetMemoryUtilizationPercentage` in Deployment Template, pods are still autoscaling based on memory utilization.

**To Reproduce**

1. Initial state:
```bash
kubectl -n alpha get hpa notification-service-alpha-hpa 
NAME                             REFERENCE                            TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
notification-service-alpha-hpa   Rollout/notification-service-alpha   291%/80%, 30%/90%   1         2         2          28d
```
2. Then I disabled it and deployed the disabled config, then deleted the HPA from kubectl. The state at this time was:
```bash
kubectl -n alpha get hpa notification-service-alpha-hpa 
Error from server (NotFound): horizontalpodautoscalers.autoscaling "notification-service-alpha-hpa" not found
```
The pod count went down to 1 (which is = `replicaCount: 1` ).

3. Then I enabled it from deployment template and redeployed it. Now the state is:
```bash
kubectl -n alpha get hpa notification-service-alpha-hpa 
NAME                             REFERENCE                            TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
notification-service-alpha-hpa   Rollout/notification-service-alpha   245%/80%, 30%/90%   1         2         2          3m56s
```
At the present moment, there are still 2 running pods (HPA still using memory metrics).

**Expected behavior**

When `TargetMemoryUtilizationPercentage` is disabled, it should disable autoscaling based on memory.

**Screenshots**

<img width="283" alt="Screenshot 2021-07-06 at 2 17 37 PM" src="https://user-images.githubusercontent.com/10865861/124710502-81843100-df1a-11eb-8f0a-732579079484.png">
<img width="477" alt="Screenshot 2021-07-06 at 2 17 50 PM" src="https://user-images.githubusercontent.com/10865861/124710507-847f2180-df1a-11eb-9e26-574e46492553.png">

**Comment by prakarsh-dt** [comment]
Removing `TargetMemoryUtilizationPercentage` from the deployment-template won't disable it, it will take the default values from values.yaml, to disable it completely, give "" or "0"
