### ISSUE TITLE
Bug: Non-Super admin users are not able to download file/folder.

### ISSUE THREAD

**Issue by amit24nov2000** [devtron-labs/devtron#5620]
### 📜 Description

 Non-Super admin users are not able to download file/folder.

### 👟 Reproduction steps

1. Create one app.
2. Go to the terminal and try to download the file and folder, but you are not able to download file and folder.

### 👍 Expected behavior

Able to download file/folder.folders

### 👎 Actual Behavior

not able to download file and folder

### ☸ Kubernetes version

1.23

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by gireesh-naidu** [comment]
fixed in above linked PR
