### ISSUE TITLE
Feature: Add Dropdown for externalCiArtifact with Docker Tag Selection

### ISSUE THREAD

**Issue by akshatsinha007** [devtron-labs/devtron#5635]
### 🔖 Feature description

Currently, specifying the externalCiArtifact requires users to manually input the entire Docker image path, such as docker.io/repository/image:tag . This process is prone to human error and can be tedious.

![image](https://github.com/user-attachments/assets/007936b1-71c0-494d-a5e7-11a8de63eaec)

### 🎤 Pitch / Usecases

Introduce a dropdown menu that allows users to select the Docker tag.
Example : docker.io/repository/image:tag:v3.10.1
here just the tag v3.10.1 would be changing so rest part can be kept as a variable  

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by manchal22** [comment]
Hi guys, can we also get a dropdown for imageDigest?
cc: @pawan-mehta-dt

**Comment by abhibhaw** [comment]
As discussed with @pawan-mehta-dt Since we have provided a key to provide image tag instead of full image and it's combination with global fixing value, this is not required as of now. Feel free to reopen this @manchal22 If the requirement still exists
