### ISSUE TITLE
Feature: Need to Update the Config approval mail subject

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#5639]
### 🔖 Feature description

Currently when user get the config approval request mail , In mail object we should not getting any relevant info.

**Config Change approval requested | Application >**

We should include env and app name in mail subject as we do for image approval mail subject .

**Devtron IMAGE PROMOTION Approval Request: env-name app-name**

We can use like this .

**Devtron Config Change Approval Request:  env-name app-name**

### 🎤 Pitch / Usecases

We should include the app name and env name in object as we do in image approval.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with: https://github.com/devtron-labs/devtron-enterprise/pull/2077
