### ISSUE TITLE
Bug:  Not showing any app after selecting cluster in app list page after refresh

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#5643]
### 📜 Description

Currently after selecting the cluster in app list page and refresh we are not showing any app , and another issue environment and cluster filter is not giving right apps .

SS after restart 

<img width="1407" alt="Screenshot 2024-08-08 at 12 41 28 PM" src="https://github.com/user-attachments/assets/bf2b17f0-d0e8-4342-b393-e12ad8d8a010">

SS before restart 

<img width="1410" alt="Screenshot 2024-08-08 at 12 41 54 PM" src="https://github.com/user-attachments/assets/6a24a087-5cce-46fe-a656-d4f1860d7371">

### 👟 Reproduction steps

1. Select any cluster in filter in app list page.
2. refresh the page

### 👍 Expected behavior

It should show the apps after the refresh 

### 👎 Actual Behavior

It is showing no any apps in app list page

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by satyampsoni** [comment]
This seems to be fixed @ajaydevtron, there was also a similar issue raised by Akshat #5365 both seems to solved now.

Closing it.
