### ISSUE TITLE
Feature: Casbin Deny Support Scripts

### ISSUE THREAD

**Issue by Shivam-nagar23** [devtron-labs/devtron#5678]
### 🔖 Feature description

Casbin Deny Support Scripts

### 🎤 Pitch / Usecases

Casbin Deny Support Scripts

### 🔄️ Alternative

Casbin Deny Support Scripts

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
