### ISSUE TITLE
Cluster tokens shouldn't be mandatory for default cluster

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#569]
Cluster tokens are mandatory for default cluster and prometheus can't be updated because of cluster token validations.

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Cluster tokens are mandatory for default cluster and prometheus can't be updated because of cluster token validations.

**To Reproduce**

Occurs in any new devtron installation.

**Expected behavior**

Cluster tokens shouldn't be mandatory for default cluster.

**Current behavior** 

Cluster token is mandatory for default cluster.

**Comment by manish-agrawal-ai** [comment]
fixed
