### ISSUE TITLE
Bug: impossible configure GitOps, Internal error server

### ISSUE THREAD

**Issue by guzmanf** [devtron-labs/devtron#5697]
### 📜 Description

When i try to configure Gitops i got the error Internal error server

### 👟 Reproduction steps

- Install devtron-operator (0.7.1) via helm chart
- log in as admin user
- Go in "Global Configurations" --> "GitOps"
- Compile form (GitHub Organisation Name*, GitHub Username*, Personal Access Token*) => Token has full control
- Click "Save" you will see "Validating repo configuration. Please wait…" and then "Internal error server"

### 👍 Expected behavior

create  test respository

### 👎 Actual Behavior

![image](https://github.com/user-attachments/assets/b945e247-4ea2-4dc7-9e48-53b8a365dd08)

![image](https://github.com/user-attachments/assets/0332482d-9898-4071-9799-b0b1cf717823)

![image](https://github.com/user-attachments/assets/899334b8-222c-49c1-8653-094cdfa30231)

![image](https://github.com/user-attachments/assets/ede28c38-5041-4f27-abce-6dc996def387)

### ☸ Kubernetes version

v1.28.10+rke2r1

### Cloud provider

<details>
VPS Contabo 
</details>

### 🌍 Browser

Something Else

### 🧱 Your Environment

linux Debian 12 and  Brave/Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by badal773** [comment]
Hello @guzmanf ,

Could you please confirm how you installed ArgoCD? Was it done via the UI or using the `helm upgrade` command?

If you used the `helm upgrade` command, did you include the `--reuse-values` flag?

Additionally, could you provide the output of the following commands for troubleshooting:

```
helm get values devtron -n devtroncd
kubectl get po -n devtroncd
```
Does that work for you, or would you like further adjustments?

**Comment by abhibhaw** [comment]
Hey is this resolved @badal773 @guzmanf ?

**Comment by abhibhaw** [comment]
Closing this due to no reply, please feel free to reopen if this still exists @guzmanf
