### ISSUE TITLE
Feature: Comparison of deployment configurations across environments

### ISSUE THREAD

**Issue by RohitRaj011** [devtron-labs/devtron#5703]
### 🔖 Feature description

- Capability to compare CM and Secrets across environments.
- Ability to sort the CM and secrets keys in diff view, for better comparison

### Usecases
- I’m a release manager who has to update the same CM / Secret at multiple environments of the same microservice.
- I’m a developer who has completed the dev testing. I want to figure out what config map / Secret I changed which will be required to be updated at production.

### Problem
- It becomes quite tough to remember what all changed and the chances of missing some changes which were supposed to be updated becomes very obvious.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with https://github.com/devtron-labs/dashboard/pull/1930
