### ISSUE TITLE
Feature: Allow wild cards condition in filter condition

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#5705]
### 🔖 Feature description

Allow wild cards condition in filter condition

### 🎤 Pitch / Usecases

I want to ensure that production deployments are only allowed if the branch is master. There are many application which are deployed in production environment and allowing wild cards will help us to do it easily as we don't have to add multiple condition for each application. 
*Note- Multiple CD pipelines are attached parallelly
ie gitCommitDetails['*'].branch=='master'

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
@ashokdevtron Please close this issue when we have these filter conditions added in our doc

**Comment by ashokdevtron** [comment]
> @ashokdevtron Please close this issue when we have these filter conditions added in our doc
Sure, I have raised the doc PR: https://github.com/devtron-labs/devtron/pull/5850
