### ISSUE TITLE
Feature: Release Channels

### ISSUE THREAD

**Issue by abhibhaw** [devtron-labs/devtron#5706]
### 🔖 Feature description

User wants to group their customers, such that it’s easier for them to decide when to release the version upgrade to that customer

### 🎤 Pitch / Usecases

A new entity named release channels will be introduced as part of the Software Distribution Hub. A release channel is a group of installations (and not to mention installations are a group of environments). 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shivam-nagar23** [comment]
Closed in this https://github.com/devtron-labs/devtron/pull/5757

**Comment by Shivam-nagar23** [comment]
https://github.com/devtron-labs/devtron-enterprise/pull/1727
