### ISSUE TITLE
Feature: Tech debt delete Component replace from common

### ISSUE THREAD

**Issue by shivani170** [devtron-labs/devtron#5716]
### 🔖 Feature description

Delete Component replace from common

### 🎤 Pitch / Usecases

.

### 🔄️ Alternative

.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with https://github.com/devtron-labs/dashboard/pull/1962
