### ISSUE TITLE
Feature: link external helm release to CD Pipeline 

### ISSUE THREAD

**Issue by iamayushm** [devtron-labs/devtron#5717]
### 🔖 Feature description

refactoring needed in oss for linking external helm release to cd pipeline

### 🎤 Pitch / Usecases

deploymentAppName should be derived from pipeline repository instead of directly using <app-name>-<env-name>

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
