### ISSUE TITLE
Feature: history UI revamp to re-align trigger details and make the navigation tabs sticky

### ISSUE THREAD

**Issue by AbhishekA1509** [devtron-labs/devtron#5729]
### 🔖 Feature description

history UI revamp to re-align trigger details and make the navigation tabs sticky.

### 🎤 Pitch / Usecases

To improve UI/UX in history pages like deployment/build/job/release history.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
