### ISSUE TITLE
Feature: Need a refresh button on app details page to check the status of pod at regular interval.

### ISSUE THREAD

**Issue by YashasviDevtron** [devtron-labs/devtron#5749]
### 🔖 Feature description

Need a refresh button on the app details page with a dropdown for selecting an automatic refresh interval. This will allow    users to choose manually refresh the pod status with a button click or select an automatic refresh interval from the dropdown menu to update the pod status at user-defined intervals without reloading the entire page.

### 🎤 Pitch / Usecases

Refresh button will allow users to quickly get the latest status updates, making it easier to identify and address any issues or confirm the successful deployment of pods.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Is this still required after we have implemented caching on app details, can you please confirm @YashasviDevtron

**Comment by YashasviDevtron** [comment]
Yes, it is still required.

**Comment by abhibhaw** [comment]
This has been fixed
