### ISSUE TITLE
Bug:  the error is getting displayed on cluster page instead of resource browser page

### ISSUE THREAD

**Issue by YashasviDevtron** [devtron-labs/devtron#5786]
### 📜 Description

When navigating to the Resource Browser where the API fetches the status of all clusters, and while the Resource Browser is still loading or fetching data, selecting and entering into one of the clusters can cause an error message to be displayed on the cluster page. This occurs even if the error is related to the status fetching process of the Resource Browser, not the cluster page.
<img width="1376" alt="This took longer than expected error" src="https://github.com/user-attachments/assets/99168104-dd6d-464c-88f4-1ac2ae480c60">

### 👟 Reproduction steps

1. Navigate to the Resource Browser where the API is fetching the status of all clusters.
2. While the Resource Browser is still loading or fetching data, select and enter into one of the clusters.
3. Simulate an error during the status fetching process.
4. Observe that the error message is displayed on the cluster page you are currently viewing, not just in the Resource Browser.

### 👍 Expected behavior

The error should be displayed on resouce browser page.

### 👎 Actual Behavior

The error is getting displayed on another page like, cluster page.

### ☸ Kubernetes version

EKS 

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
