### ISSUE TITLE
Bug: Persist the App Status, Project, and Environment settings when the user changes tabs.

### ISSUE THREAD

**Issue by vishu247** [devtron-labs/devtron#5807]
### 📜 Description

**Issue:** When switching from "helm" to "devtronApp," the environment filter does not persist, as shown in the screenshot below and it is same for Project and App Status filter also

### 👟 Reproduction steps

**Initial Stage:** When I apply the environment filter, the filter settings should be correctly reflected and applied to the current view.
<img width="1221" alt="Screenshot 2024-09-05 at 1 58 10 PM" src="https://github.com/user-attachments/assets/2dbb2146-6e43-4f64-a517-ba3b497754be">

**Issue:** When switching from "helm" to "devtronApp," the environment filter does not persist, as shown in the screenshot below and it is same for Project and App Status filter also
<img width="1316" alt="Screenshot 2024-09-05 at 1 59 24 PM" src="https://github.com/user-attachments/assets/bcb52505-834c-4e79-921b-f08734fee867">

### 👍 Expected behavior

**Expected Behavior:** The environment filter and other filter should persist and be applied consistently across all sections and tabs.

### 👎 Actual Behavior

**Actual Behavior:** The environment filter and other filter does not persist and be applied consistently across all sections and tabs.

### ☸ Kubernetes version

EKS 1.28v

### Cloud provider

<details>
         AZURE
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
