### ISSUE TITLE
Feature: Allow to change the  default selection type of deployment

### ISSUE THREAD

**Issue by YashasviDevtron** [devtron-labs/devtron#5811]
### 🔖 Feature description

Allow user to  change the default selection   of deployment from helm to argocd

### 🎤 Pitch / Usecases

Change the default deployment selection type  from Helm to ArgoCD to prevent accidental deployments with Helm and ensure consistency with preferred deployment workflows.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
We do have this option with which user can configure default deployment type, gitops / helm will that satisfy your requirement?

**Comment by tayalrishabh96** [comment]
> We do have this option with which user can configure default deployment type, gitops / helm will that satisfy your requirement?

@abhibhaw Although we wanted both to be present and select argocd as default deployment type when this issue was raised but for now we have disabled this feature to show both options in deployment type as we don't have any specific use-case. Hence for now we can close this issue.
