### ISSUE TITLE
No option for SES configuration/email like slack configuration when setting up notifications

### ISSUE THREAD

**Issue by kartik-579** [devtron-labs/devtron#584]
# Summary

There's no option for email/SES configuration when adding notifications, but there is one for slack configuration which makes it a bit confusing on how to add emails(currently we have to type emails, and it takes a while to figure that out) . If there could be same option for emails like slack configuration, it would make user interaction better.

<img width="1440" alt="Screenshot 2021-07-16 at 12 48 17 PM" src="https://user-images.githubusercontent.com/84493919/125909264-e42e0814-5585-48a1-b979-6380ebb32e24.png">

AB#369

**Comment by pawan-mehta-dt** [comment]
Added support in https://github.com/devtron-labs/notifier/pull/7
