### ISSUE TITLE
Bug: Gitops Re-authentication issue

### ISSUE THREAD

**Issue by akshatsinha007** [devtron-labs/devtron#5886]
### 📜 Description

Gitops config gettin saved but have to re save them to use them

### 👟 Reproduction steps

Save GitOps Config
Try Deploying any chart or app

### 👍 Expected behavior

App getting deployed successfully

### 👎 Actual Behavior

Throws unauthenticated error, have to resave the gitops creds then it works

### ☸ Kubernetes version

1.30

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ash-exp** [comment]
Fixed in PR https://github.com/devtron-labs/devtron/pull/5891
