### ISSUE TITLE
Feature:  Custom role for application's terminal access

### ISSUE THREAD

**Issue by YashasviDevtron** [devtron-labs/devtron#5897]
### 🔖 Feature description

Currently terminal role is tied up with admin, manager and superadmin roles, user needs flexibility to give terminal access to certain users and not to all users

### 🎤 Pitch / Usecases

Clients need to provide terminal access to developers solely for the dev environments while restricting access to other environments and their applications.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fuxed with #5991
