### ISSUE TITLE
Bug: Raw sql queries need to include params to avoid sql injection

### ISSUE THREAD

**Issue by kartik-579** [devtron-labs/devtron#5924]
### 📜 Description

Some of the raw queries directly use param with string append and need to make them passed through params to avoid sql injection.

### 👟 Reproduction steps

NA

### 👍 Expected behavior

Sql injection should not be possible

### 👎 Actual Behavior

sql injection is possible in some cases

### ☸ Kubernetes version

1.24

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
