### ISSUE TITLE
Feature: enhancements around vulnerability scanning notifications  

### ISSUE THREAD

**Issue by tayalrishabh96** [devtron-labs/devtron#5928]
### 🔖 Feature description

- Capability to trigger notifications on CI completion if certain severity vulnerabilities are found based upon env id / name.
- Add capability for future CI pipelines as well for a given env.
As of now i need to specify individual CI pipeline ids in order to configure vulnerability notifications. 

### 🎤 Pitch / Usecases

This feature request basically optimises the vulnerability notification configuration. 
Consider a scenario where I have 100 applications deployed in an environment "preprod". I want to configure vulnerability notifications for CI across all 100 CIs configured. According to current implementation I'll need to provide 100 CI pipeline ids to configure notification across all. Instead there should have been an option to configure notification on CI based upon env name.

### 🔄️ Alternative

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
