### ISSUE TITLE
Feature: Remove CVE from image-scanner logs

### ISSUE THREAD

**Issue by Neha130** [devtron-labs/devtron#5936]
### 🔖 Feature description

The current implementation of the image-scanner logs includes CVE entries that are cluttering the logs and making it difficult to extract meaningful information. We propose a modification to exclude CVE entries from the logs to enhance clarity and usability.

### 🎤 Pitch / Usecases

Improve Log Clarity by Excluding CVE Entries

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Neha130** [comment]
@RajeevRanjan27 This is a simple feature request to refactor image scanner logging by not printing CVEs while image scan is happening in any application. 
How can you visualise this ? -> 
- enable image scan
- trigger CI
- View image scanner's live logs and check for CVEs getting printed in logs

Now we don't want those CVEs to be printed in Image Scanner logs as it gets printed in a single line which is extensively big in certain scenarios if number of vulnerabilities are quite high in any application. This makes it extremely difficult for us to debug issues from logs. Another issue is that fluent bit which is a log shipper component crashes multiple times across multiple enterprises while parsing image scanner logs.

Please mention any flag you were using during the use of this feature... -> NA
ou got those logs during the both versions (if yes please add these details)? -> Yes

**Comment by RajeevRanjan27** [comment]
thanks for the info.. looking into it.

**Comment by abhibhaw** [comment]
Fixed with attached PR
