### ISSUE TITLE
Feature: Specific approver for configs also like what is there in Deployment.

### ISSUE THREAD

**Issue by kirandevtn** [devtron-labs/devtron#5959]
### 🔖 Feature description

Need a specific approver mechanism in config approval similer to what is there in deployment.

### 🎤 Pitch / Usecases

Same as what is there in deployment specific approver

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Duplicate of #5782
