### ISSUE TITLE
Feature: Config diff for custom charts.

### ISSUE THREAD

**Issue by kirandevtn** [devtron-labs/devtron#5960]
### 🔖 Feature description

Want a config diff view for custom charts also during deployment.

### 🎤 Pitch / Usecases

Someone might want to use his own chart instead of what is already present.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by prakash100198** [comment]
fixed in this :- https://github.com/devtron-labs/devtron/pull/5837
