### ISSUE TITLE
Lock configurations based on Application labels

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#599]
# Summary

Some organizations have aberration giving full control to all the Developers (admin access in Devtron) on a critical production app. While restricting Developers' access to anything less than Admin will disable their ability to create new apps on Devtron.

# Motivation

After analyzing my experience with multiple organizations using Devtron and taking feedback from the superadmins (Generally Infra/DevOps Team Leads) I found out that they are uncomfortable giving admin access to the Developers stating the following reasons:
- They need control on how much resources are being allocated to the containers.
- They need control on LoadBalancer creation (service.type LoadBalancer) and Ingress configs.
- They need control on all configurations once the app has been productionized.

# Proposal

Introducing some reserved Application Labels as below will solve the purpose:

## Lock
After the app has been productionized, the superadmins can mark the app as `Locked`. No configurations can be changed once the app has been labelled `Locked`. Only superadmins can remove this label. The admins can still Trigger the pipelines.

## Infra Lock
Infra/DevOps Team can review the configurations and label the application as `Infra Locked` after setting up the resources, Service Type and Ingress configs, and those sections will be locked for everyone once `Infra lock` label is applied. Only superadmins can remove this label.

This feature can be an extension of #580 

AB#370

**Comment by abhibhaw** [comment]
Completed with [Protect Configuration](https://docs.devtron.ai/usage/applications/creating-application/config-approval)
