### ISSUE TITLE
Build history & Deployment history > Start time and End time showing in 24hrs + am/pm. Needs to be 12hrs + am/pm

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#60]
Deployment history list items > Tooltips do not show on all items (Should be shown for all items on hover)

<img width="1155" alt="Screenshot 2020-11-20 at 6 16 42 PM" src="https://user-images.githubusercontent.com/73632042/99801787-9911d380-2b5c-11eb-8146-4abe5f6bbaaf.png">

**Comment by nishant-d** [comment]
Username is trimmed

**Comment by uxarya-d** [comment]
Deployment history list items > Tooltips do not show on all items (Should be shown for all items on hover)

**Comment by uxarya-d** [comment]
> Username is trimmed

We'll let the user email to be cropped. Complete details will be visible in a tooltip on hover.
