### ISSUE TITLE
Feature: Segregate PROD and Non-PROD clusters

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#6008]
### 🔖 Feature description

Segregate and prominently mark PROD and Non-PROD clusters. (Any cluster with at least 1 environment marked as PROD should be marked as a PROD cluster)

- [ ] Give a toast notification / or a confirmation prompt if a user selects a PROD cluster in Resource browser with a caution toast like "You have selected a PROD cluster". (Should be configurable using a CM variable FEATURE_TRIGGER_TOAST_NOTIFICATION_IF_PROD_CLUSTER: true )
- [ ] Prominently display `PRODUCTION` on the top if a Production cluster is selected in Resource browser.

  
<img width="1485" alt="Screenshot 2024-10-21 at 5 48 44 PM" src="https://github.com/user-attachments/assets/6d0f4889-e134-44ed-ad08-6aa01d6e443c">

### 🎤 Pitch / Usecases

Users add both PRODUCTION as well as NON PRODUCTION clusters in Devtron. Sometimes, the names can be confusing and user with elevated access may edit manifests in production cluster instead of non-prod. To prevent this, PRODUCTION clusters should be prominently marked as PRODUCTION when in resource browser.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
This is fixed
