### ISSUE TITLE
Need an option to remove git materials.

### ISSUE THREAD

**Issue by sankalpwako** [devtron-labs/devtron#603]
In app configuration, we have a option to add git materials, but not delete them.

This causes a issue where we have multiple repos, and due to removing dependency on one, we can't remove it from the list of git materials. We need to create a new application for this to reflect correctly.

Adding a delete button, which removes the git repos in the materials added and the workflow, will reduce the time needed to keep the application clean.

**Comment by prakarsh-dt** [comment]
This is now resolved
