### ISSUE TITLE
Feature: Disable the individual permissions assignment section for non-super admin users

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#6036]
### 🔖 Feature description

In certain organizations, it is necessary to restrict access to the individual permissions assignment section for non-super admin roles, such as Engineering Managers (EM) and Team Leads (TL). This restriction prevents these roles from assigning permissions directly to individual developers. Instead, they are encouraged to use permission groups for managing access. By enforcing this approach, permissions can be assigned in a more controlled, scalable, and consistent manner across teams, reducing the risk of unauthorized access or inconsistent permission assignments. Permission groups allow for streamlined management, ensuring that only super admins have the ability to assign individual permissions outside of these predefined groups.

<img width="1369" alt="Screenshot 2024-10-28 at 1 44 28 PM" src="https://github.com/user-attachments/assets/aa317c11-faf2-4ced-90d0-709c49980406">

### 🎤 Pitch / Usecases

NA

### 🔄️ Alternative

````


````

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Fixed with attached PR
