### ISSUE TITLE
Casbin dependency update

### ISSUE THREAD

**Issue by kilosonc** [devtron-labs/devtron#605]
# Summary

I found you guys still using casbin v1, but it no longer supported any more, so I ask updating casbin to v2.

# Motivation

https://github.com/devtron-labs/devtron/issues/596
https://github.com/devtron-labs/devtron/pull/598
https://github.com/casbin/casbin/issues/845
We could not optimise for you.

# Proposal

I'm here to ask do you want to update casbin to newest version?

AB#393

**Comment by vikramdevtron** [comment]
sure  @closetool  i'll try to update it to v2 and re check the listing performance.

**Comment by hsluoyz** [comment]
Hi @vikramdevtron any update?
