### ISSUE TITLE
feat: add support for managing label permissions based on a predefined list of authorized users

### ISSUE THREAD

**Issue by satyampsoni** [devtron-labs/devtron#6147]
### 📜 Description

The github actions `Devtron-auto-labeller` fails due to permission issue.

### 👟 Reproduction steps

NA

### 👍 Expected behavior

NA

### 👎 Actual Behavior

NA

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment]
Closed with #6164
