### ISSUE TITLE
How to remove a cluster from Global configurations/Clusters and Environments

### ISSUE THREAD

**Issue by cheoalfredo** [devtron-labs/devtron#622]
I've been trying to find out how to remove a cluster from the global configuration and no luck so far, is it that complicated ?

**Comment by nishant-d** [comment]
As of now cluster can't be deleted from UI. However if you want you can delete the cluster by following steps

1. delete all cd pipelines  for that cluster;
2. delete all the helm charts deployed on the cluster through devtron UI
3. mark environment deleted  from postgres ```update environment set active=false where  id in  (select e.id from environment e  inner join cluster c on cluster_id=c.id where cluster_name ='YOUR_CLUSTER_NAME');
```  
4. mark cluster deleted from postgres ```update cluster set sctive=false where cluster_name ='YOUR_CLUSTER_NAME'```

you can get postgres password by  ``` kubectl  get secret postgresql-postgresql -n devtroncd   -o jsonpath='{.data.postgresql-password}'|  base64 -d ```

**Comment by prakarsh-dt** [comment]
Deletion is now supported from the UI
