### ISSUE TITLE
Bug: CD Trigger plugin is not working

### ISSUE THREAD

**Issue by kamal-devtron** [devtron-labs/devtron#6234]
### 📜 Description

CD Trigger plugin is not working

### 👟 Reproduction steps

1.Add CD trigger plugin v1.20
2.Add configuration which will trigger deploy of another application 

### 👍 Expected behavior

It should trigger the given application

### 👎 Actual Behavior

It is not triggering the application and pipeline is failing.

### ☸ Kubernetes version

1.30

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by satyampsoni** [comment]
Closing this as completed!
