### ISSUE TITLE
Not able to change charts once deployed with different chart.

### ISSUE THREAD

**Issue by pawan-59** [devtron-labs/devtron#642]
* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

I deployed a chart of generic helm chart after it becomes healthy i wanted to change the chart of same deployment-name with respective chart value but it throws error and not able to deploy.

**To Reproduce**

1. Deploy a chart.
2. Now go to configure of same deployment and change the chart with respective values
3. Try to deploy.

**Expected behavior**

Chart should deploy with changed chart.

**Current behavior** 

Not able to deploy updated chart. It throws error here

**Screenshots**
First deployed this chart:-
<img width="1376" alt="Screenshot 2021-08-12 at 1 48 44 PM" src="https://user-images.githubusercontent.com/85476803/129176087-63891820-477e-4daa-83c6-3eada9d434c4.png">

Then changed the chart and respective values:-
<img width="1358" alt="Screenshot 2021-08-12 at 1 51 12 PM" src="https://user-images.githubusercontent.com/85476803/129176387-34d015d3-9805-4ed2-9959-93f506455116.png">

Now when I tried to deploy the chart got error:-
<img width="1348" alt="Screenshot 2021-08-12 at 1 51 39 PM" src="https://user-images.githubusercontent.com/85476803/129176735-b27eee90-5a0e-4400-a7d4-1f3075080e8a.png">

**Comment by vikramdevtron** [comment]
fixed and released with PR https://github.com/devtron-labs/devtron/pull/697, timeout increased for deployment.

**Comment by vikramdevtron** [comment]
ACD patch context was failed, will be fixed in new PR.
