### ISSUE TITLE
Hibernate filter not available

### ISSUE THREAD

**Issue by Abhinav-26** [devtron-labs/devtron#647]
# Summary

In the application tab, I am not able to sort my applications which are on hibernating state. A filter can be added for applications which are on hibernating state.

# Motivation

<img width="1440" alt="Screenshot 2021-08-16 at 1 27 21 PM" src="https://user-images.githubusercontent.com/48083659/129531094-e70f5307-f46d-4ee8-b263-671630bdac71.png">

# Proposal

A filter needs to be added in Status dropdown in application tab.

**Comment by prakarsh-dt** [comment]
Status filters are removed now
