### ISSUE TITLE
Gitops configuration validation 

### ISSUE THREAD

**Issue by kartik-579** [devtron-labs/devtron#653]
# Description

In the current support for Gitops configuration, the validation for the same is not implemented when it is being provided by the user. Only when an app is created/deployed, the Gitops account is accessed and at this stage the user finds out whether the configuration is correct or not.

# Proposal

To add validation at the step when a configuration is saved/updated. This will make the user alert of the mistake early-on and will ensure smoother deployment experience.

**Comment by nishant-d** [comment]
gitops validation/dry run steps

1. repo create 
2. readme push 
3. clone  
4. push  
5. commit on rest
