### ISSUE TITLE
Installation from charts get stuck and duplicated when deployed multiple times

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#679]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

When you deploy a chart multiple times after deleting again and again, one of the deployments gets stuck and it isn't deleted from argocd side so you see multiple deployments of the same and isn't able to delete from the UI too.
P.S - You don't even see that app in postgres database

**To Reproduce**

1. Deploy an app from chart and delete it
2. Repeat step 1 but do not give much time in between
3. In 4-5 continous deployments, you will see the results

**Expected behavior**

There should be 1 deployed app of the same which was deployed from chart

**Current behavior** 

We see it multiple times and even then not able to delete it

**Screenshots**

![deployed](https://user-images.githubusercontent.com/39653409/131259069-f6427a4d-2a9b-4ec4-bfff-29749531fbb9.png)

![delete-issue](https://user-images.githubusercontent.com/39653409/131259073-3d495f98-dadc-4cac-925c-8c61901c46b2.png)

**Comment by vikramdevtron** [comment]
fixed and released with PR https://github.com/devtron-labs/devtron/pull/697, timeout increased for deployment.
