### ISSUE TITLE
Browser asks for a prompt to save username/password on many places. 

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#680]
**Browser should not ask to save username/password in the below sections in Global Configurations:**

Gitops
Git Accounts
Docker Registries
Chart Repositories

After fix needs to be verified for different browsers: Chrome, Firefox, Safari.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

**Comment by prakarsh-dt** [comment]
@vivek-devtron Can you please confirm if this was done so that we can close this issue.

**Comment by abhibhaw** [comment]
Unable to reproduce this as of today, I'm assuming this is fixed, please feel free to reopen if not
