### ISSUE TITLE
Feature: Move chart versions to tag based release model

### ISSUE THREAD

**Issue by strawhat5** [devtron-labs/devtron#718]
# Summary

Right now devtron chart versions are maintained in separate folders, which is a crude way of organizing it. It is very cumbersome to maintain them and has many limitations when it comes to releasing and upgrading to new versions.

# Motivation

Lots of helm chart repos follow this model, for example: https://github.com/kubernetes/ingress-nginx/tags

# Proposal

I am proposing to move all the charts to a git `tag` based release model. This will fasten up the process of new chart releases, as well as make it that much smoother for apps to upgrade to new releases. We will follow the `semver` release pattern for major and minor releases.

AB#409

**Comment by prakarsh-dt** [comment]
Helm chart repos may become single point of failure in case they are down hence not prioritized.
