### ISSUE TITLE
Allow managers to give permission to any users even they are added by other managers.

### ISSUE THREAD

**Issue by vikramdevtron** [devtron-labs/devtron#754]
# Summary

Allow managers to give permission to any users even they are added by other managers. 
Manager won't give permission today if user has already access for environment which he has not part of.

# Motivation

Restriction need to remove for managers.

# Proposal

Re-visit the user access module.

AB#50

**Comment by ankit-ls** [comment]
@vikramdevtron Eagerly waiting for this release. Please let us know the expected release date for this. 🚀 

cc: @pghildiyal @nishant-d

**Comment by prakarsh-dt** [comment]
@ankit-ls This requires a major change in how RBAC policies are implemented at Devtron and will require an extensive regression testing, we are picking this ticket in next sprint and it is expected to last 2 sprints. So you can expect this to get released by 17 August, 2022. 

However, I will follow up with you for a beta release of this feature before that if possible.

**Comment by ankit-ls** [comment]
> However, I will follow up with you for a beta release of this feature before that if possible.

@prakarsh-dt Thanks for the update! A beta release would be super helpful. Since this has now become a daily issue to grant access control, and everytime a superadmin has to step in to resolve this, which is not scalable.

**Comment by deepak-devtron** [comment]
Some Basic Test Scenarios:
1. Verify any Manager is not able to view the List of projects of his user for which he haven't permit
2. Verify Manger is able to update(Add/Delete) the only groups for which he have access
3. Verify  Manager is able to update permissions of  his permitted Projects for any user
