### ISSUE TITLE
Deployment template values validation

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#759]
# Summary

Deployment template values validation

# Motivation

Some values in deployment-template if entered wrong make the rollout fail without giving proper error/reason.

# Proposal

Validations for fields like:
- resources
- limits >= requests

**Comment by aviralsrivastava01** [comment]
@prakarsh-dt  Sir please confirm, We have to check limits >= requests in each case or only in case of autoscaling enabled is true?
