### ISSUE TITLE
ECR repository is not created on change of docker registry

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#763]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Description**

When we build and push any image from Devtron to ECR, it creates the repository at ECR side if it doesn't already exist but only if we select ECR as the docker registry during first save of docker build config but if we use any other docker registry at first save and then update it with ECR for further builds, it doesn't create the repository if it doesn't already exist.

**To Reproduce**

1. Create an app and use any registry other than ECR
2. Save the build config and trigger pipeline
3. Now change docker registry to ECR in build config and update
4. Trigger pipeline again

**Expected behavior**

If the repo isn't created at ECR side, it should create the repo with the given name and push successfully  as it happens when we select ECR during app creation

**Current behavior** 

The build fails because push didn't succeed to ECR as repository doesn't exist at ECR side

**Comment by kartik-579** [comment]
While reproducing the bug, found another extension of the same bug that even if ECR is selected in the initial docke build config, it will create a repository for the first time. But if the repo is changed to an uncreated repo, the same bug occurs, i.e. it does not create a repository at ECR.
