### ISSUE TITLE
Embedding DevtronCD UI in an app

### ISSUE THREAD

**Issue by narioinc** [devtron-labs/devtron#767]
# Summary

Is it possible to embed DevtronCD securely within another app (possibly via iframe)

# Motivation

We are building an internal tool wherein we are combining several Kubernetes observability and app management apps into one UI. Currently when i tried adding devtroncd UI into an iframe, nothing loads up. I didnt see any content policy or x-frame options set so was curious if i missed something and if devtron already allows embedding into other apps.

# Proposal

How do you think this should be implemented?

**Comment by prakarsh-dt** [comment]
Duplicate of #578
