### ISSUE TITLE
panic: ERROR #42P01 relation "gitops_config" does not exist

### ISSUE THREAD

**Issue by clcc2019** [devtron-labs/devtron#839]
{"level":"info","ts":1636013215.6816206,"caller":"models/connection.go:61","msg":"connected with db","db":{"Addr":"postgresql-postgresql.devtroncd","Port":"5432","User":"postgres","Password":"eWx0bHFIbG44K0xxTDE5cU9GVTIvSTZvUUFjPQo","Database":"orchestrator","ApplicationName":"orchestrator","LogQuery":true}}
time="2021-11-04T08:06:55Z" level=info msg="Starting configmap/secret informers"
time="2021-11-04T08:06:55Z" level=info msg="Configmap/secret informer synced"
2021/11/04 08:06:55 ERROR #42P01 relation "gitops_config" does not exist
panic: ERROR #42P01 relation "gitops_config" does not exist

goroutine 1 [running]:
log.Panic(0xc00093ff68, 0x1, 0x1)
	/usr/local/go/src/log/log.go:351 +0xae
main.main()
	/go/src/github.com/devtron-labs/devtron/main.go:32 +0x76

**Comment by prakarsh-dt** [comment]
@clcc2019 Can you please give us more information by following the Issue template?

**Comment by pavel-antropov-epam** [comment]
What was the cause?

**Comment by scheung38** [comment]
Also seeing the same here

![Screenshot 2022-08-04 at 13 40 33](https://user-images.githubusercontent.com/1273014/182849348-1a1349f5-f2f5-4c2e-a6a8-dab84525324d.png)
