### ISSUE TITLE
Manage users, projects, environments and Preview Environments

### ISSUE THREAD

**Issue by sidkris77** [devtron-labs/devtron#844]
# Summary

The docs do not explain how you go about:

- Updating a User Password
- Delete a Project
- Delete an Environment
- Create on demand Preview Environments for Integration Tests

# Motivation

We are currently evaluating Jenkins-X & Devtron for a major AI SaaS Product and at the moment Devtron ticks almost all the boxes for us. However, the few things mentioned above are not clear.

Short lived Preview Environments with multiple services like other dependant microservices and dependancies like databases, kafka are central to our pipelines.

# Proposal

Please update the documentation explaining these. Thanks.

**Comment by pghildiyal** [comment]
Hi @sidkris77 
Thanks for reaching out. I am excited that you are comparing us against Jenkins-X and liking us.

We have something similar in the pipeline, would love to learn more about your perspective around it and figure out the priority. Can we connect over discord? I am as user pghildiy on discord.

**Comment by sidkris77** [comment]
Sure. Havent used Discord before though. Seems I need some 4 digit tag to connect with you

**Comment by pghildiyal** [comment]
my handle is pghildiy#0981

**Comment by sidkris77** [comment]
Its a 4 digit tag

**Comment by prakarsh-dt** [comment]
Fixed by #937
