### ISSUE TITLE
App details page shows wrong user in deployed by section

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#845]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

In a pipeline if we have this setup -- Build --> pre-cd --> Deployment
Here pre-cd is set to manual trigger and deployment is set to auto trigger
Now if build was triggered by some other user and pre-CD by someone else then App details always shows the username of that person on every deployment who triggered the last build

**To Reproduce**

Steps to reproduce are included in description

**Expected behavior**

We should see the username of the person who triggered pre-cd in app details section

**Current behavior** 

We see the name of person who triggered last build in app details section

**Comment by prakarsh-dt** [comment]
This is resolved
