### ISSUE TITLE
Allow text to be copied from terminal UI

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#849]
# Summary

Text can be copied from logs and every other page from Devtron UI but in terminal nothing works, not even ctrl + c or right click and copy

# Motivation

This would be great as sometimes we need to copy some directory names or file names as it as to be used in extra containers or anywhere else we need

# Proposal

Would be good if it is same as logs, whole selected text is automatically copied to clipboard

**Comment by dhirendra10** [comment]
hi Guys,

can you please add this feature for linux/windows systems as well in coming releases, That will help us lot. Thanks in advance.
