### ISSUE TITLE
Support new CRD api in v1.22

### ISSUE THREAD

**Issue by iben12** [devtron-labs/devtron#850]
# Summary

Since Kubernetes v1.22 `apiextensions.k8s.io/v1beta1` is not supported for CustomResourceDefinitions. This prevents installing Devtron via helm, because it fails with the following error:
```
Error: INSTALLATION FAILED: failed to install CRD crds/crd-devtron.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```
Since v1.22 only the `apiextensions.k8s.io/v1` is supported.

# Motivation

I would like to install Devtron in a cluster on k8s version v1.22.3.

# Proposal

A future proof solution would be to include something like `useLegacyCrdApi` in the values and when it's enabled the CRDs could be rendered with the old API.  People could use that for old Kubernetes versions. Since `apiextensions.k8s.io/v1` is supported since v1.16 (which is quite old now) I suppose the number of affected users would be minimal.

**Comment by infra-bot-navarc** [comment]
I faced this exact this,  a simple `sed -i 's/apiextensions.k8s.io/v1beta1/apiextensions.k8s.io/v1/g` crds would work right? or is there something I'm missing?

**Comment by sachincool** [comment]
I faced this exact issue,  a simple `sed -i 's/apiextensions.k8s.io/v1beta1/apiextensions.k8s.io/v1/g` crds would work right? or is there something I'm missing?

**Comment by amalic** [comment]
Minikube is already on k8s 1.24. Would love to test drive devtron on my workstation.
