### ISSUE TITLE
New chart for Deployment on k8s 1.22 

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#869]
# Summary

Create a chart that supports deployments on kubernetes 1.22 via Devtron

# Motivation

K8s 1.22 is released and people have started using Devtron to do deployment on k8s 1.22 but face challenges because of the removed apiservices in k8s 1.22 like `extensions/v1beta1.ingress` 

# Proposal

Make a chart which is compatible with k8s 1.22 while also backwards compatible with lower k8s versions.

**Comment by amalic** [comment]
Hope this will also work for k8s 1.22
