### ISSUE TITLE
Make Devtron stack compatible with k8s 1.22

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#870]
# Summary

Devtron stack comes packaged with various tools which use their own CRDs which are incompatible with k8s 1.22. Upgrade them to make the stack compatible with k8s 1.22

# Motivation

People facing issues as they're trying to install Devtron on the k8s 1.22

# Proposal

Upgrade all the CRDs and outdated objects in the stack.

**Comment by Linutux** [comment]
I hope this gets approved soon. I also use K8S 1.22 and was disappointed I can't install devtron
