### ISSUE TITLE
App Config > "Git Repository" page shows error if git account is disabled

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#872]
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

If git account is disabled from global configuration, then Git repository page shows "We encountered an error"

**To Reproduce**

1. Have only 1 Git Account Added in Git accounts section
2. Create a new app
3. Move to App Configuration > Git Repository

**Expected behavior**

Error shouldn't be there, but I shouldn't be able to select any Git account from dropdown
OR
A message should be displayed to enable at least 1 Git Account first

**Current behavior** 

It just crashes with We encountered an error

**Comment by uxarya-d** [comment]
In this case, the Git Material > **Git Account dropdown should have been empty** as there was no active/enabled git account.
We already have a "Add Git Account" option in the dropdown which navigates the user to Global Config > Git Accounts.

So if the user doesn't find the desired git account in the dropdown, they can:
1. Click on "Add Git Account" and add the desired git account.
2. Click on "Add Git Account" and enable the disabled git account (As in this case).

**Comment by prakarsh-dt** [comment]
@dheeth Is this resolved? If yes, can you please close this issue?
