### ISSUE TITLE
Enable image-scanning by default globally

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#876]
# Summary

Currently, image-scanning check is present in each CI pipeline. Which means that the user creating a pipeline has to explicitly enable image scanning. This may result in image scan misses intentionally or unintentionally.

# Proposal

We believe image scanning should be enabled by default. Also administrators should be able to control turning it on or off at a Global level. Also image scanning config, **per CI level**, should be removed (as it acts as a backdoor which may lead to vulnerabilities).

For example, it can be provided as a switch in the `Security` section (screenshot below).
<img width="1259" alt="Screenshot 2021-11-19 at 2 34 12 PM" src="https://user-images.githubusercontent.com/87482092/142595571-e9bb7cdc-85b3-44dd-92a6-2df2934aa151.png">

We might also additionally show it on the Applications tab (screenshot below), to override scanning config for an app.
<img width="921" alt="Screenshot 2021-11-19 at 2 36 03 PM" src="https://user-images.githubusercontent.com/87482092/142595786-b7f2f95e-354f-4259-9500-31357111e009.png">

**Comment by nishant-d** [comment]
fixed.
