### ISSUE TITLE
Feature: Support bitbucket server/data center

### ISSUE THREAD

**Issue by pinguxx** [devtron-labs/devtron#877]
# Summary

Add support for bitbucket server

# Motivation

My company and most likely others uses bitbucket server to keep things in house

# Proposal

Create a dif client for bitbucket server, similar to cloud

AB#445

**Comment by Levy-Tal** [comment]
This is also what blocks us from using the tool

**Comment by Levy-Tal** [comment]
Bitbucket data center is still supported, And there is no plan to close it.
