### ISSUE TITLE
Can't install on k8s 1.22: failed to install CRD crds/crd-devtron-legacy.yaml: error parsing : json. 

### ISSUE THREAD

**Issue by Linutux** [devtron-labs/devtron#881]
**Describe the bug**

When trying to install devtron on Kubernetes 1.22 I get the following error:

$ helm repo add devtron https://helm.devtron.ai     "devtron" has been added to your repositories
$ helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd
Error: INSTALLATION FAILED: failed to install CRD crds/crd-devtron-legacy.yaml: error parsing : json: offset 2: invalid character '{' looking for beginning of object key string

**To Reproduce**

1. Execute "helm repo add devtron https://helm.devtron.ai" 
2. helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd
3. Install does not start

**Expected behavior**

Devtron should install. 

**Current behavior** 

Devtron does not install.

**Comment by Linutux** [comment]
I'm using Helm 3.7.1 (latest available) and Kubernetes 1.22.3.

**Comment by pghildiyal** [comment]
@Linutux can you please check if you are still facing the issue.

**Comment by Linutux** [comment]
> @Linutux can you please check if you are still facing the issue.

Not this issue, but an other:

Error: INSTALLATION FAILED: Chart.yaml file is missing

**Comment by Linutux** [comment]
* Helm delete repo devtron
* helm repo add devtron https://helm.devtron.ai
* helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd

**Comment by prakarsh-dt** [comment]
@Linutux Can you please do a helm repo update and then retry?

**Comment by Linutux** [comment]
> @Linutux Can you please do a helm repo update and then retry?

As you can see I tried Helm update. And also removing the repo alltogether and adding it again.

**Comment by prakarsh-dt** [comment]
@Linutux Can we connect on discord and try to reproduce this?

**Comment by Linutux** [comment]
@prakarsh-dt
I now did a  - - debug and Helm is not trying to install from the remote repo but from my home dir. 

I did a Helm pull and installed it from the source files.
