### ISSUE TITLE
Discord Live Chat integration

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#882]
# Summary

Add discord chat widget in the dashboard to enable users to directly connect for support in case they face any issue.

# Motivation

Enable users who face issues during dashboard usage to seamlessly reach out for support if needed.

# Proposal

Add discord live chat widget in the dashboard.

**Comment by manish-agrawal-ai** [comment]
Done

**Comment by dillfrescott** [comment]
Is there a way to disable the widget if I dont need it?
