### ISSUE TITLE
Git Accounts > Convey user to use token instead of password in case of github

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#883]
# Summary

Github has deprecated password usage.
Users face issue if they use password instead of token.

# Motivation

Lack of messaging on UI which hampers the workflow and leads to a negative experience.

# Proposal

Global Config > Git Accounts > Show a message: If using Github, use token instead of password.

https://www.figma.com/file/z5oh20tbYNDZkDQGrSYgol/Global-Configurations?node-id=1%3A89

**Comment by manish-agrawal-ai** [comment]
Fixed.
