### ISSUE TITLE
Bug: App detail > Clicking on commit info shows incorrect data.

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#885]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in Devtron Discord [channel](https://discord.gg/jsRG5qx2gp).

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Clicking on commit info on app detail page for an env, shows details for the last deployment made across envs.
ie. If last deployment in an app was on env1 and user checks commit info for env2. It still shows data for env1.

**To Reproduce**

Can't specify a specific app in which the issue can be reproduced as it depends upon the deployments made in the app.
Pls connect with @uxarya-d to try and reproduce the issue.

**Expected behavior**

Commit info should show info for the selected env.

**Current behavior** 

Commit info shows info for env on which last deployment was made.

**Screenshots**

![image](https://user-images.githubusercontent.com/73632042/142805553-474dccdb-a310-40e1-a0e4-de68a3223735.png)

AB#451

**Comment by prakarsh-dt** [comment]
@uxarya-d I think this is fixed. Can you confirm and close this issue?

**Comment by uxarya-d** [comment]
> @uxarya-d I think this is fixed. Can you confirm and close this issue?

Checked. Issue still persists.
