### ISSUE TITLE
Software Composition Analysis (SCA) via Devtron

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#913]
# Summary

We are considering using Devtron as an SCA tool, which can scan code/images and notify us of any vulnerabilities in our code. Devtron already provides a mechanism to scan Docker images, and to identify CVEs. We are looking at it to serve the following purposes:

1. Inventory of all open source softwares used in a repo.
2. License compliance.
3. Security Vulnerabilities (CVEs).

# Motivation

There are some orgs who have worked in this field. We can take inspiration from their solutions to build it inside Devtron.
E.g. [AboutCode](https://www.aboutcode.org/), [Owasp](https://owasp.org/), [Fossology](https://www.fossology.org/)

AB#450

**Comment by prakarsh-dt** [comment]
This is now supported, hence closing 
<img width="1021" alt="Screenshot 2024-07-30 at 5 37 19 PM" src="https://github.com/user-attachments/assets/e83118cf-4f1d-4f14-accb-fe934692e246">

<img width="1013" alt="Screenshot 2024-07-30 at 5 37 26 PM" src="https://github.com/user-attachments/assets/191793bf-a56f-419d-87ed-c977294ce709">
