### ISSUE TITLE
Static code analysis via Devtron

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#914]
# Summary

Devtron works well as a CI/CD tool. But it does not provide a mechanism to integrate any static code analysis tool.

# Proposal

We are looking at Devtron to provide a Global Plugin integration. Users should be able integrate any static code analysis tool (like Sonarqube), via a plugin, like in Jenkins. This would give them more options to integrate a tool of their choice and not force them to use a specific tool.

**Comment by shivani170** [comment]
Dependency:  https://github.com/devtron-labs/devtron/issues/1418

**Comment by prakarsh-dt** [comment]
Linked to https://github.com/devtron-labs/devtron/issues/1418 and released
