### ISSUE TITLE
Upgrade argocd version, it's still running on v1.8.1

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#924]
# Summary

Upgrade argocd to latest version so that we can use it's new features

# Motivation

There are some very useful updates in latest argocd like this annotation which I am not able to use with Devtron - argocd.argoproj.io/sync-options: Replace=true because this isn't supported on argocd v1.8 or even v2.0 it is supported on latest version & stable version only

**Comment by prakarsh-dt** [comment]
Argocd 2.4.0 included in Devtron v0.5.0
