### ISSUE TITLE
Missing a button in the UI to delete notification configurations

### ISSUE THREAD

**Issue by jonasschalck** [devtron-labs/devtron#925]
![Screenshot from 2021-12-03 10-29-30](https://user-images.githubusercontent.com/92308990/144579138-2159f1b3-7b69-4e57-8068-5692c7a95fe7.png)

I have a duplicated Slack configuration but no option to delete it.

**Comment by anupdhiran** [comment]
Will be closed as part of #929

**Comment by anupdhiran** [comment]
#929 is fixed and deployed which fixes this issue as well. Kindly verify and let us know in case you observe any issue.
