### ISSUE TITLE
Gitops repo to be prefixed with a unique identifier

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#933]
# Summary
Gitops repo to be prefixed with a unique identifier so that it doesn't overlaps with the source code repo name.

# Motivation
Some users want to evaluate Devtron and don't want to create a separate github organization / gitlab group for Devtron GitOps (although this is not recommended for Production use). This creates problem if they keep their devtron app name same as the name of their source code repo. 

# Proposal
Add a random prefix / unique identifier before creating the Devtron GitOps repo.

**Comment by manish-agrawal-ai** [comment]
changed assignee from Snehith to Nishant

**Comment by vikramdevtron** [comment]
- breaks into two parts 1) devtron apps, 2) devtron charts.

**Comment by vikramdevtron** [comment]
This ticket add prefixed for only devtron apps, it handle all existing and new git repo url. for charts proxy repo new ticket will be created separately.  https://github.com/devtron-labs/devtron/issues/1256
