### ISSUE TITLE
[EA FE] Replace App detail in Deployed Chart Section with New UI and Old features.

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#943]

**Comment by manish-agrawal-ai** [comment]
**Internal timelines :** 
Code Complete + Feedbacks by utkarsh  : 3 Days (hidden : Shivani will try to integrate this new UI with devtron app as well, but will not commit it) (by 8th EOD)
Testing by all or relevant people + Bug fixes by shivani : 4 days (by 14th EOD)
Code Review : 2 full day (parallelly with Testing) -> Manish :  (by 10th EOD)
Code review comments incorporate : 2 day -> Shivani : (by 14th EOD)
Deployment on Prod : 14th EOD or 15th EOD

**Comment by manish-agrawal-ai** [comment]
Dev delayed by two days. (Will complete by 10th EOD)

**Comment by anupdhiran** [comment]
Released in prod
