### ISSUE TITLE
Grafana label changes for compatibility with latest kube-state-metrics

### ISSUE THREAD

**Issue by prakarsh-dt** [devtron-labs/devtron#957]
# Summary

Grafana label changes for compatibility with latest kube-state-metrics v2.0.x and above

# Motivation

New kube-prometheus-stack has kube-state-metrics v2.0.x which has introduced a breaking change by automatically converting all camelCase labels to snake_case. 

# Proposal

To support this, we have to release a grafana graph that supports both the label formats.

**Comment by anupdhiran** [comment]
Work completed. Will be released in next release
