### ISSUE TITLE
User should be able to make certain changes from the trigger page

### ISSUE THREAD

**Issue by pghildiyal** [devtron-labs/devtron#960]
# Summary

User should be able to make certain changes from the trigger page
1. should be able to change branch name for build
2. should be able to change config for deployment

# Motivation

Currently user has to go to config page, make changes and then come back and retrigger. Providing them at same place would allow user to do it with fewer clicks

**Comment by uxarya-d** [comment]
Outcome:
1. Enable users to define a regex for branch name in CI pipelines, and allow them to switch between matching branches from trigger view
2. Identified multiple improvement areas around workflow view
