### ISSUE TITLE
can trigger build with `view only` permission

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#976]
Checklist:

* [X] I've searched in the docs and FAQ for my answer
* [X] I've included steps to reproduce the bug.

**Describe the bug**

Having `view only` permission but can trigger build.

**To Reproduce**

1. Create an app. with having admin access
2. Create workflow for the application.
3. Change the user access to `view only`
4. Trigger build

**Expected behavior**

Build shouldn't be triggered

**Current behavior** 

Can trigger build. 

**Screenshots**

**Logs**
 
```
Paste any relevant application logs here.
```

**Comment by kartik-579** [comment]
Fix for this issue will be included in PR for issue #1100.

**Comment by kartik-579** [comment]
Fix included in PR #1128
