### ISSUE TITLE
Can acess applications on environments without having permission

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#980]
Checklist:

* [X] I've searched in the docs and FAQ for my answer
* [X] I've included steps to reproduce the bug.

**Describe the bug**

Let's assume user have `view only` permission for all applications of 2 environments of a project. But one can access (View only) applications of other environments apart from having permissions.

**To Reproduce**

[ordered list the process to finding and recreating the issue, example below]

1. Create a project and add multiple environments for the projects.
2. Create applications inside all the environments of the project.
3. Add user having `view only` permission on a single environments.
4. Login as the user having the permission
5. Go to app list page.
6. You can see and access the apps of the environment for which you don't have permission.

**Expected behavior**

Can see and acces application of environments for which user have the access.

**Current behavior** 

Can access app of environments for which the user don't have permission.

**Screenshots**

**Logs**
 
```
Paste any relevant application logs here.
```

**Comment by kartik-579** [comment]
Fix included in #1128
