### ISSUE TITLE
[EA FE] Hide some features on ui for only EA module (Some buttons/tabs/API-calls)

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#983]
# Summary

user access: following apis are breaking
orchestrator/env/autocomplete
orchestrator/chart-group/list
orchestrator/app/min?teamIds=1

project: working fine
sso login service: working fine
cluster env:
/orchestrator/env -> endpoint breaking
UI fails to load

**Comment by nishant-d** [comment]
Hey @vivek-devtron I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/devtron-600cf5416a1159001797873d/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by anupdhiran** [comment]
Released in prod
