### ISSUE TITLE
Feature: Allow user to pass  docker build `Options` from UI

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#984]
# Summary

allow user to pass  docker build `Options` from UI

# Motivation

1. in certain cases user would like to control build behaviour using options like `--target, --platform` 
2. for running devtron in multi mode we want ability to pass `--target` flag in dockerfile like https://github.com/devtron-labs/devtron/blob/binary-executor-ea/Dockerfile

# Proposal

allow user to pass these params from the UI

AB#458

**Comment by prakarsh-dt** [comment]
Resolved by #2441
