### ISSUE TITLE
Latency charts should take input from user - P99.99%

### ISSUE THREAD

**Issue by pghildiyal** [devtron-labs/devtron#991]
# Summary

User should be able to select or provide latency percentile for the latency charts of App metrics.
Also in full screen view latency chart is not visible.

# Motivation

Currently average latency is shown to the user which is not very helpful. Usually people track 99 percentile or 99.99 percentile latencies to find if there is any issue with the service.

# Proposal

Provide a dropdown with prefilled values and also allow user to override the value with his/her own value.

**Comment by anupdhiran** [comment]
Released
