### ISSUE TITLE
Change nats streaming to jetstream

### ISSUE THREAD

**Issue by pghildiyal** [devtron-labs/devtron#996]
# Summary

Devtron uses nats streaming for persisitent streams since then nats has introduced jetsream for the same puropose. Devtron should migrate to using Jetstream instead of nats streaming.

# Motivation

Nats streaming gives problem when not used for considerable time. This results in broken experience for the user. Jetstream is natively built on top of nats and should not have this problem this will also reduce the maintainance overhead as user needs to manage only 1 component instead of 2

# Proposal

Change all usage of nats streaming to jetstream.

**Comment by anupdhiran** [comment]
Testing strategy : 
1. Regression test entire app
2. Regression test EA on a high level as EA doesn't use Nats
3. Monitor consumer events and verify that we are receiving all the published messages.

In addition to above, we'll keep the app idle for 4 days on the cluster as we have obersved issues with stan when kept idle. Need to make sure that we don't see similar issue with jetstream.
